// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

Model_Config :: struct {
    size:       [3]int,
    steps:      int,
    pixel_size: int,
    iso:        bool,
}

MODEL_NAMES := []string {
    "Apartemazements",
    "Backtracker",
    "BacktrackerCycle",
    "Basic",
    "BasicBrickWall",
    "BasicDijkstraDungeon",
    "BasicDijkstraFill",
    "BasicDungeonGrowth",
    "BasicKeys",
    "BasicPartitioning",
    "BasicSkyline",
    "BasicSnake",
    "BernoulliPercolation",
    "BiasedGrowth",
    "BiasedGrowthContraction",
    "BiasedMazeGrowth",
    "BiasedVoronoi",
    "BishopParity",
    "BlueNoise",
    "CarmaTower",
    "Cave",
    "CaveContour",
    "CentralCrawlers",
    "CentralSAW",
    "ChainDungeon",
    "ChainDungeonMaze",
    "ChainMaze",
    "Chase",
    "Circuit",
    "ClosedSurface",
    "ColoredKnots",
    "CompleteSAW",
    "CompleteSAWSmart",
    "ConnectedCaves",
    "ConstrainedCaves",
    "Counting",
    "Coupling",
    "Crawlers",
    "CrawlersChase",
    "CrossCountry",
    "Cycles",
    "DenseSAW",
    "DiagonalPath",
    "Digger",
    "DijkstraDungeon",
    "DualRetraction",
    "DualRetraction3D",
    "DungeonGrowth",
    "DwarfPath",
    "Dwarves",
    "Escher",
    "EscherSurface",
    "EuclideanPath",
    "FindLongCycle",
    "FireNoise",
    "Flowers",
    "Forest",
    "ForestFire",
    "ForestFireCA",
    "GameOfLife",
    "GoTo",
    "GoToGradient",
    "GrowTo",
    "Growth",
    "GrowthCompetition",
    "GrowthContraction",
    "GrowthWalk",
    "HamiltonianPath",
    "HamiltonianPaths",
    "Hills",
    "IrregularMazeGrowth",
    "IrregularSAW",
    "Island",
    "Keys",
    "KnightPatrol",
    "Knots2D",
    "Knots3D",
    "Laplace",
    "Lightning",
    "LoopErasedWalk",
    "LoopGrowth",
    "LostCity",
    "MarchingSquares",
    "MazeBacktracker",
    "MazeGrowth",
    "MazeMap",
    "MazeTrail",
    "ModernHouse",
    "MultiHeadedDungeon",
    "MultiHeadedWalk",
    "MultiHeadedWalkDungeon",
    "MultiSokoban8",
    "MultiSokoban9",
    "NestedGrowth",
    "NoDeadEnds",
    "Noise",
    "NystromDungeon",
    "OddScale",
    "OddScale3D",
    "OpenCave",
    "OpenCave3D",
    "OrganicMechanic",
    "OrientedEscher",
    "PaintCompetition",
    "ParallelGrowth",
    "ParallelMazeGrowth",
    "ParallelWalk",
    "Partitioning",
    "Percolation",
    "PeriodicEscher",
    "PillarsOfEternity",
    "Push",
    "PutColoredLs",
    "PutLs",
    "RainbowGrowth",
    "RandomWalk",
    "Rectangle",
    "RegularPath",
    "RegularSAW",
    "RegularSAWRestart",
    "River",
    "SAWRestart",
    "SeaVilla",
    "SelectLargeCaves",
    "SelectLongKnots",
    "SelfAvoidingWalk",
    "SequentialSnake",
    "SequentialSokoban",
    "Sewers",
    "SmartSAW",
    "SmarterDigger",
    "SmoothTrail",
    "Snake",
    "SnellLaw",
    "SoftPath",
    "SokobanLevel1",
    "SokobanLevel2",
    "StableCrawlers",
    "StairsPath",
    "StochasticVoronoi",
    "StormySnellLaw",
    "StrangeDungeon",
    "StrangeGrowth",
    "StrangeNoise",
    "SubmergedKnots",
    "Surface",
    "Tetris",
    "Texture",
    "TileDungeon",
    "TilePath",
    "Trail",
    "Voronoi",
    "WaveBrickWall",
    "WaveDungeon",
    "WaveFlowers",
    "Wilson",
    "WolfBasedApproach",
}

default_model_config :: proc(name: string) -> (Model_Config, bool) {
    switch name {
    case "Apartemazements":
        return Model_Config{size = {8, 8, 8}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Backtracker":
        return Model_Config{size = {89, 89, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BacktrackerCycle":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Basic":
        return Model_Config{size = {60, 60, 1}, steps = 1000, pixel_size = 4, iso = false}, true
    case "BasicBrickWall":
        return Model_Config{size = {30, 30, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BasicDijkstraDungeon":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BasicDijkstraFill":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BasicDungeonGrowth":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BasicKeys":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BasicPartitioning":
        return Model_Config{size = {60, 60, 1}, steps = 1000, pixel_size = 4, iso = false}, true
    case "BasicSkyline":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BasicSnake":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BernoulliPercolation":
        return Model_Config{size = {359, 359, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BiasedGrowth":
        return Model_Config{size = {120, 120, 1}, steps = 1000, pixel_size = 4, iso = false}, true
    case "BiasedGrowthContraction":
        return Model_Config{size = {120, 120, 1}, steps = 5000, pixel_size = 4, iso = false}, true
    case "BiasedMazeGrowth":
        return Model_Config{size = {117, 117, 1}, steps = 400, pixel_size = 4, iso = false}, true
    case "BiasedVoronoi":
        return Model_Config{size = {80, 80, 1}, steps = 1000, pixel_size = 4, iso = false}, true
    case "BishopParity":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "BlueNoise":
        return Model_Config{size = {80, 80, 1}, steps = 500, pixel_size = 4, iso = false}, true
    case "CarmaTower":
        return Model_Config{size = {12, 12, 18}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Cave":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "CaveContour":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "CentralCrawlers":
        return Model_Config{size = {60, 60, 1}, steps = 300, pixel_size = 4, iso = false}, true
    case "CentralSAW":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "ChainDungeon":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "ChainDungeonMaze":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "ChainMaze":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Chase":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Circuit":
        return Model_Config{size = {59, 59, 1}, steps = 1200, pixel_size = 4, iso = false}, true
    case "ClosedSurface":
        return Model_Config{size = {12, 12, 12}, steps = 50000, pixel_size = 4, iso = false}, true
    case "ColoredKnots":
        return Model_Config{size = {12, 12, 12}, steps = 50000, pixel_size = 4, iso = false}, true
    case "CompleteSAW":
        return Model_Config{size = {19, 19, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "CompleteSAWSmart":
        return Model_Config{size = {23, 23, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "ConnectedCaves":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "ConstrainedCaves":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Counting":
        return Model_Config{size = {8, 8, 8}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Coupling":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Crawlers":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "CrawlersChase":
        return Model_Config{size = {60, 60, 1}, steps = 200, pixel_size = 4, iso = false}, true
    case "CrossCountry":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Cycles":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "DenseSAW":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "DiagonalPath":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Digger":
        return Model_Config{size = {359, 359, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "DijkstraDungeon":
        return Model_Config{size = {40, 40, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "DualRetraction":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "DualRetraction3D":
        return Model_Config{size = {27, 27, 27}, steps = 50000, pixel_size = 4, iso = false}, true
    case "DungeonGrowth":
        return Model_Config{size = {79, 79, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "DwarfPath":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Dwarves":
        return Model_Config{size = {20, 20, 1}, steps = 85, pixel_size = 4, iso = false}, true
    case "Escher":
        return Model_Config{size = {8, 8, 8}, steps = 50000, pixel_size = 4, iso = false}, true
    case "EscherSurface":
        return Model_Config{size = {8, 8, 8}, steps = 50000, pixel_size = 4, iso = false}, true
    case "EuclideanPath":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "FindLongCycle":
        return Model_Config{size = {27, 27, 1}, steps = 50000, pixel_size = 10, iso = false}, true
    case "FireNoise":
        return Model_Config{size = {300, 300, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Flowers":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Forest":
        return Model_Config{size = {240, 240, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "ForestFire":
        return Model_Config{size = {600, 600, 1}, steps = 80, pixel_size = 1, iso = false}, true
    case "ForestFireCA":
        return Model_Config{size = {600, 600, 1}, steps = 80, pixel_size = 1, iso = false}, true
    case "GameOfLife":
        return Model_Config{size = {120, 120, 1}, steps = 100, pixel_size = 4, iso = false}, true
    case "GoTo":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "GoToGradient":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "GrowTo":
        return Model_Config{size = {120, 120, 1}, steps = 2000, pixel_size = 4, iso = false}, true
    case "Growth":
        return Model_Config{size = {359, 359, 1}, steps = 40000, pixel_size = 4, iso = false}, true
    case "GrowthCompetition":
        return Model_Config{size = {80, 80, 1}, steps = 30000, pixel_size = 4, iso = false}, true
    case "GrowthContraction":
        return Model_Config{size = {79, 79, 1}, steps = 10000, pixel_size = 4, iso = false}, true
    case "GrowthWalk":
        return Model_Config{size = {79, 79, 1}, steps = 5000, pixel_size = 4, iso = false}, true
    case "HamiltonianPath":
        return Model_Config{size = {39, 39, 1}, steps = 150000, pixel_size = 4, iso = false}, true
    case "HamiltonianPaths":
        return Model_Config{size = {39, 39, 1}, steps = 1000, pixel_size = 4, iso = false}, true
    case "Hills":
        return Model_Config{size = {40, 40, 40}, steps = 50000, pixel_size = 4, iso = false}, true
    case "IrregularMazeGrowth":
        return Model_Config{size = {79, 79, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "IrregularSAW":
        return Model_Config{size = {79, 79, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Island":
        return Model_Config{size = {800, 800, 1}, steps = -1, pixel_size = 1, iso = false}, true
    case "Keys":
        return Model_Config{size = {33, 33, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "KnightPatrol":
        return Model_Config{size = {60, 60, 1}, steps = 200, pixel_size = 4, iso = false}, true
    case "Knots2D":
        return Model_Config{size = {12, 12, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Knots3D":
        return Model_Config{size = {8, 8, 8}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Laplace":
        return Model_Config{size = {60, 60, 1}, steps = 1000, pixel_size = 4, iso = false}, true
    case "Lightning":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "LoopErasedWalk":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "LoopGrowth":
        return Model_Config{size = {37, 37, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "LostCity":
        return Model_Config{size = {256, 256, 1}, steps = 50000, pixel_size = 3, iso = false}, true
    case "MarchingSquares":
        return Model_Config{size = {20, 20, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "MazeBacktracker":
        return Model_Config{size = {359, 359, 1}, steps = 20000, pixel_size = 4, iso = false}, true
    case "MazeGrowth":
        return Model_Config{size = {359, 359, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "MazeMap":
        return Model_Config{size = {30, 30, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "MazeTrail":
        return Model_Config{size = {59, 59, 1}, steps = 1000, pixel_size = 4, iso = false}, true
    case "ModernHouse":
        return Model_Config{size = {9, 9, 4}, steps = 50000, pixel_size = 4, iso = false}, true
    case "MultiHeadedDungeon":
        return Model_Config{size = {55, 55, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "MultiHeadedWalk":
        return Model_Config{size = {99, 99, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "MultiHeadedWalkDungeon":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "MultiSokoban8":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "MultiSokoban9":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "NestedGrowth":
        return Model_Config{size = {80, 80, 1}, steps = 100, pixel_size = 4, iso = false}, true
    case "NoDeadEnds":
        return Model_Config{size = {39, 39, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Noise":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "NystromDungeon":
        return Model_Config{size = {39, 39, 1}, steps = 50000, pixel_size = 8, iso = false}, true
    case "OddScale":
        return Model_Config{size = {8, 8, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "OddScale3D":
        return Model_Config{size = {8, 8, 8}, steps = 50000, pixel_size = 4, iso = false}, true
    case "OpenCave":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "OpenCave3D":
        return Model_Config{size = {40, 40, 40}, steps = 50000, pixel_size = 4, iso = false}, true
    case "OrganicMechanic":
        return Model_Config{size = {30, 30, 1}, steps = 200, pixel_size = 4, iso = false}, true
    case "OrientedEscher":
        return Model_Config{size = {6, 6, 6}, steps = 50000, pixel_size = 4, iso = false}, true
    case "PaintCompetition":
        return Model_Config{size = {48, 48, 1}, steps = 400, pixel_size = 4, iso = false}, true
    case "ParallelGrowth":
        return Model_Config{size = {29, 29, 29}, steps = 24, pixel_size = 4, iso = false}, true
    case "ParallelMazeGrowth":
        return Model_Config{size = {179, 179, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "ParallelWalk":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Partitioning":
        return Model_Config{size = {11, 11, 3}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Percolation":
        return Model_Config{size = {360, 360, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "PeriodicEscher":
        return Model_Config{size = {8, 8, 8}, steps = 50000, pixel_size = 4, iso = false}, true
    case "PillarsOfEternity":
        return Model_Config{size = {9, 9, 9}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Push":
        return Model_Config{size = {40, 40, 1}, steps = 8000, pixel_size = 4, iso = false}, true
    case "PutColoredLs":
        return Model_Config{size = {30, 30, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "PutLs":
        return Model_Config{size = {50, 50, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "RainbowGrowth":
        return Model_Config{size = {59, 59, 1}, steps = 1600, pixel_size = 4, iso = false}, true
    case "RandomWalk":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Rectangle":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "RegularPath":
        return Model_Config{size = {79, 79, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "RegularSAW":
        return Model_Config{size = {39, 39, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "RegularSAWRestart":
        return Model_Config{size = {39, 39, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "River":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SAWRestart":
        return Model_Config{size = {79, 79, 1}, steps = 2000, pixel_size = 4, iso = false}, true
    case "SeaVilla":
        return Model_Config{size = {10, 10, 4}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SelectLargeCaves":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SelectLongKnots":
        return Model_Config{size = {10, 10, 10}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SelfAvoidingWalk":
        return Model_Config{size = {39, 39, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SequentialSnake":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SequentialSokoban":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Sewers":
        return Model_Config{size = {40, 40, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SmartSAW":
        return Model_Config{size = {19, 19, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SmarterDigger":
        return Model_Config{size = {40, 40, 1}, steps = 800, pixel_size = 4, iso = false}, true
    case "SmoothTrail":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Snake":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SnellLaw":
        return Model_Config{size = {80, 80, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SoftPath":
        return Model_Config{size = {180, 180, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SokobanLevel1":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "SokobanLevel2":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "StableCrawlers":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "StairsPath":
        return Model_Config{size = {33, 33, 33}, steps = 50000, pixel_size = 4, iso = false}, true
    case "StochasticVoronoi":
        return Model_Config{size = {200, 200, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "StormySnellLaw":
        return Model_Config{size = {120, 120, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "StrangeDungeon":
        return Model_Config{size = {59, 59, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "StrangeGrowth":
        return Model_Config{size = {59, 59, 1}, steps = 700, pixel_size = 4, iso = false}, true
    case "StrangeNoise":
        return Model_Config{size = {60, 60, 1}, steps = 500, pixel_size = 4, iso = false}, true
    case "SubmergedKnots":
        return Model_Config{size = {12, 12, 12}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Surface":
        return Model_Config{size = {10, 10, 10}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Tetris":
        return Model_Config{size = {30, 30, 1}, steps = 1500, pixel_size = 4, iso = false}, true
    case "Texture":
        return Model_Config{size = {240, 240, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "TileDungeon":
        return Model_Config{size = {12, 12, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "TilePath":
        return Model_Config{size = {20, 20, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Trail":
        return Model_Config{size = {59, 59, 1}, steps = 3000, pixel_size = 4, iso = false}, true
    case "Voronoi":
        return Model_Config{size = {240, 240, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "WaveBrickWall":
        return Model_Config{size = {50, 50, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "WaveDungeon":
        return Model_Config{size = {50, 50, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "WaveFlowers":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "Wilson":
        return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}, true
    case "WolfBasedApproach":
        return Model_Config{size = {70, 70, 1}, steps = 300, pixel_size = 4, iso = false}, true
    }
    return {}, false
}

model_override_color :: proc(name: string, symbol: u8) -> (i32, bool) {
    switch name {
    case "Island":
        switch symbol {
        case 'I':
            return transmute(i32)u32(0xff000000 | 0xabcbe8), true
        case 'U':
            return transmute(i32)u32(0xff000000 | 0xcee6f9), true
        case 'T':
            return transmute(i32)u32(0xff000000 | 0x2b8aa9), true
        case 'Y':
            return transmute(i32)u32(0xff000000 | 0xf1ebc2), true
        case 'G':
            return transmute(i32)u32(0xff000000 | 0xa8d1a5), true
        case 'E':
            return transmute(i32)u32(0xff000000 | 0x93c08d), true
        case 'S':
            return transmute(i32)u32(0xff000000 | 0xd0d8ac), true
        case 's':
            return transmute(i32)u32(0xff000000 | 0xe9e0b2), true
        }
    }
    return 0, false
}
