// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_rainbowgrowth :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(8)),
        mk.kattr(.origin, true),
        mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{1, 2})),
        mk.rule(mk.in_exact_layer([]int{2, 0}), mk.out_exact_layer([]int{2, 3})),
        mk.rule(mk.in_exact_layer([]int{3, 0}), mk.out_exact_layer([]int{3, 4})),
        mk.rule(mk.in_exact_layer([]int{4, 0}), mk.out_exact_layer([]int{4, 5})),
        mk.rule(mk.in_exact_layer([]int{5, 0}), mk.out_exact_layer([]int{5, 6})),
        mk.rule(mk.in_exact_layer([]int{6, 0}), mk.out_exact_layer([]int{6, 7})),
        mk.rule(mk.in_exact_layer([]int{7, 0}), mk.out_exact_layer([]int{7, 1})),
    )
}
