// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_euclideanpath :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(7)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 6, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.steps, 8),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{6})),
            mk.kattr(.out, mk.out_exact_layer([]int{5})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{6})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 1),
            mk.field_node(
                mk.kattr(.for_, mk.sym(1)),
                mk.kattr(.from_, mk.one_of(mk.sym(5))),
                mk.kattr(.on, mk.one_of(mk.sym(0), mk.sym(6))),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{6})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 1),
            mk.field_node(
                mk.kattr(.for_, mk.sym(2)),
                mk.kattr(.from_, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0), mk.sym(6))),
            ),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{0})),
            mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{0})),
        ),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{3, 4})),
            mk.rule(mk.in_exact_layer([]int{4}), mk.out_exact_layer([]int{1})),
            mk.rule(
                mk.in_exact_layer([]int{1, mk.IN_ANY}, []int{mk.IN_ANY, 0}),
                mk.out_exact_layer([]int{3, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 5}),
            ),
            mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{6})),
            mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{1})),
            mk.observe_node(
                mk.kattr(.value, mk.sym(2)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(3)))),
            mk.observe_node(mk.kattr(.value, mk.sym(1)), mk.kattr(.to, mk.one_of(mk.sym(3)))),
        ),
    )
}
