// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_centralsaw :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.origin, true),
        mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0})),
        mk.kattr(.out, mk.out_exact_layer([]int{2, 2, 1})),
        mk.kattr(.temperature, 0.1),
        mk.field_node(
            mk.kattr(.for_, mk.sym(2)),
            mk.kattr(.to, mk.one_of(mk.sym(1))),
            mk.kattr(.on, mk.one_of(mk.sym(0))),
            mk.kattr(.recompute, false),
        ),
    )
}
