// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_dualretraction :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.kattr(.origin, true),
        mk.one(
            mk.rule(
                mk.in_exact_layer(
                    []int{0, 0, mk.IN_ANY, 0, 0},
                    []int{0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 1},
                    []int{0, 0, 0, 0, 0},
                    []int{0, 0, mk.IN_ANY, 0, 0},
                ),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 3, 3, 3, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 3, 3, 3, 2},
                    []int{mk.OUT_KEEP, 3, 3, 3, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.rule(
                mk.in_exact_layer(
                    []int{0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0},
                    []int{1, 0, 0, 0, mk.IN_ANY},
                    []int{0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0},
                ),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{2, 3, 3, 3, 1},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{3})),
            mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{3})),
        ),
        mk.all(
            mk.rule(
                mk.in_exact_layer([]int{0, 0, 0}, []int{0, 3, 0}),
                mk.out_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{3, 3, 3}, []int{3, 0, 3}),
                mk.out_exact_layer([]int{3, 3, 3}, []int{3, 3, 3}),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{3, 3, 0}, []int{3, 3, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
    )
}
