// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_backtracker :: proc() -> mk.Proc_Node {
    return mk.markov_node(
        mk.kattr(.values, mk.values_count(4)),
        mk.kattr(.origin, true),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})), mk.kattr(.out, mk.out_exact_layer([]int{2, 1}))),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1, 2})), mk.kattr(.out, mk.out_exact_layer([]int{3, 1}))),
    )
}
