// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_lightning :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 1),
        ),
        mk.markov_node(
            mk.one(
                mk.rule(mk.in_exact_layer([]int{2, 4}), mk.out_exact_layer([]int{mk.OUT_KEEP, 5})),
                mk.rule(mk.in_exact_layer([]int{5, 4}), mk.out_exact_layer([]int{mk.OUT_KEEP, 5})),
                mk.rule(mk.in_exact_layer([]int{5, 3}), mk.out_exact_layer([]int{mk.OUT_KEEP, 0})),
            ),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(2))),
                mk.kattr(.to, mk.one_of(mk.sym(3))),
                mk.kattr(.on, mk.one_of(mk.sym(1))),
                mk.kattr(.color, mk.sym(4)),
            ),
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{5})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
        ),
    )
}
