// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_completesawsmart :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(7)),
        mk.kattr(.origin, true),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{2, mk.IN_ANY, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 1})),
            mk.rule(mk.in_exact_layer([]int{1, mk.IN_ANY, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 2})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 2})),
            mk.kattr(.out, mk.out_exact_layer([]int{3, 4, mk.OUT_KEEP})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{5})),
            mk.kattr(.steps, 1),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        mk.one(
            mk.kattr(.search, true),
            mk.kattr(.limit, 300),
            mk.kattr(.depth_coefficient, -1.0),
            mk.rule(mk.in_exact_layer([]int{3, 4, 0, 0, 0}), mk.out_exact_layer([]int{6, 6, 3, 4, mk.OUT_KEEP})),
            mk.rule(mk.in_exact_layer([]int{3, 4, 0, 0, 5}), mk.out_exact_layer([]int{6, 6, 6, 6, 3})),
            mk.rule(
                mk.in_exact_layer([]int{0, 0, 0}, []int{4, mk.IN_ANY, mk.IN_ANY}, []int{3, mk.IN_ANY, mk.IN_ANY}),
                mk.out_exact_layer(
                    []int{3, 4, mk.OUT_KEEP},
                    []int{6, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{6, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.rule(
                mk.in_exact_layer([]int{0, 0, 5}, []int{4, mk.IN_ANY, mk.IN_ANY}, []int{3, mk.IN_ANY, mk.IN_ANY}),
                mk.out_exact_layer(
                    []int{6, 6, 3},
                    []int{6, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{6, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.observe_node(
                mk.kattr(.value, mk.sym(2)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(6))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(3)), mk.kattr(.to, mk.one_of(mk.sym(6)))),
            mk.observe_node(mk.kattr(.value, mk.sym(4)), mk.kattr(.to, mk.one_of(mk.sym(6)))),
            mk.observe_node(mk.kattr(.value, mk.sym(5)), mk.kattr(.to, mk.one_of(mk.sym(3)))),
            mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(6)))),
        ),
    )
}
