// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_nestedgrowth :: proc() -> mk.Proc_Node {
    return mk.all(
        mk.kattr(.values, mk.values_count(4)),
        mk.kattr(.origin, true),
        mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{1, 1})),
        mk.rule(mk.in_exact_layer([]int{1, 3}), mk.out_exact_layer([]int{1, 1})),
        mk.rule(mk.in_exact_layer([]int{2, 1}), mk.out_exact_layer([]int{2, 2})),
        mk.rule(mk.in_exact_layer([]int{3, 2}), mk.out_exact_layer([]int{3, 3})),
        mk.rule(
            mk.in_exact_layer(
                []int{mk.IN_ANY, 1, 1, 1, mk.IN_ANY},
                []int{1, 1, 1, 1, 1},
                []int{1, 1, 1, 1, 1},
                []int{1, 1, 1, 1, 1},
                []int{mk.IN_ANY, 1, 1, 1, mk.IN_ANY},
            ),
            mk.out_exact_layer(
                []int{mk.OUT_KEEP, 1, 1, 1, mk.OUT_KEEP},
                []int{1, 1, 1, 1, 1},
                []int{1, 1, 2, 1, 1},
                []int{1, 1, 1, 1, 1},
                []int{mk.OUT_KEEP, 1, 1, 1, mk.OUT_KEEP},
            ),
        ),
        mk.rule(
            mk.in_exact_layer(
                []int{mk.IN_ANY, 1, 1, 1, mk.IN_ANY},
                []int{1, 1, 1, 1, 1},
                []int{1, 1, 1, 1, 1},
                []int{1, 1, 1, 1, 1},
                []int{mk.IN_ANY, 1, 1, 1, mk.IN_ANY},
            ),
            mk.out_exact_layer(
                []int{mk.OUT_KEEP, 1, 1, 1, mk.OUT_KEEP},
                []int{1, 1, 1, 1, 1},
                []int{1, 1, 1, 1, 1},
                []int{1, 1, 1, 1, 1},
                []int{mk.OUT_KEEP, 1, 1, 1, mk.OUT_KEEP},
            ),
        ),
        mk.rule(
            mk.in_exact_layer(
                []int{mk.IN_ANY, 2, 2, 2, mk.IN_ANY},
                []int{2, 2, 2, 2, 2},
                []int{2, 2, 2, 2, 2},
                []int{2, 2, 2, 2, 2},
                []int{mk.IN_ANY, 2, 2, 2, mk.IN_ANY},
            ),
            mk.out_exact_layer(
                []int{mk.OUT_KEEP, 2, 2, 2, mk.OUT_KEEP},
                []int{2, 2, 2, 2, 2},
                []int{2, 2, 3, 2, 2},
                []int{2, 2, 2, 2, 2},
                []int{mk.OUT_KEEP, 2, 2, 2, mk.OUT_KEEP},
            ),
        ),
        mk.rule(
            mk.in_exact_layer(
                []int{mk.IN_ANY, 2, 2, 2, mk.IN_ANY},
                []int{2, 2, 2, 2, 2},
                []int{2, 2, 2, 2, 2},
                []int{2, 2, 2, 2, 2},
                []int{mk.IN_ANY, 2, 2, 2, mk.IN_ANY},
            ),
            mk.out_exact_layer(
                []int{mk.OUT_KEEP, 2, 2, 2, mk.OUT_KEEP},
                []int{2, 2, 2, 2, 2},
                []int{2, 2, 2, 2, 2},
                []int{2, 2, 2, 2, 2},
                []int{mk.OUT_KEEP, 2, 2, 2, mk.OUT_KEEP},
            ),
        ),
        mk.rule(
            mk.in_exact_layer(
                []int{mk.IN_ANY, 3, 3, 3, mk.IN_ANY},
                []int{3, 3, 3, 3, 3},
                []int{3, 3, 3, 3, 3},
                []int{3, 3, 3, 3, 3},
                []int{mk.IN_ANY, 3, 3, 3, mk.IN_ANY},
            ),
            mk.out_exact_layer(
                []int{mk.OUT_KEEP, 3, 3, 3, mk.OUT_KEEP},
                []int{3, 3, 3, 3, 3},
                []int{3, 3, 1, 3, 3},
                []int{3, 3, 3, 3, 3},
                []int{mk.OUT_KEEP, 3, 3, 3, mk.OUT_KEEP},
            ),
        ),
        mk.rule(
            mk.in_exact_layer(
                []int{mk.IN_ANY, 3, 3, 3, mk.IN_ANY},
                []int{3, 3, 3, 3, 3},
                []int{3, 3, 3, 3, 3},
                []int{3, 3, 3, 3, 3},
                []int{mk.IN_ANY, 3, 3, 3, mk.IN_ANY},
            ),
            mk.out_exact_layer(
                []int{mk.OUT_KEEP, 3, 3, 3, mk.OUT_KEEP},
                []int{3, 3, 3, 3, 3},
                []int{3, 3, 3, 3, 3},
                []int{3, 3, 3, 3, 3},
                []int{mk.OUT_KEEP, 3, 3, 3, mk.OUT_KEEP},
            ),
        ),
    )
}
