// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_putcoloredls :: proc() -> mk.Proc_Node {
    return mk.markov_node(
        mk.kattr(.values, mk.values_count(5)),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{2, 1}), mk.out_exact_layer([]int{2, 2})),
            mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{3, 3})),
            mk.rule(mk.in_exact_layer([]int{4, 1}), mk.out_exact_layer([]int{4, 4})),
        ),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{2})),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{3})),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{4})),
        ),
        mk.one(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{0, 0, 0, mk.IN_ANY},
                    []int{0, 0, 0, mk.IN_ANY},
                    []int{0, 0, 0, 0},
                    []int{0, 0, 0, 0},
                    []int{0, 0, 0, 0},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{0, 0, 0, mk.OUT_KEEP},
                    []int{0, 1, 0, mk.OUT_KEEP},
                    []int{0, 1, 0, 0},
                    []int{0, 1, 1, 0},
                    []int{0, 0, 0, 0},
                ),
            ),
        ),
    )
}
