// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_eschersurface :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layers(
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, 1, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.values, mk.values_count(4)),
            mk.kattr(.tileset, "EscherSurface"),
            mk.rule(mk.sym(1), "Empty"),
            mk.all(
                mk.rule(mk.in_exact_layer([]int{1, 0, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 1, mk.OUT_KEEP})),
                mk.rule(mk.in_exact_layer([]int{3, 0, 3}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3, mk.OUT_KEEP})),
                mk.rule(mk.in_exact_layer([]int{2, 0, 2}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2, mk.OUT_KEEP})),
            ),
        ),
    )
}
