// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_carmatower :: proc() -> Model_Config {
    return Model_Config{size = {12, 12, 18}, steps = 50000, pixel_size = 4, iso = false}
}

model_palette_symbol_carmatower :: proc(value: int) -> (u8, bool) {
    values := "BtTRL"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_carmatower :: proc(value: int) -> (i32, bool) {
    return 0, false
}
