// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_snake :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(9)),
        mk.kattr(.origin, true),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 1})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 1, 0}, []int{0, 0, 0}, []int{0, 1, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{6, 4, 2},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.steps, 1),
        ),
        mk.markov_node(
            mk.one(
                mk.rule(mk.in_exact_layer([]int{2, 1, 8}), mk.out_exact_layer([]int{4, 4, 2})),
                mk.rule(mk.in_exact_layer([]int{2, 1, 1}), mk.out_exact_layer([]int{5, 5, 3})),
                mk.rule(mk.in_exact_layer([]int{4, 4, 5}), mk.out_exact_layer([]int{5, 5, 5})),
                mk.rule(mk.in_exact_layer([]int{6, 4, 5}), mk.out_exact_layer([]int{0, 0, 7})),
            ),
            mk.all(
                mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{4})),
                mk.rule(mk.in_exact_layer([]int{3}), mk.out_exact_layer([]int{2})),
                mk.rule(mk.in_exact_layer([]int{7}), mk.out_exact_layer([]int{6})),
            ),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(2))),
                mk.kattr(.to, mk.one_of(mk.sym(8))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.color, mk.sym(1)),
                mk.kattr(.inertia, true),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 1}, []int{0, 0, 0}, []int{1, 0, 1})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 8, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
            ),
        ),
    )
}
