// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_periodicescher :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, 1, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 0, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.values, mk.values_count(7)),
            mk.kattr(.tileset, "Escher"),
            mk.kattr(.periodic, true),
            mk.rule(mk.sym(1), "Empty"),
            mk.sequence(
                mk.all(
                    mk.rule(mk.in_exact_layer([]int{2, 0, 2}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2, mk.OUT_KEEP})),
                    mk.rule(mk.in_exact_layer([]int{1, 0, 2}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2, mk.OUT_KEEP})),
                ),
                mk.all(
                    mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_IDENTITY)),
                    mk.rule(mk.in_exact_layer([]int{3, 6}), mk.out_exact_layer([]int{3, 0})),
                    mk.rule(mk.in_exact_layer([]int{3}, []int{6}), mk.out_exact_layer([]int{4}, []int{0})),
                    mk.rule(
                        mk.in_exact_layers([][]int{[]int{6}}, [][]int{[]int{3}}),
                        mk.out_exact_layers([][]int{[]int{0}}, [][]int{[]int{5}}),
                    ),
                    mk.rule(mk.in_exact_layer([]int{6, 3}), mk.out_exact_layer([]int{0, 6})),
                    mk.rule(mk.in_exact_layer([]int{6}, []int{3}), mk.out_exact_layer([]int{0}, []int{6})),
                    mk.rule(
                        mk.in_exact_layers([][]int{[]int{3}}, [][]int{[]int{6}}),
                        mk.out_exact_layers([][]int{[]int{6}}, [][]int{[]int{0}}),
                    ),
                ),
            ),
        ),
    )
}
