// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_biasedvoronoi :: proc() -> Model_Config {
    return Model_Config{size = {80, 80, 1}, steps = 1000, pixel_size = 4, iso = false}
}

model_palette_symbol_biasedvoronoi :: proc(value: int) -> (u8, bool) {
    values := "BOS"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_biasedvoronoi :: proc(value: int) -> (i32, bool) {
    return 0, false
}
