// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_parallelwalk :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 24),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})), mk.kattr(.out, mk.out_exact_layer([]int{0, 1}))),
    )
}
