// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_nystromdungeon :: proc() -> Model_Config {
    return Model_Config{size = {39, 39, 1}, steps = 50000, pixel_size = 8, iso = false}
}

model_palette_symbol_nystromdungeon :: proc(value: int) -> (u8, bool) {
    values := "BPWRG"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_nystromdungeon :: proc(value: int) -> (i32, bool) {
    return 0, false
}
