// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_firenoise :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.prl(
            mk.kattr(.steps, 75),
            mk.rule(mk.in_exact_layer([]int{2, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
            mk.rule(
                mk.in_exact_layer([]int{2, mk.IN_ANY}, []int{mk.IN_ANY, 1}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 2}),
            ),
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{1}), mk.kattr(.p, 0.01)),
            mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{0})),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{2}), mk.kattr(.p, 0.0001)),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY, 1, mk.IN_ANY}, []int{1, 0, 1})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 1, mk.OUT_KEEP}),
            ),
        ),
        mk.all(
            mk.rule(
                mk.in_exact_layer([]int{mk.IN_ANY, 0, mk.IN_ANY}, []int{0, 1, 0}, []int{mk.IN_ANY, 0, mk.IN_ANY}),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.rule(
                mk.in_exact_layer(
                    []int{mk.IN_ANY, 0, 0, mk.IN_ANY},
                    []int{0, 1, 1, 0},
                    []int{mk.IN_ANY, 0, 0, mk.IN_ANY},
                ),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 0, 0, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.markov_node(
            mk.sequence(
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{1})),
                    mk.kattr(.out, mk.out_exact_layer([]int{4})),
                    mk.kattr(.steps, 1),
                ),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{4, 1})),
                    mk.kattr(.out, mk.out_exact_layer([]int{4, 4})),
                    mk.kattr(.steps, 10),
                ),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{4, 1})),
                    mk.kattr(.out, mk.out_exact_layer([]int{3, 3})),
                ),
                mk.all(
                    mk.rule(mk.in_exact_layer([]int{3, 4}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
                    mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
                ),
            ),
        ),
        mk.markov_node(
            mk.sequence(
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{0})),
                    mk.kattr(.out, mk.out_exact_layer([]int{5})),
                    mk.kattr(.steps, 1),
                ),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{5, 0})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 5})),
                    mk.kattr(.steps, 10),
                ),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{5, 0})),
                    mk.kattr(.out, mk.out_exact_layer([]int{1, 1})),
                ),
                mk.all(
                    mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 1})),
                    mk.rule(mk.in_exact_layer([]int{1, 5}), mk.out_exact_layer([]int{mk.OUT_KEEP, 1})),
                ),
            ),
        ),
        mk.prl(
            mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{3})),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{0})),
        ),
    )
}
