// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_sewers :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.sample, "Sewers"),
            mk.kattr(.n, 3),
            mk.kattr(.values, mk.values_count(4)),
            mk.rule(mk.sym(0), mk.one_of(mk.sym(0), mk.sym(2))),
            mk.markov_node(
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{3, 1})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
                ),
                mk.path_node(
                    mk.kattr(.from_, mk.one_of(mk.sym(3))),
                    mk.kattr(.to, mk.one_of(mk.sym(1))),
                    mk.kattr(.on, mk.one_of(mk.sym(0))),
                    mk.kattr(.color, mk.sym(3)),
                    mk.kattr(.inertia, true),
                ),
                mk.path_node(
                    mk.kattr(.from_, mk.one_of(mk.sym(3))),
                    mk.kattr(.to, mk.one_of(mk.sym(1))),
                    mk.kattr(.on, mk.one_of(mk.sym(2))),
                    mk.kattr(.color, mk.sym(3)),
                    mk.kattr(.inertia, true),
                ),
                mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
            ),
        ),
    )
}
