// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_multiheadedwalk :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.kattr(.origin, true),
        mk.sequence(
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
                mk.kattr(.steps, 3),
            ),
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        ),
    )
}
