// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_mazetrail :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.origin, true),
        mk.rule(mk.in_exact_layer([]int{1, 0, 0}), mk.out_exact_layer([]int{2, 2, 1})),
        mk.rule(mk.in_exact_layer([]int{1, mk.IN_ANY, 2}), mk.out_exact_layer([]int{2, mk.OUT_KEEP, 1})),
    )
}
