// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_paintcompetition :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{2})),
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{3})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{2})),
            mk.kattr(.out, mk.out_exact_layer([]int{0})),
            mk.kattr(.steps, 5),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{3})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 5),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{0, 2}), mk.out_exact_layer([]int{2, 0})),
            mk.rule(mk.in_exact_layer([]int{0, 3}), mk.out_exact_layer([]int{2, 0})),
            mk.rule(mk.in_exact_layer([]int{1, 2}), mk.out_exact_layer([]int{3, 1})),
            mk.rule(mk.in_exact_layer([]int{1, 3}), mk.out_exact_layer([]int{3, 1})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(1)),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
                mk.kattr(.on, mk.one_of(mk.sym(3))),
                mk.kattr(.recompute, true),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(3))),
                mk.kattr(.on, mk.one_of(mk.sym(2))),
                mk.kattr(.recompute, true),
            ),
        ),
    )
}
