// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_coloredknots :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layers(
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, 1, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 2, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.values, mk.values_count(16)),
            mk.kattr(.tileset, "Knots3D"),
            mk.kattr(.tiles, "Knots3D/3"),
            mk.rule(mk.sym(1), "Empty"),
            mk.rule(mk.sym(2), "Line|Turn|Empty"),
            mk.markov_node(
                mk.all(
                    mk.rule(mk.in_exact_layer([]int{2, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
                    mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
                    mk.rule(mk.in_exact_layer([]int{4, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 4})),
                    mk.rule(mk.in_exact_layer([]int{5, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 5})),
                    mk.rule(mk.in_exact_layer([]int{6, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 6})),
                    mk.rule(mk.in_exact_layer([]int{7, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 7})),
                    mk.rule(mk.in_exact_layer([]int{8, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 8})),
                    mk.rule(mk.in_exact_layer([]int{9, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 9})),
                    mk.rule(mk.in_exact_layer([]int{10, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 10})),
                    mk.rule(mk.in_exact_layer([]int{11, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 11})),
                    mk.rule(mk.in_exact_layer([]int{12, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 12})),
                    mk.rule(mk.in_exact_layer([]int{13, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 13})),
                    mk.rule(mk.in_exact_layer([]int{14, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 14})),
                    mk.rule(mk.in_exact_layer([]int{15, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 15})),
                ),
                mk.one(
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{2})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{3})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{4})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{5})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{6})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{7})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{8})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{9})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{10})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{11})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{12})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{13})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{14})),
                    mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{15})),
                ),
            ),
        ),
    )
}
