// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_dungeongrowth :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.kattr(.origin, true),
        mk.kattr(.folder, "DungeonGrowth"),
        mk.union_node(mk.kattr(.symbol, "?"), mk.kattr(.values, mk.one_of(mk.sym(1), mk.sym(2)))),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, 0, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 2, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.one(
            mk.rule_node(mk.kattr(.file, "Room1"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room2"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room3"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room4"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room5"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room7"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room13"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room8"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room9"), mk.kattr(.legend, "*0241?3")),
            mk.rule_node(mk.kattr(.file, "Room10"), mk.kattr(.legend, "*0?2143")),
            mk.rule_node(mk.kattr(.file, "Room11"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room12"), mk.kattr(.legend, "*024?13")),
            mk.rule_node(mk.kattr(.file, "Room14"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room15"), mk.kattr(.legend, "*02413?")),
            mk.rule_node(mk.kattr(.file, "Room16"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room17"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room18"), mk.kattr(.legend, "*?01243")),
            mk.rule_node(mk.kattr(.file, "Room6"), mk.kattr(.legend, "*?01243")),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 3, 0}, []int{2, 2, 2})),
            mk.kattr(.out, mk.out_exact_layer([]int{0, 1, 0}, []int{2, 2, 2})),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
        mk.markov_node(
            mk.all(
                mk.rule(mk.in_exact_layer([]int{1, 5}), mk.out_exact_layer([]int{3, 3})),
                mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{3, 3})),
                mk.rule(mk.in_exact_layer([]int{3, 5}), mk.out_exact_layer([]int{3, 3})),
                mk.rule(mk.in_exact_layer([]int{2, 3}), mk.out_exact_layer([]int{0, 3})),
                mk.rule(
                    mk.in_exact_layer([]int{2, mk.IN_ANY}, []int{mk.IN_ANY, 3}),
                    mk.out_exact_layer([]int{0, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 3}),
                ),
            ),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(1))),
                mk.kattr(.to, mk.one_of(mk.sym(5))),
                mk.kattr(.on, mk.one_of(mk.sym(2))),
                mk.kattr(.color, mk.sym(3)),
                mk.kattr(.inertia, true),
                mk.kattr(.longest, true),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{5})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{5}))),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{3}), mk.out_exact_layer([]int{4})),
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{2})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{2, 2, 2}, []int{2, 4, 2})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 2, mk.OUT_KEEP}),
            ),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{2, 4}), mk.out_exact_layer([]int{0, 4})),
            mk.rule(
                mk.in_exact_layer([]int{2, mk.IN_ANY}, []int{mk.IN_ANY, 4}),
                mk.out_exact_layer([]int{0, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 4}),
            ),
        ),
    )
}
