// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_forestfireca :: proc() -> mk.Proc_Node {
    return mk.convolution_node(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.neighborhood, "Moore"),
        mk.rule(mk.sym(1), mk.sym(2), mk.kattr(.sum, "1..8"), mk.kattr(.values, mk.one_of(mk.sym(2)))),
        mk.rule(mk.sym(2), mk.sym(0)),
        mk.rule(mk.sym(0), mk.sym(1), mk.kattr(.p, 0.01)),
        mk.rule(mk.sym(1), mk.sym(2), mk.kattr(.p, 0.0001)),
    )
}
