// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_biasedgrowthcontraction :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.kattr(.origin, true),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{0}, []int{mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{2}, []int{mk.OUT_KEEP})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY}, []int{2})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP}, []int{3})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{3}, []int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{1}, []int{3})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
            mk.kattr(.steps, 20),
        ),
        mk.one(
            mk.kattr(.temperature, 35.0),
            mk.rule(mk.in_exact_layer([]int{1, 3}), mk.out_exact_layer([]int{1, 1})),
            mk.rule(mk.in_exact_layer([]int{3, 1, 1}), mk.out_exact_layer([]int{3, 3, 1})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(1)),
                mk.kattr(.to, mk.one_of(mk.sym(0))),
                mk.kattr(.on, mk.one_of(mk.sym(1), mk.sym(3))),
                mk.kattr(.recompute, false),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(3)),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
                mk.kattr(.on, mk.one_of(mk.sym(1), mk.sym(3))),
                mk.kattr(.recompute, false),
            ),
        ),
    )
}
