// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_goto :: proc() -> mk.Proc_Node {
    return mk.markov_node(
        mk.kattr(.values, mk.values_count(4)),
        mk.kattr(.origin, true),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{1, 2}), mk.out_exact_layer([]int{0, 1})),
            mk.rule(mk.in_exact_layer([]int{1, 3}), mk.out_exact_layer([]int{0, 1})),
        ),
        mk.path_node(
            mk.kattr(.from_, mk.one_of(mk.sym(1))),
            mk.kattr(.to, mk.one_of(mk.sym(2))),
            mk.kattr(.on, mk.one_of(mk.sym(0))),
            mk.kattr(.color, mk.sym(3)),
        ),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
    )
}
