// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_completesaw :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.kattr(.origin, true),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1, mk.IN_ANY, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 3})),
            mk.rule(mk.in_exact_layer([]int{3, mk.IN_ANY, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 3})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 2, 1})),
            mk.kattr(.search, true),
            mk.kattr(.limit, 1000),
            mk.kattr(.depth_coefficient, -1.0),
            mk.observe_node(
                mk.kattr(.value, mk.sym(3)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(1), mk.sym(2))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(1)), mk.kattr(.to, mk.one_of(mk.sym(2)))),
            mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(2)))),
        ),
    )
}
