// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_tilepath :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.comment, "color all inner cells gray"),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 1, 1}, []int{0, 1, 1})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 2},
                ),
            ),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
            mk.kattr(.comment, "color 2 cells near opposite corners red"),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 1, 0}, []int{1, 1, 0}, []int{0, 0, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{2, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.wfc_node(
            mk.kattr(.tileset, "Knots2D"),
            mk.kattr(.values, mk.values_count(4)),
            mk.rule(mk.sym(0), "Empty"),
            mk.rule(mk.sym(1), "Empty|Line|Turn"),
            mk.rule(mk.sym(2), "End"),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 1, 0})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 2, mk.OUT_KEEP},
                    ),
                ),
                mk.kattr(.comment, "color river endpoints indigo"),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
                mk.kattr(.comment, "color the whole path indigo"),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 2, 0})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 3, mk.OUT_KEEP},
                    ),
                ),
                mk.kattr(.comment, "color endpoints red"),
            ),
        ),
    )
}
