// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_basickeys :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(13)),
        mk.kattr(.origin, true),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2, 1})),
            mk.kattr(.comment, "draw a grid"),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{4})),
            mk.kattr(.limit, 1),
            mk.kattr(.comment, "put an end"),
        ),
        mk.one(
            mk.kattr(.comment, "put a start far from the end"),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{3}), mk.kattr(.limit, 1)),
            mk.field_node(
                mk.kattr(.for_, mk.sym(3)),
                mk.kattr(.from_, mk.one_of(mk.sym(4))),
                mk.kattr(.on, mk.one_of(mk.sym(1), mk.sym(2), mk.sym(3))),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, 2, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 6, 7})),
            mk.kattr(.limit, 1),
        ),
        mk.one(
            mk.kattr(.temperature, 2.0),
            mk.kattr(.comment, "draw a non-optimal path from start to end"),
            mk.rule(mk.in_exact_layer([]int{7, 2, 1}), mk.out_exact_layer([]int{5, 6, 7})),
            mk.rule(mk.in_exact_layer([]int{7, 2, 4}), mk.out_exact_layer([]int{5, 6, 4})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(7)),
                mk.kattr(.to, mk.one_of(mk.sym(4))),
                mk.kattr(.on, mk.one_of(mk.sym(1), mk.sym(2), mk.sym(4), mk.sym(7))),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, 6, 5})),
            mk.kattr(.out, mk.out_exact_layer([]int{8, 10, 3})),
            mk.kattr(.limit, 1),
        ),
        mk.markov_node(
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{12, 2, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{11, 11, 12})),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{3, 2, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{7, 11, 12})),
            ),
            mk.one(
                mk.rule(mk.in_exact_layer([]int{3, 6, 5}), mk.out_exact_layer([]int{10, 10, 3})),
                mk.rule(mk.in_exact_layer([]int{7, 6, 5}), mk.out_exact_layer([]int{10, 9, 3})),
                mk.rule(mk.in_exact_layer([]int{3, 6, 4}), mk.out_exact_layer([]int{10, 10, 4})),
                mk.rule(mk.in_exact_layer([]int{7, 6, 4}), mk.out_exact_layer([]int{10, 9, 4})),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{11, 2, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 11, 11})),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
    )
}
