// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_parallelgrowth :: proc() -> mk.Proc_Node {
    return mk.all(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(.origin, true),
        mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})),
        mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 1})),
    )
}
