// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_knightpatrol :: proc() -> mk.Proc_Node {
    return mk.markov_node(
        mk.kattr(.values, mk.values_count(5)),
        mk.kattr(.origin, true),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, mk.IN_ANY, mk.IN_ANY}, []int{mk.IN_ANY, mk.IN_ANY, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{3, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, 1})),
            mk.observe_node(
                mk.kattr(.value, mk.sym(2)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(3)))),
            mk.observe_node(mk.kattr(.value, mk.sym(1)), mk.kattr(.to, mk.one_of(mk.sym(3)))),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
    )
}
