// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_pillarsofeternity :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_XY)),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 2, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.values, mk.values_count(7)),
            mk.kattr(.output_values, "BWAE"),
            mk.kattr(.tileset, "OrientedStairs"),
            mk.kattr(.periodic, true),
            mk.rule(mk.sym(2), "Empty"),
            mk.all(
                mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{3})),
                mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{3})),
            ),
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{mk.IN_ANY}}, [][]int{[]int{2}})),
                mk.kattr(.out, mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{0}})),
            ),
            mk.all(
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{4}}),
                    mk.out_exact_layers([][]int{[]int{6}}, [][]int{[]int{4}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{6}}),
                    mk.out_exact_layers([][]int{[]int{6}}, [][]int{[]int{6}}),
                ),
            ),
            mk.all(
                mk.rule(mk.in_exact_layer([]int{3, 6}), mk.out_exact_layer([]int{mk.OUT_KEEP, 5})),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{3}}, [][]int{[]int{6}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{5}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{2}}, [][]int{[]int{6}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{5}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{5}}, [][]int{[]int{6}}),
                    mk.out_exact_layers([][]int{[]int{0}}, [][]int{[]int{5}}),
                ),
            ),
            mk.all(
                mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{0})),
                mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{0})),
                mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{3})),
                mk.rule(mk.in_exact_layer([]int{4}), mk.out_exact_layer([]int{3})),
            ),
        ),
    )
}
