// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_sequentialsnake :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(7)),
        mk.kattr(.origin, true),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0})), mk.kattr(.out, mk.out_exact_layer([]int{3, 2, 4}))),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{4, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 2, 4})),
            mk.kattr(.steps, 10),
        ),
        mk.markov_node(
            mk.one(
                mk.rule(mk.in_exact_layer([]int{4, 0, 0}), mk.out_exact_layer([]int{6, 6, 5})),
                mk.rule(mk.in_exact_layer([]int{2, 2, 6}), mk.out_exact_layer([]int{6, 6, 6})),
                mk.rule(mk.in_exact_layer([]int{3, 2, 6}), mk.out_exact_layer([]int{0, 0, 3})),
            ),
            mk.all(
                mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{2})),
                mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{4})),
            ),
            mk.all(
                mk.rule(mk.in_exact_layer([]int{4}), mk.out_exact_layer([]int{3})),
                mk.rule(mk.in_exact_layer([]int{3}), mk.out_exact_layer([]int{4})),
            ),
        ),
    )
}
