// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_regularpath :: proc() -> Model_Config {
    return Model_Config{size = {79, 79, 1}, steps = 50000, pixel_size = 4, iso = false}
}

model_palette_symbol_regularpath :: proc(value: int) -> (u8, bool) {
    values := "BAWRGY"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_regularpath :: proc(value: int) -> (i32, bool) {
    return 0, false
}
