// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_dijkstradungeon :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.union_node(mk.kattr(.symbol, "?"), mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(4)))),
        mk.one(mk.kattr(.file, "DijkstraRoom"), mk.kattr(.legend, "?42*03"), mk.kattr(.steps, 1)),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.markov_node(
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1, 3})), mk.kattr(.out, mk.out_exact_layer([]int{1, 1}))),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(3))),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.color, mk.sym(1)),
                mk.kattr(.inertia, true),
            ),
            mk.one(mk.kattr(.file, "DijkstraRoom"), mk.kattr(.legend, "?42*03")),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{2})),
            mk.rule(mk.in_exact_layer([]int{4}), mk.out_exact_layer([]int{0})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, 2})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
    )
}
