// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_opencave3d :: proc() -> Model_Config {
    return Model_Config{size = {40, 40, 40}, steps = 50000, pixel_size = 4, iso = false}
}

model_palette_symbol_opencave3d :: proc(value: int) -> (u8, bool) {
    values := "DA"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_opencave3d :: proc(value: int) -> (i32, bool) {
    return 0, false
}
