// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_selectlargecaves :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{0})),
            mk.kattr(.p, 0.435),
            mk.kattr(.steps, 1),
        ),
        mk.convolution_node(
            mk.kattr(.neighborhood, "Moore"),
            mk.rule(mk.sym(1), mk.sym(0), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(0)))),
            mk.rule(mk.sym(0), mk.sym(1), mk.kattr(.sum, "6..8"), mk.kattr(.values, mk.one_of(mk.sym(1)))),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0}, []int{0, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{0, 0}, []int{0, 1})),
        ),
        mk.markov_node(
            mk.sequence(
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{1})),
                    mk.kattr(.out, mk.out_exact_layer([]int{2})),
                    mk.kattr(.steps, 1),
                ),
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
                    mk.kattr(.steps, 200),
                ),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})),
                    mk.kattr(.out, mk.out_exact_layer([]int{3, 3})),
                ),
                mk.all(
                    mk.rule(mk.in_exact_layer([]int{3, 2}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
                    mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
                ),
            ),
        ),
    )
}
