// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_waveflowers :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0}, []int{mk.IN_ANY}, []int{mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{1}, []int{mk.OUT_KEEP}, []int{mk.OUT_KEEP})),
        ),
        mk.wfc_node(
            mk.kattr(.sample, "Flowers"),
            mk.kattr(.values, mk.values_count(4)),
            mk.kattr(.n, 3),
            mk.kattr(.periodic, true),
            mk.kattr(.shannon, true),
            mk.rule(mk.sym(0), mk.one_of(mk.sym(2), mk.sym(3))),
            mk.rule(mk.sym(1), mk.one_of(mk.sym(0), mk.sym(1), mk.sym(2))),
        ),
    )
}
