// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_lostcity :: proc() -> Model_Config {
    return Model_Config{size = {256, 256, 1}, steps = 50000, pixel_size = 3, iso = false}
}

model_palette_symbol_lostcity :: proc(value: int) -> (u8, bool) {
    values := "BWRDIE"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_lostcity :: proc(value: int) -> (i32, bool) {
    return 0, false
}
