// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_sokobanlevel2 :: proc() -> Model_Config {
    return Model_Config{size = {60, 60, 1}, steps = 50000, pixel_size = 4, iso = false}
}

model_palette_symbol_sokobanlevel2 :: proc(value: int) -> (u8, bool) {
    values := "BRWDIA"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_sokobanlevel2 :: proc(value: int) -> (i32, bool) {
    return 0, false
}
