// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_chase :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.periodic, true),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 20),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 20),
        ),
        mk.all(
            mk.kattr(.temperature, 1.0),
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{0, 1})),
            mk.rule(mk.in_exact_layer([]int{2, 0}), mk.out_exact_layer([]int{0, 2})),
            mk.rule(mk.in_exact_layer([]int{1, 2}), mk.out_exact_layer([]int{0, 1})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(2)),
                mk.kattr(.from_, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0), mk.sym(2))),
                mk.kattr(.recompute, true),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(1)),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
                mk.kattr(.on, mk.one_of(mk.sym(0), mk.sym(1))),
                mk.kattr(.recompute, true),
            ),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})), mk.kattr(.out, mk.out_exact_layer([]int{0, 1}))),
    )
}
