// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_bernoullipercolation :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.kattr(.origin, true),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{4, mk.OUT_KEEP})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 4, mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2, 1})),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{2})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.p, 0.517),
            mk.kattr(.steps, 1),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
        mk.path_node(
            mk.kattr(.from_, mk.one_of(mk.sym(0))),
            mk.kattr(.to, mk.one_of(mk.sym(3))),
            mk.kattr(.on, mk.one_of(mk.sym(1))),
            mk.kattr(.color, mk.sym(5)),
        ),
    )
}
