// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_basic :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(.in_, mk.in_exact_layer([]int{0})),
        mk.kattr(.out, mk.out_exact_layer([]int{1})),
    )
}
