// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_softpath :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(8)),
        mk.kattr(.origin, true),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1, 0, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 2})),
            mk.rule(mk.in_exact_layer([]int{2, 0, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 2})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{2})),
            mk.kattr(.out, mk.out_exact_layer([]int{3})),
            mk.kattr(.steps, 1),
            mk.kattr(.temperature, 20.0),
            mk.field_node(
                mk.kattr(.for_, mk.sym(3)),
                mk.kattr(.from_, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0), mk.sym(2))),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{2})),
            mk.kattr(.out, mk.out_exact_layer([]int{5})),
            mk.kattr(.steps, 1),
            mk.kattr(.temperature, 20.0),
            mk.field_node(
                mk.kattr(.for_, mk.sym(5)),
                mk.kattr(.from_, mk.one_of(mk.sym(3))),
                mk.kattr(.on, mk.one_of(mk.sym(0), mk.sym(2))),
            ),
        ),
        mk.prl(
            mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{0})),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{0})),
        ),
        mk.one(
            mk.kattr(.temperature, 2.0),
            mk.rule(mk.in_exact_layer([]int{3, 0, 0}), mk.out_exact_layer([]int{4, 7, 6})),
            mk.rule(mk.in_exact_layer([]int{6, 0, 0}), mk.out_exact_layer([]int{7, 7, 6})),
            mk.rule(mk.in_exact_layer([]int{6, 0, 5}), mk.out_exact_layer([]int{7, 7, 5})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(6)),
                mk.kattr(.to, mk.one_of(mk.sym(5))),
                mk.kattr(.on, mk.one_of(mk.sym(0), mk.sym(6))),
            ),
        ),
    )
}
