// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_findlongcycle :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(7)),
        mk.kattr(.origin, true),
        mk.union_node(mk.kattr(.symbol, "?"), mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(4), mk.sym(5)))),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0})), mk.kattr(.out, mk.out_exact_layer([]int{1, 2, 1}))),
        mk.markov_node(
            mk.markov_node(
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{3, 2, 1})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 3})),
                    mk.kattr(.steps, 20),
                ),
                mk.all(
                    mk.rule(mk.in_exact_layer([]int{3, 2, 1}), mk.out_exact_layer([]int{6, 2, 6})),
                    mk.rule(mk.in_exact_layer([]int{6, 2, 1}), mk.out_exact_layer([]int{6, 2, 6})),
                    mk.rule(mk.in_exact_layer([]int{6, 2, 3}), mk.out_exact_layer([]int{6, 2, 6})),
                ),
                mk.sequence(
                    mk.one(
                        mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 1})),
                        mk.kattr(.out, mk.out_exact_layer([]int{3, 0, 3})),
                        mk.kattr(.steps, 1),
                    ),
                    mk.all(
                        mk.rule(
                            "B?B/?W?",
                            mk.out_exact_layer(
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, 5, mk.OUT_KEEP},
                            ),
                        ),
                        mk.rule(
                            "???/BAB",
                            mk.out_exact_layer(
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, 4, mk.OUT_KEEP},
                            ),
                        ),
                    ),
                ),
            ),
            mk.markov_node(
                mk.all(
                    mk.rule(mk.in_exact_layer([]int{3}), mk.out_exact_layer([]int{1})),
                    mk.rule(mk.in_exact_layer([]int{1, 4, 5}), mk.out_exact_layer([]int{1, 2, 1})),
                ),
            ),
        ),
        mk.one(
            mk.kattr(.in_, "B?B/?U?"),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 3, mk.OUT_KEEP}),
            ),
        ),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{3, 0, 3})), mk.kattr(.out, mk.out_exact_layer([]int{6, 2, 6}))),
        mk.prl(
            mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{1})),
            mk.rule(mk.in_exact_layer([]int{4}), mk.out_exact_layer([]int{5})),
        ),
    )
}
