// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_cavecontour :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{0})),
            mk.kattr(.p, 0.5),
            mk.kattr(.steps, 1),
        ),
        mk.convolution_node(
            mk.kattr(.neighborhood, "Moore"),
            mk.kattr(.periodic, true),
            mk.rule(mk.sym(1), mk.sym(0), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(0)))),
            mk.rule(mk.sym(0), mk.sym(1), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(1)))),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{0, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
            mk.rule(
                mk.in_exact_layer([]int{0, mk.IN_ANY}, []int{mk.IN_ANY, 1}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 3}),
            ),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{3, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
            mk.rule(
                mk.in_exact_layer([]int{3, mk.IN_ANY}, []int{mk.IN_ANY, 0}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 2}),
            ),
        ),
        mk.prl(
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{1})),
            mk.rule(mk.in_exact_layer([]int{3}), mk.out_exact_layer([]int{2})),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, 2}, []int{2, 3})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
        ),
    )
}
