// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_basicdijkstrafill :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.all(mk.kattr(.file, "BasicDijkstraRoom"), mk.kattr(.legend, "01")),
        mk.markov_node(
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})), mk.kattr(.out, mk.out_exact_layer([]int{2, 2}))),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(2))),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.color, mk.sym(2)),
                mk.kattr(.inertia, true),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        ),
    )
}
