// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_hamiltonianpath :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.kattr(.origin, true),
        mk.one(
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
            mk.rule(mk.in_exact_layer([]int{0}, []int{0}, []int{1}), mk.out_exact_layer([]int{1}, []int{0}, []int{0})),
            mk.rule(mk.in_exact_layer([]int{0, 0, 1}), mk.out_exact_layer([]int{1, 0, 0})),
        ),
        mk.markov_node(
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0})),
                mk.kattr(.out, mk.out_exact_layer([]int{2, 2, 1})),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1}, []int{0}, []int{0})),
                mk.kattr(.out, mk.out_exact_layer([]int{2}, []int{2}, []int{1})),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 2, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 1, mk.OUT_KEEP}),
            ),
        ),
        mk.markov_node(
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{4, 2, 2})),
                mk.kattr(.out, mk.out_exact_layer([]int{4, 4, 4})),
            ),
            mk.sequence(
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{4, 2, 3})),
                    mk.kattr(.out, mk.out_exact_layer([]int{1, 0, 2})),
                ),
                mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{4})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 2})),
                mk.kattr(.out, mk.out_exact_layer([]int{4, 2, 3})),
            ),
        ),
    )
}
