// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_tiledungeon :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.tileset, "Dungeon"),
            mk.kattr(.values, mk.values_count(3)),
            mk.rule(mk.sym(0), "Stone"),
            mk.markov_node(
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{2, 0})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
                ),
                mk.path_node(
                    mk.kattr(.from_, mk.one_of(mk.sym(0))),
                    mk.kattr(.to, mk.one_of(mk.sym(2))),
                    mk.kattr(.on, mk.one_of(mk.sym(1))),
                    mk.kattr(.color, mk.sym(2)),
                ),
                mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
            ),
        ),
    )
}
