// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_bishopparity :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 1),
            mk.kattr(.temperature, 10.0),
            mk.field_node(
                mk.kattr(.for_, mk.sym(2)),
                mk.kattr(.from_, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 3, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.steps, 1),
            mk.kattr(.temperature, 10.0),
            mk.field_node(
                mk.kattr(.for_, mk.sym(3)),
                mk.kattr(.from_, mk.one_of(mk.sym(1), mk.sym(2))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
            ),
        ),
        mk.one(
            mk.rule(
                mk.in_exact_layer([]int{1, mk.IN_ANY}, []int{mk.IN_ANY, 0}),
                mk.out_exact_layer([]int{4, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 1}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{3, mk.IN_ANY}, []int{1, 0}),
                mk.out_exact_layer([]int{3, mk.OUT_KEEP}, []int{4, 1}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{3, mk.IN_ANY}, []int{0, 1}),
                mk.out_exact_layer([]int{3, mk.OUT_KEEP}, []int{1, 4}),
            ),
            mk.observe_node(
                mk.kattr(.value, mk.sym(2)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(1)), mk.kattr(.to, mk.one_of(mk.sym(4)))),
            mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(4)))),
            mk.observe_node(mk.kattr(.value, mk.sym(3)), mk.kattr(.to, mk.one_of(mk.sym(3)))),
        ),
    )
}
