// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_chainmaze :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.convchain_node(
            mk.kattr(.sample, "Maze"),
            mk.kattr(.on, "B"),
            mk.kattr(.black, "D"),
            mk.kattr(.white, "A"),
            mk.kattr(.n, 2),
            mk.kattr(.steps, 10),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{2, 1}, []int{1, 2})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 1}, []int{2, 2})),
        ),
    )
}
