// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_stochasticvoronoi :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 10),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 10),
        ),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{2, 0}), mk.out_exact_layer([]int{2, 2})),
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{1, 1})),
        ),
    )
}
