// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_mazemap :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        mk.kattr(.values, mk.values_count(5)),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{1})),
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{2})),
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{3})),
            mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{4})),
        ),
        mk.map_node(
            mk.kattr(.scale, "2 2 1"),
            mk.kattr(.values, mk.values_count(2)),
            mk.rule(
                mk.in_exact_layer([]int{1}),
                mk.out_exact_layer([]int{0, 0}, []int{0, 1}),
                mk.kattr(.comment, "1 cell"),
            ),
            mk.rule(
                mk.in_exact_layer([]int{2}),
                mk.out_exact_layer([]int{0, 0}, []int{1, 1}),
                mk.kattr(.comment, "horizontal 2 cells"),
            ),
            mk.rule(
                mk.in_exact_layer([]int{3}),
                mk.out_exact_layer([]int{0, 1}, []int{0, 1}),
                mk.kattr(.comment, "vertical 2 cells"),
            ),
            mk.rule(
                mk.in_exact_layer([]int{4}),
                mk.out_exact_layer([]int{0, 1}, []int{1, 1}),
                mk.kattr(.comment, "3 cells"),
            ),
        ),
    )
}
