// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_basicbrickwall :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0}, []int{mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{2}, []int{mk.OUT_KEEP})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{2}, []int{mk.IN_ANY}, []int{mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{1}, []int{mk.OUT_KEEP}, []int{mk.OUT_KEEP})),
        ),
        mk.markov_node(
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{0, 1})), mk.kattr(.out, mk.out_exact_layer([]int{0, 0}))),
            mk.one(
                mk.kattr(
                    .in_,
                    mk.in_exact_layer([]int{1}, []int{1}, []int{1}, []int{1}, []int{1}, []int{1}, []int{1}, []int{1}),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP},
                        []int{mk.OUT_KEEP},
                        []int{mk.OUT_KEEP},
                        []int{0},
                        []int{mk.OUT_KEEP},
                        []int{mk.OUT_KEEP},
                        []int{mk.OUT_KEEP},
                        []int{mk.OUT_KEEP},
                    ),
                ),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{2, 2, 2, 2, 2, 2, 2, 2}, []int{0, 0, 0, 0, 0, 0, 0, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int {
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        0,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                    },
                    []int {
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                    },
                ),
            ),
        ),
        mk.markov_node(
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_ALL)),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{2, 2}, []int{2, 0})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 0}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{2, 2, 2, 2}, []int{0, 0, 0, 0}, []int{2, 2, 2, 2})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, 0, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 1}, []int{0, 0}, []int{2, 0})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, 2},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
            ),
        ),
    )
}
