// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_stormysnelllaw :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(8)),
        mk.kattr(.origin, true),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 1})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, mk.OUT_KEEP})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY, 2})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 4})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.all(
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
            mk.rule(mk.in_exact_layer([]int{1}, []int{0}), mk.out_exact_layer([]int{0}, []int{1})),
            mk.rule(mk.in_exact_layer([]int{0}, []int{2}), mk.out_exact_layer([]int{2}, []int{0})),
            mk.rule(mk.in_exact_layer([]int{4, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 4})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{4}, []int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP}, []int{4})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{5})),
            mk.kattr(.steps, 8),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{4})),
            mk.kattr(.out, mk.out_exact_layer([]int{3})),
            mk.kattr(.steps, 8),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{5, 4}), mk.out_exact_layer([]int{5, 5})),
            mk.rule(mk.in_exact_layer([]int{3, 4}), mk.out_exact_layer([]int{3, 3})),
        ),
        mk.one(
            mk.rule(
                mk.in_exact_layer([]int{1, mk.IN_ANY, mk.IN_ANY}, []int{mk.IN_ANY, mk.IN_ANY, 3}),
                mk.out_exact_layer([]int{4, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, 6}),
            ),
            mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{1})),
            mk.rule(
                mk.in_exact_layer([]int{1, mk.IN_ANY, mk.IN_ANY}, []int{mk.IN_ANY, mk.IN_ANY, 5}),
                mk.out_exact_layer([]int{4, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, 7}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{7, mk.IN_ANY, mk.IN_ANY}, []int{mk.IN_ANY, mk.IN_ANY, 5}),
                mk.out_exact_layer([]int{0, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, 7}),
            ),
            mk.observe_node(
                mk.kattr(.value, mk.sym(2)),
                mk.kattr(.from_, mk.sym(5)),
                mk.kattr(.to, mk.one_of(mk.sym(7))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(1)), mk.kattr(.to, mk.one_of(mk.sym(4)))),
            mk.observe_node(mk.kattr(.value, mk.sym(5)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(5)))),
            mk.observe_node(mk.kattr(.value, mk.sym(3)), mk.kattr(.to, mk.one_of(mk.sym(3), mk.sym(4)))),
        ),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{7})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
    )
}
