// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_surface :: proc() -> Model_Config {
    return Model_Config{size = {10, 10, 10}, steps = 50000, pixel_size = 4, iso = false}
}

model_palette_symbol_surface :: proc(value: int) -> (u8, bool) {
    values := "B"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_surface :: proc(value: int) -> (i32, bool) {
    return 0, false
}
