// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_river :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{2, 0}), mk.out_exact_layer([]int{2, 2})),
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{1, 1})),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})), mk.kattr(.out, mk.out_exact_layer([]int{3, 3}))),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{0})),
            mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{0})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{3, 3})),
            mk.kattr(.steps, 1),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 3}, []int{3, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{3, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 4})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{5})),
            mk.kattr(.steps, 13),
        ),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{5, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 5})),
            mk.rule(mk.in_exact_layer([]int{4, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 4})),
        ),
    )
}
