// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_parallelgrowth :: proc() -> Model_Config {
    return Model_Config{size = {29, 29, 29}, steps = 24, pixel_size = 4, iso = false}
}

model_palette_symbol_parallelgrowth :: proc(value: int) -> (u8, bool) {
    values := "BW"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_parallelgrowth :: proc(value: int) -> (i32, bool) {
    return 0, false
}
