// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_wavebrickwall :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(1)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        mk.wfc_node(
            mk.kattr(.sample, "BrickWall"),
            mk.kattr(.values, mk.values_count(3)),
            mk.kattr(.n, 3),
            mk.kattr(.periodic, true),
            mk.kattr(.shannon, true),
            mk.rule(mk.sym(0), mk.one_of(mk.sym(0), mk.sym(1), mk.sym(2))),
        ),
    )
}
