// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_connectedcaves :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{0})),
            mk.kattr(.p, 0.5),
            mk.kattr(.steps, 1),
        ),
        mk.convolution_node(
            mk.kattr(.neighborhood, "Moore"),
            mk.kattr(.periodic, true),
            mk.rule(mk.sym(1), mk.sym(0), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(0)))),
            mk.rule(mk.sym(0), mk.sym(1), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(1)))),
        ),
        mk.markov_node(
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})), mk.kattr(.out, mk.out_exact_layer([]int{2, 2}))),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(2))),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.color, mk.sym(1)),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        ),
    )
}
