// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_rectangle :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 1),
        ),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})), mk.kattr(.out, mk.out_exact_layer([]int{2, 2}))),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 2, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, 2, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}),
            ),
            mk.kattr(.steps, 5),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{2, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
            mk.rule(
                mk.in_exact_layer([]int{0, 0}, []int{2, 0}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, 2}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
            ),
        ),
    )
}
