// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_knots2d :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.tileset, "Knots2D"),
            mk.kattr(.values, mk.values_count(2)),
            mk.rule(mk.sym(0), "Empty"),
            mk.rule(mk.sym(1), "Empty|Line|Turn|Cross"),
        ),
    )
}
