// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_biasedgrowthcontraction :: proc() -> Model_Config {
    return Model_Config{size = {120, 120, 1}, steps = 5000, pixel_size = 4, iso = false}
}

model_palette_symbol_biasedgrowthcontraction :: proc(value: int) -> (u8, bool) {
    values := "NWSB"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_biasedgrowthcontraction :: proc(value: int) -> (i32, bool) {
    return 0, false
}
