// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_wolfbasedapproach :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(7)),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{3})),
            mk.kattr(.steps, 15),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{4})),
            mk.kattr(.steps, 1),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{4, 2}), mk.out_exact_layer([]int{2, 4})),
            mk.rule(mk.in_exact_layer([]int{4, 1}), mk.out_exact_layer([]int{5, 4})),
            mk.rule(mk.in_exact_layer([]int{3, 2}), mk.out_exact_layer([]int{2, 3})),
            mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{2, 3})),
            mk.rule(mk.in_exact_layer([]int{4, 3}), mk.out_exact_layer([]int{4, 4})),
            mk.rule(
                mk.in_exact_layer([]int{4, mk.IN_ANY}, []int{mk.IN_ANY, 3}),
                mk.out_exact_layer([]int{4, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 4}),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(3)),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(2))),
                mk.kattr(.recompute, true),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(4)),
                mk.kattr(.to, mk.one_of(mk.sym(3))),
                mk.kattr(.on, mk.one_of(mk.sym(1), mk.sym(2))),
                mk.kattr(.recompute, true),
                mk.kattr(.essential, true),
            ),
        ),
        mk.prl(
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{0})),
            mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{6})),
            mk.rule(mk.in_exact_layer([]int{4}), mk.out_exact_layer([]int{6})),
            mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{6})),
        ),
        mk.all(
            mk.rule(
                mk.in_exact_layer([]int{0, 6}, []int{6, 0}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 6}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{6, 6, 6}, []int{6, 0, 6}, []int{6, 6, 6}),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 6, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 6, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0, mk.OUT_KEEP}),
            ),
        ),
    )
}
