// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_backtrackercycle :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.kattr(.origin, true),
        mk.union_node(mk.kattr(.symbol, "?"), mk.kattr(.values, mk.one_of(mk.sym(3), mk.sym(4)))),
        mk.markov_node(
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0})),
                mk.kattr(.out, mk.out_exact_layer([]int{2, 2, 1})),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 2, 2})),
                mk.kattr(.out, mk.out_exact_layer([]int{3, 4, 1})),
            ),
        ),
        mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, 0, 3})),
            mk.kattr(.out, mk.out_exact_layer([]int{3, 4, 3})),
            mk.kattr(.steps, 1),
        ),
        mk.all(
            mk.kattr(.in_, "BBB/B?B"),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0, mk.OUT_KEEP}),
            ),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{4})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
    )
}
