// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_growthwalk :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(.origin, true),
        mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{0, 1})),
        mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{1, 1})),
    )
}
