// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_strangegrowth :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(
            .in_,
            mk.in_exact_layer([]int{mk.IN_ANY, mk.IN_ANY, 0}, []int{1, 0, mk.IN_ANY}, []int{mk.IN_ANY, mk.IN_ANY, 0}),
        ),
        mk.kattr(
            .out,
            mk.out_exact_layer(
                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
            ),
        ),
        mk.kattr(.origin, true),
    )
}
