// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_basicskyline :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 7),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1, 1})),
            mk.kattr(.steps, 100),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})), mk.kattr(.out, mk.out_exact_layer([]int{2, 0}))),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{2}, []int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2}, []int{2})),
        ),
    )
}
