// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_biasedmazegrowth :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.kattr(.origin, true),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{0}, []int{mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{3}, []int{mk.OUT_KEEP})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY}, []int{3})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP}, []int{4})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.one(
            mk.kattr(.temperature, 10.0),
            mk.rule(mk.in_exact_layer([]int{1, 4, 4}), mk.out_exact_layer([]int{1, 2, 1})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(1)),
                mk.kattr(.to, mk.one_of(mk.sym(0))),
                mk.kattr(.on, mk.one_of(mk.sym(4))),
                mk.kattr(.recompute, false),
            ),
        ),
    )
}
