// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_carmatower :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.kattr(.origin, true),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_XY)),
        mk.kattr(.folder, "CarmaTower"),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{1}}, [][]int{[]int{0}})),
            mk.kattr(.out, mk.out_exact_layers([][]int{[]int{0}}, [][]int{[]int{1}})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0}, []int{0, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{1, 1}, []int{1, 1})),
            mk.kattr(.steps, 1),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_IDENTITY)),
        ),
        mk.all(
            mk.kattr(.steps, 2),
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 1})),
            mk.rule(
                mk.in_exact_layer([]int{1, mk.IN_ANY}, []int{mk.IN_ANY, 0}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 1}),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{1}})),
            mk.kattr(.out, mk.out_exact_layers([][]int{[]int{1}}, [][]int{[]int{mk.OUT_KEEP}})),
            mk.kattr(.steps, 2),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{1}})),
            mk.kattr(.out, mk.out_exact_layers([][]int{[]int{2}}, [][]int{[]int{mk.OUT_KEEP}})),
            mk.kattr(.steps, 1),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{2}})),
            mk.kattr(.out, mk.out_exact_layers([][]int{[]int{2}}, [][]int{[]int{mk.OUT_KEEP}})),
        ),
        mk.union_node(
            mk.kattr(.symbol, "r"),
            mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(2), mk.sym(3))),
            mk.kattr(.color, "45283c"),
        ),
        mk.one(
            mk.rule_node(mk.kattr(.file, "block_2_4x3"), mk.kattr(.legend, "r0*423")),
            mk.rule_node(mk.kattr(.file, "block_1_5x3"), mk.kattr(.legend, "r0*423")),
        ),
        mk.all(
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
            mk.rule(mk.in_exact_layer([]int{0, 3, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 0, mk.OUT_KEEP})),
            mk.rule(
                mk.in_exact_layers(
                    [][]int{[]int{0, mk.IN_ANY}, []int{mk.IN_ANY, mk.IN_ANY}},
                    [][]int{[]int{3, 0}, []int{0, mk.IN_ANY}},
                ),
                mk.out_exact_layers(
                    [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP}},
                    [][]int{[]int{0, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP}},
                ),
            ),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        mk.all(
            mk.kattr(.comment, "add on sides"),
            mk.rule(
                mk.in_exact_layer([]int{4, 2}, []int{0, 0}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{4, mk.OUT_KEEP}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{0, 4}, []int{4, 4}),
                mk.out_exact_layer([]int{4, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
            ),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{2}}, [][]int{[]int{0}})),
            mk.kattr(.out, mk.out_exact_layers([][]int{[]int{0}}, [][]int{[]int{mk.OUT_KEEP}})),
            mk.kattr(.steps, 2),
        ),
        mk.all(
            mk.rule(
                mk.in_exact_layers([][]int{[]int{4, 2}}, [][]int{[]int{0, 0}}),
                mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}, [][]int{[]int{3, mk.OUT_KEEP}}),
            ),
            mk.rule(
                mk.in_exact_layers([][]int{[]int{4, 4}}, [][]int{[]int{3, 0}}),
                mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}, [][]int{[]int{mk.OUT_KEEP, 3}}),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{3}}, [][]int{[]int{0}})),
            mk.kattr(.out, mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{3}})),
            mk.kattr(.steps, 1),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
        mk.union_node(mk.kattr(.symbol, "^"), mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(4)))),
        mk.one(
            mk.kattr(.steps, 4),
            mk.rule(
                "^^^^/^^^^/^^^^ ^^^^/^^^^/^^^^ TTTT/TTTT/TTTT",
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                ),
            ),
            mk.rule(
                "^^^^/^^^^/^^^^ ^^^^/^^^^/^^^^ ^^^^/^^^^/^^^^ TTTT/TTTT/TTTT",
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                ),
            ),
            mk.rule(
                "^^^^/^^^^/^^^^ ^^^^/^^^^/^^^^ ^^^^/^^^^/^^^^ ^^^^/^^^^/^^^^ TTTT/TTTT/TTTT",
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                    [][]int{[]int{4, 4, 4, 4}, []int{4, 4, 4, 4}, []int{4, 4, 4, 4}},
                ),
            ),
            mk.rule(
                "^^^/^^^ ^^^/^^^ ^^^/^^^ TTT/TTT",
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int{[]int{4, 4, 4}, []int{4, 4, 4}},
                    [][]int{[]int{4, 4, 4}, []int{4, 4, 4}},
                    [][]int{[]int{4, 4, 4}, []int{4, 4, 4}},
                ),
            ),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{4})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
        mk.map_node(
            mk.kattr(.scale, "4 4 4"),
            mk.kattr(.values, mk.values_count(24)),
            mk.kattr(.output_values, "BaLDWYl"),
            mk.kattr(.transparent, "OoH"),
            mk.kattr(.folder, "CarmaTower"),
            mk.rule(
                mk.in_exact_layer([]int{4}),
                mk.out_exact_layers(
                    [][]int {
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                    },
                    [][]int {
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                    },
                    [][]int {
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                    },
                    [][]int {
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                    },
                    [][]int {
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1},
                    },
                ),
                mk.kattr(.comment, "EEEEE"),
            ),
            mk.prl(
                mk.kattr(.steps, 1),
                mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{0})),
            ),
            mk.sequence(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.kattr(.comment, "scaffolding"),
                mk.all(
                    mk.kattr(
                        .in_,
                        mk.in_exact_layers([][]int{[]int{0, 0}, []int{0, 0}}, [][]int{[]int{1, 0}, []int{0, 0}}),
                    ),
                    mk.kattr(
                        .out,
                        mk.out_exact_layers(
                            [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9}},
                            [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        ),
                    ),
                ),
                mk.all(
                    mk.kattr(
                        .in_,
                        mk.in_exact_layers(
                            [][]int {
                                []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                                []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 1},
                            },
                            [][]int {
                                []int{9, 0, 0, 0, 0},
                                []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                            },
                        ),
                    ),
                    mk.kattr(
                        .out,
                        mk.out_exact_layers(
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 9},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                        ),
                    ),
                ),
                mk.union_node(
                    mk.kattr(.symbol, "+"),
                    mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(9))),
                    mk.kattr(.comment, "black or scaffold"),
                ),
            ),
            mk.all(
                mk.kattr(.in_, "BBB/+++ LLL/BBB *L*/BBB"),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 5, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
                mk.kattr(.comment, "setting up panels"),
            ),
            mk.all(
                mk.rule(
                    mk.in_exact_layer([]int{1, 5, 5, 1}),
                    mk.out_exact_layer([]int{mk.OUT_KEEP, 1, 1, mk.OUT_KEEP}),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{1, 5, 5, 5, 1}),
                    mk.out_exact_layer([]int{mk.OUT_KEEP, 1, 1, 1, mk.OUT_KEEP}),
                ),
            ),
            mk.markov_node(
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{2, 5, 5, 5})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 2})),
                ),
                mk.one(
                    mk.rule(
                        mk.in_exact_layer([]int{0, 1, 5, 5, 5}),
                        mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 2}),
                    ),
                    mk.rule(
                        mk.in_exact_layer([]int{0, 1, 5, 5, 5}),
                        mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 10}),
                    ),
                ),
            ),
            mk.all(
                mk.rule(
                    mk.in_exact_layer([]int{2, 1}, []int{0, 0}),
                    mk.out_exact_layer([]int{1, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{2, 5, 1}, []int{0, 0, 0}),
                    mk.out_exact_layer([]int{1, 1, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}),
                ),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{2, 5, 5, 2, 5, 5, 2})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.comment, "fill down"),
                mk.rule(
                    "W* L* L+",
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{5, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
                mk.rule(
                    "a* L* L+",
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{2, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.comment, "mark uneven panels"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{1, mk.IN_ANY, 5}}, [][]int{[]int{5, 2, 5}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, 10}}, [][]int{[]int{10, 10, 10}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{1, 5}}, [][]int{[]int{5, 5}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, 10}}, [][]int{[]int{10, 10}}),
                ),
                mk.rule(mk.in_exact_layer([]int{5, 5, 5}), mk.out_exact_layer([]int{10, 10, 10})),
                mk.rule(
                    mk.in_exact_layer([]int{1, 15}, []int{1, 0}),
                    mk.out_exact_layer([]int{mk.OUT_KEEP, 10}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
                ),
            ),
            mk.all(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.rule(mk.in_exact_layer([]int{10, 5}), mk.out_exact_layer([]int{mk.OUT_KEEP, 10})),
                mk.rule(mk.in_exact_layer([]int{10, 2}), mk.out_exact_layer([]int{mk.OUT_KEEP, 10})),
            ),
            mk.all(
                mk.kattr(.comment, "delete too short panels"),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int{[]int{2}},
                        [][]int{[]int{2}},
                        [][]int{[]int{2}},
                        [][]int{[]int{2}},
                        [][]int{[]int{2}},
                        [][]int{[]int{2}},
                        [][]int{[]int{2}},
                        [][]int{[]int{1}},
                    ),
                    mk.out_exact_layers(
                        [][]int{[]int{16}},
                        [][]int{[]int{16}},
                        [][]int{[]int{16}},
                        [][]int{[]int{16}},
                        [][]int{[]int{16}},
                        [][]int{[]int{16}},
                        [][]int{[]int{16}},
                        [][]int{[]int{mk.OUT_KEEP}},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{2}}, [][]int{[]int{16}}),
                    mk.out_exact_layers([][]int{[]int{16}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
                mk.rule(mk.in_exact_layer([]int{16, 5}), mk.out_exact_layer([]int{mk.OUT_KEEP, 15})),
                mk.rule(mk.in_exact_layer([]int{15, 5}), mk.out_exact_layer([]int{mk.OUT_KEEP, 15})),
            ),
            mk.prl(
                mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{10})),
                mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{10})),
                mk.rule(mk.in_exact_layer([]int{10}), mk.out_exact_layer([]int{1})),
            ),
            mk.all(
                mk.kattr(.in_, "BBB/+++ LLL/BBB *L*/BBB"),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 21, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
                mk.kattr(.comment, "special windows"),
            ),
            mk.union_node(mk.kattr(.symbol, "2"), mk.kattr(.values, mk.one_of(mk.sym(5), mk.sym(21)))),
            mk.all(
                mk.rule(
                    mk.in_exact_layers(
                        [][]int{[]int{1}},
                        [][]int{[]int{1}},
                        [][]int{[]int{1}},
                        [][]int{[]int{1}},
                        [][]int{[]int{1}},
                        [][]int{[]int{1}},
                        [][]int{[]int{21}},
                    ),
                    mk.out_exact_layers(
                        [][]int{[]int{5}},
                        [][]int{[]int{5}},
                        [][]int{[]int{5}},
                        [][]int{[]int{5}},
                        [][]int{[]int{21}},
                        [][]int{[]int{21}},
                        [][]int{[]int{21}},
                    ),
                ),
                mk.rule(
                    "W+ LB LB",
                    mk.out_exact_layers(
                        [][]int{[]int{21, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.all(
                mk.rule(
                    "L 2 L",
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{10}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
                mk.rule("L2L", mk.out_exact_layer([]int{mk.OUT_KEEP, 10, mk.OUT_KEEP})),
                mk.rule("2T", mk.out_exact_layer([]int{10, mk.OUT_KEEP})),
                mk.rule("22/BL", mk.out_exact_layer([]int{10, 10}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
                mk.rule("2L/BL", mk.out_exact_layer([]int{10, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
            ),
            mk.all(
                mk.kattr(.in_, "R2"),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 10})),
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
            ),
            mk.all(
                mk.kattr(.comment, "mark long enough windows"),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int{[]int{1, 21, 21, 21, 21, 21, 21}},
                        [][]int{[]int{1, 21, 21, 21, 21, 21, 21}},
                        [][]int{[]int{1, 21, 21, 21, 21, 21, 21}},
                    ),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 17, 17, 17, 17, 17, 17}},
                        [][]int{[]int{mk.OUT_KEEP, 17, 17, 17, 17, 17, 17}},
                        [][]int{[]int{mk.OUT_KEEP, 17, 17, 17, 17, 17, 17}},
                    ),
                ),
                mk.rule(mk.in_exact_layer([]int{17, 21}), mk.out_exact_layer([]int{mk.OUT_KEEP, 17})),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int{[]int{5}},
                        [][]int{[]int{5}},
                        [][]int{[]int{5}},
                        [][]int{[]int{5}},
                        [][]int{[]int{17}},
                    ),
                    mk.out_exact_layers(
                        [][]int{[]int{18}},
                        [][]int{[]int{18}},
                        [][]int{[]int{18}},
                        [][]int{[]int{18}},
                        [][]int{[]int{mk.OUT_KEEP}},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{5}}, [][]int{[]int{18}}),
                    mk.out_exact_layers([][]int{[]int{18}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
            ),
            mk.prl(
                mk.rule(mk.in_exact_layer([]int{21}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{10}), mk.out_exact_layer([]int{1})),
            ),
            mk.prl(
                mk.kattr(.comment, "delete solo windows"),
                mk.rule(mk.in_exact_layer([]int{18}), mk.out_exact_layer([]int{5})),
                mk.rule(mk.in_exact_layer([]int{17}), mk.out_exact_layer([]int{21})),
            ),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{21}}, [][]int{[]int{mk.IN_ANY}}, [][]int{[]int{5}})),
                mk.kattr(
                    .out,
                    mk.out_exact_layers([][]int{[]int{17}}, [][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{18}}),
                ),
            ),
            mk.all(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.rule(mk.in_exact_layer([]int{18, 5}), mk.out_exact_layer([]int{mk.OUT_KEEP, 18})),
                mk.rule(mk.in_exact_layer([]int{18, 21}), mk.out_exact_layer([]int{mk.OUT_KEEP, 17})),
                mk.rule(mk.in_exact_layer([]int{17, 21}), mk.out_exact_layer([]int{mk.OUT_KEEP, 17})),
                mk.rule(mk.in_exact_layer([]int{17, 5}), mk.out_exact_layer([]int{mk.OUT_KEEP, 18})),
            ),
            mk.prl(
                mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{21}), mk.out_exact_layer([]int{1})),
            ),
            mk.all(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.kattr(.comment, "fine scaffold"),
                mk.rule(
                    mk.in_exact_layer([]int{9, 0, 0}, []int{mk.IN_ANY, 1, mk.IN_ANY}),
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, 21},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{21, 0, 0}, []int{mk.IN_ANY, 1, mk.IN_ANY}),
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, 21},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
            ),
            mk.union_node(
                mk.kattr(.symbol, "-"),
                mk.kattr(.values, mk.one_of(mk.sym(9), mk.sym(21))),
                mk.kattr(.color, "fec601"),
            ),
            mk.union_node(
                mk.kattr(.symbol, "="),
                mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(9), mk.sym(14), mk.sym(21))),
            ),
            mk.all(
                mk.rule("T-", mk.out_exact_layer([]int{mk.OUT_KEEP, 0})),
                mk.rule("T*/*-", mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0})),
                mk.rule("t-", mk.out_exact_layer([]int{mk.OUT_KEEP, 0})),
                mk.rule("V-", mk.out_exact_layer([]int{mk.OUT_KEEP, 0})),
                mk.rule("LQ/B-", mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0})),
                mk.rule(
                    "Q- L* V*",
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 0}},
                    ),
                ),
                mk.rule("VL/B-", mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0})),
                mk.rule("QL/B-", mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0})),
            ),
            mk.all(
                mk.kattr(.in_, "-B-/*L*"),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, 14, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{14, 1}}, [][]int{[]int{0, 18}})),
                mk.kattr(
                    .out,
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}, [][]int{[]int{21, mk.OUT_KEEP}}),
                ),
            ),
            mk.markov_node(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.kattr(.comment, "connect special windows"),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{5, 18})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 5})),
                ),
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{11, 18})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 5})),
                ),
                mk.path_node(
                    mk.kattr(.from_, mk.one_of(mk.sym(18))),
                    mk.kattr(.to, mk.one_of(mk.sym(5), mk.sym(11))),
                    mk.kattr(.on, mk.one_of(mk.sym(9), mk.sym(14), mk.sym(21))),
                    mk.kattr(.color, mk.sym(11)),
                    mk.kattr(.inertia, true),
                ),
                mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{18})), mk.kattr(.out, mk.out_exact_layer([]int{5}))),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{5})), mk.kattr(.out, mk.out_exact_layer([]int{18}))),
            mk.prl(
                mk.rule(mk.in_exact_layer([]int{14, 18}), mk.out_exact_layer([]int{0, mk.OUT_KEEP})),
                mk.rule(mk.in_exact_layer([]int{9, 18}), mk.out_exact_layer([]int{0, mk.OUT_KEEP})),
                mk.rule(mk.in_exact_layer([]int{21, 18}), mk.out_exact_layer([]int{0, mk.OUT_KEEP})),
            ),
            mk.convolution_node(
                mk.kattr(.neighborhood, "VonNeumann"),
                mk.kattr(.comment, "mark edges"),
                mk.rule(
                    mk.sym(1),
                    mk.sym(20),
                    mk.kattr(.sum, "2..3"),
                    mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(14))),
                ),
            ),
            mk.union_node(
                mk.kattr(.symbol, "5"),
                mk.kattr(.values, mk.one_of(mk.sym(1), mk.sym(10), mk.sym(11), mk.sym(12))),
            ),
            mk.union_node(
                mk.kattr(.symbol, "6"),
                mk.kattr(.values, mk.one_of(mk.sym(1), mk.sym(3))),
                mk.kattr(.color, "222034"),
            ),
            mk.all(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.rule("QL/==", mk.out_exact_layer([]int{mk.OUT_KEEP, 3}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
                mk.rule("DL/==", mk.out_exact_layer([]int{mk.OUT_KEEP, 3}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
            ),
            mk.all(
                mk.rule(
                    mk.in_exact_layer([]int{1, 1}, []int{1, 1}, []int{18, 20}),
                    mk.out_exact_layer([]int{mk.OUT_KEEP, 3}, []int{mk.OUT_KEEP, 3}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{1, 1}, []int{1, 1}, []int{17, 20}),
                    mk.out_exact_layer([]int{mk.OUT_KEEP, 3}, []int{mk.OUT_KEEP, 3}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
                ),
            ),
            mk.markov_node(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.kattr(.comment, "marking small or large faces"),
                mk.one(
                    mk.kattr(.in_, "RL/=="),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 10}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
                    mk.kattr(.steps, 200),
                ),
                mk.all(
                    mk.kattr(.in_, "RL/=="),
                    mk.kattr(.out, mk.out_exact_layer([]int{12, 12}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
                ),
                mk.all(
                    mk.rule("UR/==", mk.out_exact_layer([]int{12, 12}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
                    mk.rule("UL/==", mk.out_exact_layer([]int{12, 12}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
                ),
                mk.one(
                    mk.kattr(.in_, "L5/=5"),
                    mk.kattr(.out, mk.out_exact_layer([]int{10, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP})),
                ),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{10})),
                mk.kattr(.out, mk.out_exact_layer([]int{7})),
                mk.kattr(.steps, 12),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{7, 10})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 7})),
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
            ),
            mk.prl(
                mk.rule(mk.in_exact_layer([]int{12}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{10}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{20}), mk.out_exact_layer([]int{1})),
            ),
            mk.markov_node(
                mk.kattr(.comment, "surface prefab placement"),
                mk.all(
                    mk.kattr(.in_, "hLL/=== hLL/=== hLL/==="),
                    mk.kattr(
                        .out,
                        mk.out_exact_layers(
                            [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0, mk.OUT_KEEP}},
                            [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0, mk.OUT_KEEP}},
                            [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0, mk.OUT_KEEP}},
                        ),
                    ),
                ),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{12, 5})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 12})),
                    mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                ),
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{11, 5})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 12})),
                    mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                ),
                mk.path_node(
                    mk.kattr(.from_, mk.one_of(mk.sym(5))),
                    mk.kattr(.to, mk.one_of(mk.sym(11), mk.sym(12), mk.sym(18))),
                    mk.kattr(.on, mk.one_of(mk.sym(9), mk.sym(14), mk.sym(21))),
                    mk.kattr(.color, mk.sym(11)),
                    mk.kattr(.inertia, true),
                ),
                mk.one(
                    mk.rule_node(mk.kattr(.file, "side_13x5"), mk.kattr(.legend, "*E6-5")),
                    mk.rule_node(mk.kattr(.file, "side_5x13"), mk.kattr(.legend, "*E6-5")),
                    mk.rule_node(mk.kattr(.file, "side_7x11"), mk.kattr(.legend, "*E6-5")),
                    mk.rule_node(mk.kattr(.file, "side_11x7"), mk.kattr(.legend, "*E6-5")),
                    mk.rule_node(mk.kattr(.file, "roof_7x11"), mk.kattr(.legend, "6*E-5")),
                    mk.rule_node(mk.kattr(.file, "window_3"), mk.kattr(.legend, "9EL*018")),
                    mk.rule_node(mk.kattr(.file, "window_3"), mk.kattr(.legend, "9EL*018")),
                ),
            ),
            mk.markov_node(
                mk.kattr(.comment, "intermediate prefab placement"),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{12, 5})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 12})),
                    mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                ),
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{11, 5})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 12})),
                    mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                ),
                mk.path_node(
                    mk.kattr(.from_, mk.one_of(mk.sym(5))),
                    mk.kattr(.to, mk.one_of(mk.sym(11), mk.sym(12), mk.sym(18))),
                    mk.kattr(.on, mk.one_of(mk.sym(9), mk.sym(14), mk.sym(21))),
                    mk.kattr(.color, mk.sym(11)),
                    mk.kattr(.inertia, true),
                ),
                mk.one(
                    mk.rule_node(mk.kattr(.file, "roof_7x7"), mk.kattr(.legend, "6*E-5")),
                    mk.rule_node(mk.kattr(.file, "roof_5x9"), mk.kattr(.legend, "6*E-5")),
                ),
            ),
            mk.markov_node(
                mk.kattr(.comment, "secondary prefab placement"),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{12, 5})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 12})),
                    mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                ),
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{11, 5})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 12})),
                    mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                ),
                mk.path_node(
                    mk.kattr(.from_, mk.one_of(mk.sym(5))),
                    mk.kattr(.to, mk.one_of(mk.sym(11), mk.sym(12), mk.sym(18))),
                    mk.kattr(.on, mk.one_of(mk.sym(9), mk.sym(14), mk.sym(21))),
                    mk.kattr(.color, mk.sym(11)),
                    mk.kattr(.inertia, true),
                ),
                mk.one(
                    mk.rule_node(mk.kattr(.file, "side_3x5"), mk.kattr(.legend, "*E6-5")),
                    mk.rule_node(mk.kattr(.file, "side_5x3"), mk.kattr(.legend, "*E6-5")),
                    mk.rule_node(mk.kattr(.file, "side_3x5_fake"), mk.kattr(.legend, "*EJ6-7")),
                    mk.rule_node(mk.kattr(.file, "side_5x3_fake"), mk.kattr(.legend, "*EJ6-7")),
                    mk.rule_node(mk.kattr(.file, "roof_3x5"), mk.kattr(.legend, "6*-E5")),
                    mk.rule_node(mk.kattr(.file, "window_2"), mk.kattr(.legend, "9EL*018")),
                    mk.rule_node(mk.kattr(.file, "window_2"), mk.kattr(.legend, "9EL*018")),
                    mk.rule_node(mk.kattr(.file, "window_2"), mk.kattr(.legend, "9EL*018")),
                    mk.rule_node(mk.kattr(.file, "window_2"), mk.kattr(.legend, "9EL*018")),
                    mk.rule_node(mk.kattr(.file, "holes_4"), mk.kattr(.legend, "*E1-08")),
                    mk.rule_node(mk.kattr(.file, "small_windows_3"), mk.kattr(.legend, "*E1-08")),
                ),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{12, 12, 12}}, [][]int{[]int{0, 14, 0}})),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 13, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
            ),
            mk.markov_node(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.kattr(.comment, "draw secondary tubes"),
                mk.one(
                    mk.rule(
                        mk.in_exact_layer([]int{5, 12, 13}),
                        mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 5}),
                    ),
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{12, 12, 13}},
                            [][]int{[]int{12, 12, 12}},
                            [][]int{[]int{5, 12, 12}},
                        ),
                        mk.out_exact_layers(
                            [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, 5}},
                            [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                            [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        ),
                    ),
                ),
                mk.path_node(
                    mk.kattr(.from_, mk.one_of(mk.sym(13))),
                    mk.kattr(.to, mk.one_of(mk.sym(5))),
                    mk.kattr(.on, mk.one_of(mk.sym(9), mk.sym(14), mk.sym(21))),
                    mk.kattr(.color, mk.sym(11)),
                    mk.kattr(.inertia, true),
                    mk.kattr(.longest, true),
                ),
                mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{5})), mk.kattr(.out, mk.out_exact_layer([]int{10}))),
                mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{13})), mk.kattr(.out, mk.out_exact_layer([]int{5}))),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{10})), mk.kattr(.out, mk.out_exact_layer([]int{12}))),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{19})), mk.kattr(.out, mk.out_exact_layer([]int{14}))),
            mk.all(mk.kattr(.file, "small_windows_2"), mk.kattr(.legend, "E*1-08")),
            mk.all(mk.kattr(.file, "holes_2"), mk.kattr(.legend, "E*1-08")),
            mk.markov_node(
                mk.one(
                    mk.kattr(.in_, "hLL/=== hLL/=== hLL/==="),
                    mk.kattr(
                        .out,
                        mk.out_exact_layers(
                            [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0, mk.OUT_KEEP}},
                            [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0, mk.OUT_KEEP}},
                            [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 0, mk.OUT_KEEP}},
                        ),
                    ),
                ),
                mk.one(mk.kattr(.file, "window_1"), mk.kattr(.legend, "9EL*018")),
            ),
            mk.all(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{1, 1, 1, 1, 1}},
                        [][]int{[]int{1, 8, 8, 8, 1}},
                        [][]int{[]int{1, 8, 8, 8, 1}},
                        [][]int{[]int{1, 8, 8, 8, 1}},
                        [][]int{[]int{1, 1, 1, 1, 1}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, 1, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.one(mk.kattr(.file, "small_windows_2"), mk.kattr(.legend, "E*1-08")),
            mk.one(
                mk.rule_node(mk.kattr(.file, "holes_h_4"), mk.kattr(.legend, "*E1-08")),
                mk.rule_node(mk.kattr(.file, "holes_v_3"), mk.kattr(.legend, "*E1-08")),
            ),
            mk.prl(
                mk.kattr(.comment, "delete fine scaffold"),
                mk.rule(mk.in_exact_layer([]int{21}), mk.out_exact_layer([]int{0})),
                mk.rule(mk.in_exact_layer([]int{14}), mk.out_exact_layer([]int{0})),
                mk.rule(mk.in_exact_layer([]int{9}), mk.out_exact_layer([]int{0})),
                mk.rule(mk.in_exact_layer([]int{3}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{7}), mk.out_exact_layer([]int{1})),
            ),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{0}}, [][]int{[]int{1}})),
                mk.kattr(
                    .out,
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{10}}),
                ),
            ),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{1}})),
                mk.kattr(.out, mk.out_exact_layers([][]int{[]int{6}}, [][]int{[]int{mk.OUT_KEEP}})),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{10})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
            mk.all(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                        [][]int{[]int{1, 1, 1}, []int{0, 0, 0}},
                        [][]int{[]int{1, 8, 1}, []int{0, 0, 0}},
                        [][]int{[]int{1, 1, 1}, []int{0, 0, 0}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int{[]int{mk.OUT_KEEP, 1, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.comment, "propagate holes"),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int{[]int{1, 1, 1, 1, 1}, []int{0, 0, 0, 0, 0}},
                        [][]int{[]int{1, 8, 1, 1, 1}, []int{0, 0, 0, 0, 0}},
                        [][]int{[]int{1, 1, 1, 1, 1}, []int{0, 0, 0, 0, 0}},
                    ),
                    mk.out_exact_layers(
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 8, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int{[]int{1, 1, 1}, []int{0, 0, 0}},
                        [][]int{[]int{1, 8, 1}, []int{0, 0, 0}},
                        [][]int{[]int{1, 1, 1}, []int{0, 0, 0}},
                        [][]int{[]int{1, 1, 1}, []int{0, 0, 0}},
                        [][]int{[]int{1, 1, 1}, []int{0, 0, 0}},
                    ),
                    mk.out_exact_layers(
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{0, 1}}, [][]int{[]int{0, 0}})),
                mk.kattr(
                    .out,
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}, [][]int{[]int{2, mk.OUT_KEEP}}),
                ),
                mk.kattr(.comment, "top edges"),
            ),
            mk.all(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers([][]int{[]int{0, 1}, []int{0, 0}}, [][]int{[]int{2, 0}, []int{0, 2}}),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{2, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{8, 8, 8}, []int{0, 2, 0})),
                mk.kattr(.out, mk.out_exact_layer([]int{10, 10, 10}, []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP})),
            ),
            mk.all(
                mk.rule(
                    mk.in_exact_layer([]int{8, 8}, []int{0, 2}),
                    mk.out_exact_layer([]int{10, 10}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{10}}, [][]int{[]int{8}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{10}}),
                ),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{10})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
            mk.all(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers([][]int{[]int{1, 8, 1}}, [][]int{[]int{1, 8, 1}}, [][]int{[]int{1, 8, 1}}),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.one(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{1, 8, 8, 8, 8, 8}},
                        [][]int{[]int{1, 8, 8, 8, 8, 8}},
                        [][]int{[]int{1, 8, 8, 8, 8, 8}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{8, 8, 8, 1, 8}, []int{0, 0, 0, 0, 0})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 13, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{13})), mk.kattr(.out, mk.out_exact_layer([]int{8}))),
            mk.one(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{1, 1, 1, 1}},
                        [][]int{[]int{1, 8, 8, 1}},
                        [][]int{[]int{1, 8, 8, 1}},
                        [][]int{[]int{1, 8, 8, 1}},
                        [][]int{[]int{1, 1, 1, 1}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
                mk.kattr(.steps, 7),
                mk.kattr(.comment, "remove some windows"),
            ),
            mk.one(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers([][]int{[]int{1, 1, 1}}, [][]int{[]int{1, 8, 1}}, [][]int{[]int{1, 1, 1}}),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
                mk.kattr(.steps, 3),
            ),
            mk.one(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{1, 1, 1}},
                        [][]int{[]int{1, 8, 1}},
                        [][]int{[]int{1, 8, 1}},
                        [][]int{[]int{1, 1, 1}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 1, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
                mk.kattr(.steps, 2),
            ),
            mk.all(
                mk.kattr(.steps, 1),
                mk.kattr(.comment, "shorten panels"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{15}}, [][]int{[]int{1}}),
                    mk.out_exact_layers([][]int{[]int{1}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{16}}, [][]int{[]int{1}}),
                    mk.out_exact_layers([][]int{[]int{1}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{1}}, [][]int{[]int{15}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{1}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{1}}, [][]int{[]int{16}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{1}}),
                ),
            ),
            mk.all(
                mk.kattr(.steps, 1),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{16}}, [][]int{[]int{1}}),
                    mk.out_exact_layers([][]int{[]int{15}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{1}}, [][]int{[]int{16}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{15}}),
                ),
            ),
            mk.markov_node(
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layer([]int{3, 12})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
                ),
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{12, 12}, []int{12, 12})),
                    mk.kattr(.out, mk.out_exact_layer([]int{3, 3}, []int{3, 3})),
                ),
            ),
            mk.convolution_node(
                mk.kattr(.neighborhood, "VonNeumann"),
                mk.kattr(.steps, 1),
                mk.kattr(.comment, "mark radiator edges"),
                mk.rule(mk.sym(12), mk.sym(10), mk.kattr(.sum, "2..3"), mk.kattr(.values, mk.one_of(mk.sym(12)))),
            ),
            mk.markov_node(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.all(
                    mk.rule(
                        mk.in_exact_layers([][]int{[]int{12, 12}}, [][]int{[]int{13, 12}}),
                        mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, 13}}, [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}),
                    ),
                    mk.rule(
                        mk.in_exact_layers([][]int{[]int{12, 12}}, [][]int{[]int{0, 12}}),
                        mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, 0}}, [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}),
                    ),
                    mk.rule(
                        mk.in_exact_layer([]int{13, 12, 12}),
                        mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 13}),
                    ),
                    mk.rule(
                        mk.in_exact_layer([]int{0, 12, 12}),
                        mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 0}),
                    ),
                ),
                mk.one(
                    mk.rule(
                        mk.in_exact_layers([][]int{[]int{10, 12}}, [][]int{[]int{10, 10}}),
                        mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, 13}}, [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}),
                    ),
                    mk.rule(
                        mk.in_exact_layers([][]int{[]int{10, 12}}, [][]int{[]int{10, 10}}),
                        mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, 0}}, [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}),
                    ),
                ),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{10})), mk.kattr(.out, mk.out_exact_layer([]int{12}))),
            mk.all(
                mk.kattr(.steps, 1),
                mk.rule(mk.in_exact_layer([]int{1, 15, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 1, 15})),
                mk.rule(mk.in_exact_layer([]int{1, 16, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 1, 16})),
            ),
            mk.union_node(mk.kattr(.symbol, "0"), mk.kattr(.values, mk.one_of(mk.sym(1), mk.sym(21)))),
            mk.all(
                mk.kattr(.in_, "0hB 0hB 0hB"),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{21, 2, 2}},
                        [][]int{[]int{21, 0, mk.OUT_KEEP}},
                        [][]int{[]int{21, 0, mk.OUT_KEEP}},
                    ),
                ),
                mk.kattr(.comment, "deepen windows"),
            ),
            mk.all(
                mk.kattr(.in_, "0hB 0hB"),
                mk.kattr(.out, mk.out_exact_layers([][]int{[]int{21, 2, 2}}, [][]int{[]int{21, 0, mk.OUT_KEEP}})),
            ),
            mk.all(mk.kattr(.in_, "0hB"), mk.kattr(.out, mk.out_exact_layer([]int{21, 0, mk.OUT_KEEP}))),
            mk.all(
                mk.kattr(.comment, "deepen special windows"),
                mk.rule(mk.in_exact_layer([]int{18, 11, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 0, mk.OUT_KEEP})),
                mk.rule(mk.in_exact_layer([]int{1, 18, 0}), mk.out_exact_layer([]int{0, mk.OUT_KEEP, mk.OUT_KEEP})),
                mk.rule(mk.in_exact_layer([]int{1, 17, 0}), mk.out_exact_layer([]int{0, mk.OUT_KEEP, mk.OUT_KEEP})),
            ),
            mk.union_node(mk.kattr(.symbol, "#"), mk.kattr(.values, mk.one_of(mk.sym(1), mk.sym(8)))),
            mk.all(mk.kattr(.in_, "#BV"), mk.kattr(.out, mk.out_exact_layer([]int{8, mk.OUT_KEEP, 0}))),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{0, 17}, []int{17, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 0}, []int{0, mk.OUT_KEEP})),
            ),
            mk.all(
                mk.rule(
                    mk.in_exact_layer([]int{1, 8}, []int{1, 0}),
                    mk.out_exact_layer([]int{mk.OUT_KEEP, 10}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{0, 8}, []int{0, 0}),
                    mk.out_exact_layer([]int{mk.OUT_KEEP, 10}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
                ),
            ),
            mk.one(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{10, 8, 8, 8, 8, 8}},
                        [][]int{[]int{10, 8, 8, 8, 8, 8}},
                        [][]int{[]int{10, 8, 8, 8, 8, 8}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 10, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 10, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 10, mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.one(
                mk.kattr(.comment, "merge some special windows"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{8, 10, 8}}, [][]int{[]int{8, 10, 8}}, [][]int{[]int{8, 10, 8}}),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 8, mk.OUT_KEEP}},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{8, 10, 8}}, [][]int{[]int{8, 10, 8}}, [][]int{[]int{8, 10, 8}}),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 19, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 19, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 19, mk.OUT_KEEP}},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{8, 10, 8}}, [][]int{[]int{8, 10, 8}}, [][]int{[]int{8, 10, 8}}),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 19, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 19, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 19, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.in_, "0hB"),
                mk.kattr(.out, mk.out_exact_layer([]int{21, 0, mk.OUT_KEEP})),
                mk.kattr(.comment, "secondary deepening"),
            ),
            mk.prl(
                mk.rule(mk.in_exact_layer([]int{10}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{19}), mk.out_exact_layer([]int{1})),
            ),
            mk.all(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{0, 0, 1, 1}, []int{0, 11, 1, 1}, []int{0, 0, 1, 1}},
                        [][]int{[]int{0, 2, 0, 0}, []int{0, 11, 11, 11}, []int{0, 2, 0, 0}},
                        [][]int{[]int{0, 0, 0, 0}, []int{0, 0, 0, 0}, []int{0, 0, 0, 0}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{11, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{11, 2, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{11, 11, 11, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
                mk.kattr(.comment, "resolve some conflicts between tubes and borders"),
            ),
            mk.prl(
                mk.kattr(.comment, "color bottoms"),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int{[]int{0}},
                        [][]int{[]int{0}},
                        [][]int{[]int{0}},
                        [][]int{[]int{0}},
                        [][]int{[]int{1}},
                    ),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP}},
                        [][]int{[]int{6}},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int{[]int{0}},
                        [][]int{[]int{0}},
                        [][]int{[]int{0}},
                        [][]int{[]int{11}},
                        [][]int{[]int{1}},
                    ),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP}},
                        [][]int{[]int{6}},
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 6, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 1, mk.OUT_KEEP})),
            ),
            mk.all(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{0, 18, mk.IN_ANY}, []int{0, 1, 18}, []int{0, 0, 0}},
                        [][]int{[]int{0, 18, mk.IN_ANY}, []int{0, 1, 18}, []int{0, 0, 0}},
                        [][]int{[]int{0, 18, mk.IN_ANY}, []int{0, 1, 18}, []int{0, 0, 0}},
                        [][]int{[]int{0, 18, mk.IN_ANY}, []int{0, 1, 18}, []int{0, 0, 0}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{1, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{1, 1, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
            ),
            mk.union_node(mk.kattr(.symbol, "_"), mk.kattr(.values, mk.one_of(mk.sym(15), mk.sym(16)))),
            mk.markov_node(
                mk.kattr(.comment, "put panel holders"),
                mk.one(
                    mk.rule("__/OB", mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9})),
                    mk.rule(
                        mk.in_exact_layer([]int{15, 0}, []int{9, 0}),
                        mk.out_exact_layer([]int{mk.OUT_KEEP, 9}, []int{mk.OUT_KEEP, 9}),
                    ),
                    mk.rule(
                        mk.in_exact_layer([]int{9, 15}, []int{9, 0}),
                        mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9}),
                    ),
                ),
                mk.one(
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                        ),
                        mk.out_exact_layers(
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int{[]int{mk.OUT_KEEP, 9, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9, 9}},
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                        ),
                    ),
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                        ),
                        mk.out_exact_layers(
                            [][]int{[]int{mk.OUT_KEEP, 9, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9, 9}},
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                        ),
                    ),
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                        ),
                        mk.out_exact_layers(
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int{[]int{mk.OUT_KEEP, 9, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9, 9}},
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                        ),
                    ),
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                        ),
                        mk.out_exact_layers(
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int{[]int{mk.OUT_KEEP, 9, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9, 9}},
                        ),
                    ),
                ),
            ),
            mk.one(
                mk.kattr(.steps, 1),
                mk.rule_node(mk.kattr(.file, "cut_1"), mk.kattr(.legend, "0FG*")),
                mk.rule_node(mk.kattr(.file, "cut_2"), mk.kattr(.legend, "0FG*")),
            ),
            mk.markov_node(
                mk.one(
                    mk.rule("__/OB", mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9})),
                    mk.rule(
                        mk.in_exact_layer([]int{15, 0}, []int{9, 0}),
                        mk.out_exact_layer([]int{mk.OUT_KEEP, 9}, []int{mk.OUT_KEEP, 9}),
                    ),
                ),
                mk.one(
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                        ),
                        mk.out_exact_layers(
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int{[]int{mk.OUT_KEEP, 9, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9, 9}},
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                        ),
                    ),
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                        ),
                        mk.out_exact_layers(
                            [][]int{[]int{mk.OUT_KEEP, 9, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9, 9}},
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                        ),
                    ),
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                        ),
                        mk.out_exact_layers(
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int{[]int{mk.OUT_KEEP, 9, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9, 9}},
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                        ),
                    ),
                    mk.rule(
                        mk.in_exact_layers(
                            [][]int{[]int{0, 0, 0}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                            [][]int{[]int{0, 0, 15}, []int{0, 0, 0}},
                        ),
                        mk.out_exact_layers(
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int {
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            },
                            [][]int{[]int{mk.OUT_KEEP, 9, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9, 9}},
                        ),
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{9, 15}, []int{9, 0})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 9})),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{15, 16, 15}, []int{9, 9, 9})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{0, 0, 0})),
            ),
            mk.one(
                mk.kattr(.steps, 2),
                mk.rule_node(mk.kattr(.file, "bracing_v_3"), mk.kattr(.legend, "*1B")),
                mk.rule_node(mk.kattr(.file, "bracing_h_3"), mk.kattr(.legend, "*B1")),
            ),
            mk.one(
                mk.kattr(.steps, 3),
                mk.rule_node(mk.kattr(.file, "bracing_v_2"), mk.kattr(.legend, "*1B")),
                mk.rule_node(mk.kattr(.file, "bracing_h_2"), mk.kattr(.legend, "*B1")),
            ),
            mk.one(
                mk.kattr(.steps, 16),
                mk.rule_node(mk.kattr(.file, "bracing_v_1"), mk.kattr(.legend, "*1B")),
                mk.rule_node(mk.kattr(.file, "bracing_h_1"), mk.kattr(.legend, "*B1")),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int {
                            []int{mk.IN_ANY, 1, 1, 1},
                            []int{0, 0, 11, 1},
                            []int{0, 0, 0, 1},
                            []int{0, 0, 0, mk.IN_ANY},
                        },
                        [][]int {
                            []int{mk.IN_ANY, 1, 1, 1},
                            []int{0, 0, 11, 1},
                            []int{0, 0, 0, 1},
                            []int{0, 0, 0, mk.IN_ANY},
                        },
                        [][]int {
                            []int{mk.IN_ANY, 1, 1, 1},
                            []int{0, 0, 11, 1},
                            []int{0, 0, 0, 1},
                            []int{0, 0, 0, mk.IN_ANY},
                        },
                    ),
                    mk.out_exact_layers(
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, 1, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, 1, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
            ),
            mk.all(
                mk.rule_node(mk.kattr(.file, "roof_thing_7x11"), mk.kattr(.legend, "31*2")),
                mk.rule_node(mk.kattr(.file, "roof_thing_2"), mk.kattr(.legend, "31A2E*")),
            ),
            mk.all(
                mk.rule_node(mk.kattr(.file, "roof_thing_1"), mk.kattr(.legend, "31A2E*")),
                mk.rule_node(mk.kattr(.file, "roof_thing_5x9"), mk.kattr(.legend, "31*2")),
            ),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{mk.IN_ANY}}, [][]int{[]int{14}})),
                mk.kattr(.out, mk.out_exact_layers([][]int{[]int{0}}, [][]int{[]int{0}})),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{11, 10, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 11, mk.OUT_KEEP})),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{0, 1}, []int{11, 10})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 11})),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{10})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
            mk.prl(
                mk.rule(mk.in_exact_layer([]int{11}), mk.out_exact_layer([]int{3})),
                mk.rule(mk.in_exact_layer([]int{18}), mk.out_exact_layer([]int{5})),
                mk.rule(mk.in_exact_layer([]int{15}), mk.out_exact_layer([]int{5})),
                mk.rule(mk.in_exact_layer([]int{16}), mk.out_exact_layer([]int{2})),
                mk.rule(mk.in_exact_layer([]int{9}), mk.out_exact_layer([]int{1})),
                mk.rule(mk.in_exact_layer([]int{12}), mk.out_exact_layer([]int{2})),
                mk.rule(mk.in_exact_layer([]int{13}), mk.out_exact_layer([]int{3})),
                mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{22})),
                mk.rule(mk.in_exact_layer([]int{21}), mk.out_exact_layer([]int{23})),
            ),
        ),
    )
}
