// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_stablecrawlers :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{0, 0, 0}, []int{1, 2, 0}, []int{0, 0, 0})),
            mk.kattr(.steps, 20),
        ),
        mk.all(
            mk.rule(
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, 0, 0},
                    []int{1, 2, 0, 0},
                    []int{mk.IN_ANY, mk.IN_ANY, 0, 0},
                ),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 0, 0},
                    []int{0, 1, 2, 0},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 0, 0},
                ),
            ),
            mk.rule(
                mk.in_exact_layer([]int{1, 2, mk.IN_ANY}, []int{mk.IN_ANY, 0, mk.IN_ANY}, []int{0, 0, 0}),
                mk.out_exact_layer([]int{0, 1, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 2, mk.OUT_KEEP}, []int{0, 0, 0}),
            ),
        ),
    )
}
