// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_centralcrawlers :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.kattr(.origin, true),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 3})),
            mk.kattr(.steps, 10),
        ),
        mk.all(
            mk.kattr(.temperature, 5.0),
            mk.rule(mk.in_exact_layer([]int{2, 3, 0}), mk.out_exact_layer([]int{0, 2, 3})),
            mk.rule(
                mk.in_exact_layer([]int{2, 3}, []int{mk.IN_ANY, 0}),
                mk.out_exact_layer([]int{0, 2}, []int{mk.OUT_KEEP, 3}),
            ),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{0})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(3)),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.recompute, false),
            ),
        ),
    )
}
