// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_sokobanlevel2 :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.one(
            mk.kattr(.file, "Sokoban2"),
            mk.kattr(.legend, "042513"),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        ),
        mk.one(
            mk.kattr(.search, true),
            mk.kattr(.depth_coefficient, 1.0),
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{0, 1})),
            mk.rule(mk.in_exact_layer([]int{1, 2, 0}), mk.out_exact_layer([]int{0, 1, 2})),
            mk.observe_node(
                mk.kattr(.value, mk.sym(4)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
            ),
            mk.observe_node(
                mk.kattr(.value, mk.sym(5)),
                mk.kattr(.from_, mk.sym(2)),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(1)))),
            mk.observe_node(mk.kattr(.value, mk.sym(2)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(1)))),
            mk.observe_node(mk.kattr(.value, mk.sym(1)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(1)))),
        ),
    )
}
