// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_irregularmazegrowth :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(.origin, true),
        mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY, 0, 0}, []int{1, 0, 0}, []int{mk.IN_ANY, 0, 0})),
        mk.kattr(
            .out,
            mk.out_exact_layer(
                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                []int{1, 1, mk.OUT_KEEP},
                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
            ),
        ),
    )
}
