// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_flowers :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0}, []int{mk.IN_ANY}, []int{mk.IN_ANY}, []int{mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{1}, []int{mk.OUT_KEEP}, []int{mk.OUT_KEEP}, []int{mk.OUT_KEEP})),
        ),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer([]int{1}, []int{mk.IN_ANY}, []int{mk.IN_ANY}, []int{mk.IN_ANY}, []int{mk.IN_ANY}),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{2},
                    []int{mk.OUT_KEEP},
                    []int{mk.OUT_KEEP},
                    []int{mk.OUT_KEEP},
                    []int{mk.OUT_KEEP},
                ),
            ),
        ),
        mk.markov_node(
            mk.one(
                mk.rule(
                    mk.in_exact_layer([]int{2, 2, 2}, []int{2, 2, 2}, []int{2, 4, 2}),
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 4, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 3, mk.OUT_KEEP},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layer(
                        []int{2, 2, 2},
                        []int{2, 2, 2},
                        []int{2, 2, 2},
                        []int{4, 2, 2},
                        []int{mk.IN_ANY, mk.IN_ANY, 2},
                    ),
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 4, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 3, mk.OUT_KEEP},
                        []int{3, 3, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layer(
                        []int{2, 2, 2, 2, 2},
                        []int{2, 2, 2, 2, 2},
                        []int{2, 2, 2, 2, 2},
                        []int{2, 2, 4, 2, 2},
                        []int{2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 2},
                    ),
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 4, mk.OUT_KEEP, 4, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 3, mk.OUT_KEEP, 3, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 3, 3, 3, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{2, 2, 2}, []int{2, 4, 2}, []int{2, 3, 2}, []int{2, 3, 2}),
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, 5, mk.OUT_KEEP},
                        []int{5, 3, 5},
                        []int{mk.OUT_KEEP, 5, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
            ),
            mk.one(
                mk.kattr(
                    .in_,
                    mk.in_exact_layer(
                        []int{2, 2, 2, 2, 2},
                        []int{2, 2, 2, 2, 2},
                        []int{2, 2, 2, 2, 2},
                        []int{1, 1, 1, 1, 1},
                        []int{0, 0, 0, 0, 0},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, 4, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, 3, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, 3, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, 3, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
            ),
        ),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 4, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, 5, mk.OUT_KEEP},
                    []int{5, 3, 5},
                    []int{mk.OUT_KEEP, 5, mk.OUT_KEEP},
                ),
            ),
        ),
    )
}
