// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_stairspath :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(7)),
        mk.kattr(.origin, true),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_XY)),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, mk.IN_ANY, mk.IN_ANY, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 1})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0, 1, 0, 0, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{0, mk.OUT_KEEP, mk.OUT_KEEP, 5, 6, 0, 0})),
            mk.kattr(.steps, 1),
            mk.kattr(.comment, "finish"),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0, 1, 0, 0, 1})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{2, 3, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}),
            ),
            mk.kattr(.steps, 1),
            mk.kattr(.comment, "start"),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
        mk.one(
            mk.rule(
                mk.in_exact_layer([]int{2, 3, 0, 0, 0}),
                mk.out_exact_layer([]int{1, 4, 4, 2, 3}),
                mk.kattr(.comment, "forward"),
            ),
            mk.rule(
                mk.in_exact_layer(
                    []int{2, 3, 0, 0},
                    []int{mk.IN_ANY, 0, 0, 0},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 0},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 0},
                ),
                mk.out_exact_layer(
                    []int{1, 4, 4, 2},
                    []int{mk.OUT_KEEP, 0, 0, 3},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
                mk.kattr(.comment, "Turn"),
            ),
            mk.rule(
                mk.in_exact_layers(
                    [][]int{[]int{0, 0, 0, 0, 0}},
                    [][]int{[]int{0, 0, 0, 0, 0}},
                    [][]int{[]int{0, 0, 0, 0, 0}},
                    [][]int{[]int{2, 3, 0, 0, 0}},
                ),
                mk.out_exact_layers(
                    [][]int{[]int{1, 0, 0, 2, 3}},
                    [][]int{[]int{0, 0, 0, 4, 0}},
                    [][]int{[]int{0, 0, 0, 4, 0}},
                    [][]int{[]int{1, 4, 4, 1, 0}},
                ),
                mk.kattr(.comment, "stairs down"),
            ),
            mk.rule(
                mk.in_exact_layers(
                    [][]int{[]int{2, 3, 0, 0, 0}},
                    [][]int{[]int{0, 0, 0, 0, 0}},
                    [][]int{[]int{0, 0, 0, 0, 0}},
                    [][]int{[]int{0, 0, 0, 0, 0}},
                ),
                mk.out_exact_layers(
                    [][]int{[]int{1, 4, 4, 1, 0}},
                    [][]int{[]int{0, 0, 0, 4, 0}},
                    [][]int{[]int{0, 0, 0, 4, 0}},
                    [][]int{[]int{1, 0, 0, 2, 3}},
                ),
                mk.kattr(.comment, "stairs up"),
            ),
            mk.observe_node(
                mk.kattr(.value, mk.sym(5)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
            ),
            mk.observe_node(
                mk.kattr(.value, mk.sym(6)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(3))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(2)), mk.kattr(.to, mk.one_of(mk.sym(1)))),
            mk.observe_node(mk.kattr(.value, mk.sym(3)), mk.kattr(.to, mk.one_of(mk.sym(4)))),
            mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(1), mk.sym(4)))),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{2, 3, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1, 4, 4, 1})),
        ),
        mk.map_node(
            mk.kattr(.scale, "5/3 5/3 5/3"),
            mk.kattr(.values, mk.values_count(4)),
            mk.kattr(.folder, "Stairs"),
            mk.rule_node(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{4, 1, 4}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                    ),
                ),
                mk.kattr(.fout, "Line"),
                mk.kattr(.legend, "021"),
            ),
            mk.rule_node(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{0, 1, 4}, []int{0, 4, 0}},
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                    ),
                ),
                mk.kattr(.fout, "Turn"),
                mk.kattr(.legend, "021"),
            ),
            mk.rule_node(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{0, 0, 0}, []int{0, 4, 0}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{4, 1, 0}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                    ),
                ),
                mk.kattr(.fout, "Down"),
                mk.kattr(.legend, "021"),
            ),
            mk.rule_node(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{0, 1, 4}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{0, 4, 0}, []int{0, 0, 0}},
                    ),
                ),
                mk.kattr(.fout, "Up"),
                mk.kattr(.legend, "021"),
            ),
            mk.rule_node(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{4, 1, 0}, []int{0, 0, 0}},
                        [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                    ),
                ),
                mk.kattr(.fout, "End"),
                mk.kattr(.legend, "0213"),
            ),
        ),
    )
}
