// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_orientedescher :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.origin, true),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 2, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.values, mk.values_count(7)),
            mk.kattr(.tileset, "OrientedEscher"),
            mk.kattr(.periodic, true),
            mk.rule(mk.sym(2), "Empty"),
            mk.rule(mk.sym(1), "T"),
            mk.all(
                mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{0})),
                mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{5})),
            ),
        ),
    )
}
