// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_selectlongknots :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layers(
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, 1, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 2, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.values, mk.values_count(4)),
            mk.kattr(.tileset, "Knots3D"),
            mk.kattr(.tiles, "Knots3D/3"),
            mk.rule(mk.sym(1), "Empty"),
            mk.rule(mk.sym(2), "Line|Turn|Empty"),
            mk.markov_node(
                mk.sequence(
                    mk.one(
                        mk.kattr(.in_, mk.in_exact_layer([]int{1})),
                        mk.kattr(.out, mk.out_exact_layer([]int{2})),
                        mk.kattr(.steps, 1),
                    ),
                    mk.all(
                        mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})),
                        mk.kattr(.out, mk.out_exact_layer([]int{2, 2})),
                        mk.kattr(.steps, 60),
                    ),
                    mk.all(
                        mk.rule(mk.in_exact_layer([]int{2, 1}), mk.out_exact_layer([]int{3, 3})),
                        mk.rule(mk.in_exact_layer([]int{3, 2}), mk.out_exact_layer([]int{3, 3})),
                        mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{3, 3})),
                    ),
                ),
            ),
        ),
    )
}
