// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_forestfireca :: proc() -> Model_Config {
    return Model_Config{size = {600, 600, 1}, steps = 80, pixel_size = 1, iso = false}
}

model_palette_symbol_forestfireca :: proc(value: int) -> (u8, bool) {
    values := "BGR"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_forestfireca :: proc(value: int) -> (i32, bool) {
    return 0, false
}
