// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_dwarves :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(8)),
        mk.one(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 4, 4, 4, 4, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 4, mk.OUT_KEEP, mk.OUT_KEEP, 4, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 4, mk.OUT_KEEP, mk.OUT_KEEP, 4, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 4, 4, 4, 4, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 2, 2}, []int{2, 2, 2})),
            mk.kattr(.steps, 2),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 2),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{0, 1})),
            mk.rule(mk.in_exact_layer([]int{1, 2}), mk.out_exact_layer([]int{0, 6})),
            mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{3})),
            mk.rule(mk.in_exact_layer([]int{7}), mk.out_exact_layer([]int{1})),
            mk.rule(mk.in_exact_layer([]int{3, 0}), mk.out_exact_layer([]int{0, 3})),
            mk.rule(mk.in_exact_layer([]int{3, 4}), mk.out_exact_layer([]int{7, 5})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(1)),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.recompute, true),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(3)),
                mk.kattr(.to, mk.one_of(mk.sym(4))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.recompute, true),
            ),
        ),
    )
}
