// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_hills :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{mk.IN_ANY}}, [][]int{[]int{1}})),
            mk.kattr(.out, mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{0}})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_IDENTITY)),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1, 1})),
            mk.kattr(.steps, 8000),
        ),
        mk.convolution_node(
            mk.kattr(.neighborhood, "NoCorners"),
            mk.kattr(.periodic, true),
            mk.rule(mk.sym(0), mk.sym(1), mk.kattr(.sum, "10..18"), mk.kattr(.values, mk.one_of(mk.sym(1)))),
            mk.rule(mk.sym(1), mk.sym(0), mk.kattr(.sum, "10..18"), mk.kattr(.values, mk.one_of(mk.sym(0)))),
        ),
    )
}
