// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_wilson :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(8)),
        mk.kattr(.origin, true),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1, 0, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 2})),
            mk.rule(mk.in_exact_layer([]int{2, 0, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 2})),
        ),
        mk.markov_node(
            mk.one(
                mk.rule(mk.in_exact_layer([]int{3, 0, 2}), mk.out_exact_layer([]int{4, 4, 3})),
                mk.rule(mk.in_exact_layer([]int{3, 0, 4}), mk.out_exact_layer([]int{5, 4, 6})),
                mk.rule(mk.in_exact_layer([]int{3, 0, 1}), mk.out_exact_layer([]int{1, 1, 1})),
                mk.rule(mk.in_exact_layer([]int{1, 4, 4}), mk.out_exact_layer([]int{1, 1, 1})),
                mk.rule(mk.in_exact_layer([]int{6, 4, 5}), mk.out_exact_layer([]int{6, 0, 7})),
                mk.rule(mk.in_exact_layer([]int{7, 4, 4}), mk.out_exact_layer([]int{2, 0, 7})),
                mk.rule(mk.in_exact_layer([]int{7, 4, 6}), mk.out_exact_layer([]int{2, 0, 3})),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
        ),
    )
}
