// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_oddscale :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_IDENTITY)),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{0})),
            mk.kattr(.p, 0.5),
            mk.kattr(.steps, 1),
        ),
        mk.map_node(
            mk.kattr(.scale, "2 2 1"),
            mk.kattr(.values, mk.values_count(3)),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{1, 2, 1}, []int{2, 2, 2}, []int{1, 2, 1})),
        ),
    )
}
