// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_texture :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, mk.IN_ANY}, []int{0, 0, 0}, []int{mk.IN_ANY, 0, mk.IN_ANY})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY, 1, mk.IN_ANY}, []int{1, 0, 1})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 1, mk.OUT_KEEP}),
            ),
        ),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer([]int{mk.IN_ANY, 0, mk.IN_ANY}, []int{0, 1, 0}, []int{mk.IN_ANY, 0, mk.IN_ANY}),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 4, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.markov_node(
            mk.all(
                mk.rule(mk.in_exact_layer([]int{2, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
                mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
            ),
            mk.one(
                mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{2})),
                mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{3})),
            ),
        ),
    )
}
