// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_lostcity :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{4})),
            mk.kattr(.steps, 4),
            mk.kattr(.comment, "make a few lakes by random growth"),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{4, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 4})),
            mk.kattr(.steps, 24000),
        ),
        mk.convolution_node(
            mk.kattr(.neighborhood, "Moore"),
            mk.rule(mk.sym(4), mk.sym(0), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(0)))),
            mk.rule(mk.sym(0), mk.sym(4), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(4)))),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 20),
            mk.kattr(.comment, "make some land by a self-avoiding random walk with backtracking"),
        ),
        mk.markov_node(
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{2, 0, 0})),
                mk.kattr(.out, mk.out_exact_layer([]int{1, 1, 2})),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{2, 1, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{3, 3, 2})),
            ),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 1, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 0, mk.OUT_KEEP, mk.OUT_KEEP})),
            mk.kattr(.comment, "erode narrow sections of land"),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{4, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
            mk.rule(
                mk.in_exact_layer([]int{4, mk.IN_ANY}, []int{mk.IN_ANY, 1}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 3}),
            ),
            mk.rule(mk.in_exact_layer([]int{3, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
        mk.prl(
            mk.kattr(.steps, 2),
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
            mk.rule(mk.in_exact_layer([]int{3, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, 3}), mk.kattr(.p, 0.5)),
        ),
        mk.convolution_node(
            mk.kattr(.neighborhood, "Moore"),
            mk.rule(mk.sym(3), mk.sym(0), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(0)))),
            mk.rule(mk.sym(0), mk.sym(3), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(3), mk.sym(4)))),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, mk.IN_ANY}, []int{0, 0, 0}, []int{mk.IN_ANY, 0, mk.IN_ANY})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 5, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY, 5, mk.IN_ANY}, []int{5, 0, 5})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 5, mk.OUT_KEEP}),
            ),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
    )
}
