// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_nystromdungeon :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.kattr(.origin, true),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 1})),
            mk.kattr(.comment, "draw a grid"),
        ),
        mk.one(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{1, 0, 1, 0, 1, 0, 1, 0, 1},
                    []int{0, 0, 0, 0, 0, 0, 0, 0, 0},
                    []int{1, 0, 1, 0, 1, 0, 1, 0, 1},
                    []int{0, 0, 0, 0, 0, 0, 0, 0, 0},
                    []int{1, 0, 1, 0, 1, 0, 1, 0, 1},
                    []int{0, 0, 0, 0, 0, 0, 0, 0, 0},
                    []int{1, 0, 1, 0, 1, 0, 1, 0, 1},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{2, 2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2, 2},
                ),
            ),
        ),
        mk.markov_node(
            mk.kattr(.comment, "generate corridors with MazeBacktracker"),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{3, 0, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{4, 4, 3})),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{4, 4, 3})),
                mk.kattr(.out, mk.out_exact_layer([]int{3, 2, 2})),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{3})),
            mk.kattr(.out, mk.out_exact_layer([]int{4})),
            mk.kattr(.steps, 1),
            mk.kattr(.comment, "leave only one start"),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{3})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.comment, "forget other starts"),
        ),
        mk.markov_node(
            mk.kattr(.comment, "connect components"),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{4, 2, 2})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 4})),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{4, 0, 2})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2, 4})),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{4, 0, 4})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2, mk.OUT_KEEP})),
            mk.kattr(.steps, 5),
            mk.kattr(.comment, "insert cycles"),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{4})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.comment, "forget structure"),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 2, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{0, 0, 0}, []int{0, 0, 0})),
            mk.kattr(.comment, "retract dead ends"),
        ),
    )
}
