// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_putls :: proc() -> mk.Proc_Node {
    return mk.all(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(
            .in_,
            mk.in_exact_layer(
                []int{0, 0, 0, mk.IN_ANY},
                []int{0, 0, 0, mk.IN_ANY},
                []int{0, 0, 0, 0},
                []int{0, 0, 0, 0},
                []int{0, 0, 0, 0},
            ),
        ),
        mk.kattr(
            .out,
            mk.out_exact_layer(
                []int{0, 0, 0, mk.OUT_KEEP},
                []int{0, 1, 0, mk.OUT_KEEP},
                []int{0, 1, 0, 0},
                []int{0, 1, 1, 0},
                []int{0, 0, 0, 0},
            ),
        ),
    )
}
