// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_laplace :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(.origin, true),
        mk.kattr(.temperature, 12.0),
        mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{1})),
        mk.field_node(
            mk.kattr(.for_, mk.sym(1)),
            mk.kattr(.to, mk.one_of(mk.sym(1))),
            mk.kattr(.on, mk.one_of(mk.sym(0))),
            mk.kattr(.recompute, false),
        ),
    )
}
