// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_organicmechanic :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(10)),
        mk.kattr(.origin, true),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{3, 2})),
            mk.kattr(.steps, 12),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{3, 2, 0}), mk.out_exact_layer([]int{0, 3, 2})),
            mk.rule(
                mk.in_exact_layer([]int{3, 2}, []int{mk.IN_ANY, 0}),
                mk.out_exact_layer([]int{0, 3}, []int{mk.OUT_KEEP, 2}),
            ),
            mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{0, 1})),
            mk.rule(mk.in_exact_layer([]int{1, 8}), mk.out_exact_layer([]int{0, 6})),
            mk.rule(mk.in_exact_layer([]int{6}), mk.out_exact_layer([]int{4})),
            mk.rule(mk.in_exact_layer([]int{4, 0}), mk.out_exact_layer([]int{0, 4})),
            mk.rule(
                mk.in_exact_layer([]int{4, 7}, []int{0, mk.IN_ANY}),
                mk.out_exact_layer([]int{3, 2}, []int{5, mk.OUT_KEEP}),
            ),
            mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{1})),
            mk.rule(
                mk.in_exact_layer([]int{mk.IN_ANY, 0, mk.IN_ANY}, []int{0, 2, 0}, []int{mk.IN_ANY, 0, mk.IN_ANY}),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 7, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.rule(
                mk.in_exact_layer([]int{mk.IN_ANY, 0, mk.IN_ANY}, []int{0, 3, 0}, []int{mk.IN_ANY, 0, mk.IN_ANY}),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 8, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(1)),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.to, mk.one_of(mk.sym(8))),
                mk.kattr(.recompute, true),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(4)),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.to, mk.one_of(mk.sym(7))),
                mk.kattr(.recompute, true),
            ),
            mk.field_node(
                mk.kattr(.for_, mk.sym(9)),
                mk.kattr(.on, mk.one_of(mk.sym(2))),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
                mk.kattr(.recompute, true),
            ),
        ),
    )
}
