// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_wolfbasedapproach :: proc() -> Model_Config {
    return Model_Config{size = {70, 70, 1}, steps = 300, pixel_size = 4, iso = false}
}

model_palette_symbol_wolfbasedapproach :: proc(value: int) -> (u8, bool) {
    values := "DEIWRSA"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_wolfbasedapproach :: proc(value: int) -> (i32, bool) {
    return 0, false
}
