// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_noise :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{0}, []int{mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{1}, []int{mk.OUT_KEEP})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY}, []int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP}, []int{2})),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
        ),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{0, 2}), mk.out_exact_layer([]int{0, 0})),
            mk.rule(mk.in_exact_layer([]int{1, 2}), mk.out_exact_layer([]int{1, 1})),
        ),
    )
}
