// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_marchingsquares :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.p, 0.5),
            mk.kattr(.steps, 1),
        ),
        mk.map_node(
            mk.kattr(.scale, "3 3 1"),
            mk.kattr(.values, mk.values_count(2)),
            mk.rule(
                mk.in_exact_layer([]int{0, 0}, []int{0, 0}),
                mk.out_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{0, 0}, []int{0, 1}),
                mk.out_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 1}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{0, 0}, []int{1, 1}),
                mk.out_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}, []int{1, 1, 1}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{0, 1}, []int{1, 0}),
                mk.out_exact_layer([]int{0, 0, 1}, []int{0, 0, 0}, []int{1, 0, 0}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{0, 1}, []int{1, 1}),
                mk.out_exact_layer([]int{0, 0, 1}, []int{0, 0, 1}, []int{1, 1, 1}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{1, 1}, []int{1, 1}),
                mk.out_exact_layer([]int{1, 1, 1}, []int{1, 1, 1}, []int{1, 1, 1}),
            ),
        ),
    )
}
