// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_basicdungeongrowth :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.kattr(.origin, true),
        mk.union_node(mk.kattr(.symbol, "?"), mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(1)))),
        mk.one(
            mk.kattr(.in_, "**?**/*BBB*/*BBB?/*BBB*/**R**"),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{2, 2, 1, 2, 2},
                    []int{2, 4, 4, 4, 2},
                    []int{2, 4, 4, 4, 1},
                    []int{2, 4, 4, 4, 2},
                    []int{2, 2, 3, 2, 2},
                ),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{2, 3, 2}, []int{0, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 1, 2}, []int{0, 0, 0})),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{3}), mk.out_exact_layer([]int{4})),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{4})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 4})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{4, 4, 4}, []int{2, 4, 2}, []int{4, 4, 4})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{4, mk.OUT_KEEP, 4},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{4, 4, 4}, []int{4, 2, 4}, []int{4, 4, 4})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 4, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
    )
}
