// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_apartemazements :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_XY)),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layers(
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, 1, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                ),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{1}}, [][]int{[]int{0}})),
            mk.kattr(.out, mk.out_exact_layers([][]int{[]int{2}}, [][]int{[]int{0}})),
        ),
        mk.wfc_node(
            mk.kattr(.values, mk.values_count(12)),
            mk.kattr(.tileset, "Paths"),
            mk.rule(mk.sym(1), "Empty"),
            mk.rule(mk.sym(2), "Empty|Line|Up|Turn|X"),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layer([]int{0})),
                mk.kattr(.out, mk.out_exact_layer([]int{11})),
                mk.kattr(.comment, "draw earth"),
            ),
            mk.prl(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers([][]int{[]int{mk.IN_ANY}}, [][]int{[]int{mk.IN_ANY}}, [][]int{[]int{11}}),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{0}}),
                ),
                mk.kattr(.comment, "remove extra earth"),
            ),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{11}}, [][]int{[]int{11}})),
                mk.kattr(.out, mk.out_exact_layers([][]int{[]int{10}}, [][]int{[]int{9}})),
                mk.kattr(.comment, "draw grass"),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{11})), mk.kattr(.out, mk.out_exact_layer([]int{10}))),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layer([]int{1})),
                mk.kattr(.out, mk.out_exact_layer([]int{11})),
                mk.kattr(.p, 0.25),
                mk.kattr(.steps, 1),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
            mk.all(
                mk.kattr(.comment, "draw columns"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{2}}),
                    mk.out_exact_layers([][]int{[]int{7}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{7}}),
                    mk.out_exact_layers([][]int{[]int{7}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
            ),
            mk.all(
                mk.kattr(.comment, "remove extra columns"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{9, 9}}, [][]int{[]int{7, 7}}),
                    mk.out_exact_layers([][]int{[]int{9, 9}}, [][]int{[]int{0, 0}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{9, 9}}, [][]int{[]int{7, 2}}, [][]int{[]int{7, 7}}),
                    mk.out_exact_layers([][]int{[]int{9, 9}}, [][]int{[]int{0, 2}}, [][]int{[]int{7, 7}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{7}}),
                    mk.out_exact_layers([][]int{[]int{0}}, [][]int{[]int{0}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{7}}, [][]int{[]int{0}}),
                    mk.out_exact_layers([][]int{[]int{0}}, [][]int{[]int{0}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{5}}, [][]int{[]int{7}}),
                    mk.out_exact_layers([][]int{[]int{5}}, [][]int{[]int{0}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{mk.IN_ANY, 7}}, [][]int{[]int{5, mk.IN_ANY}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP, 0}}, [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}}),
                ),
            ),
            mk.all(
                mk.kattr(.comment, "draw corner columns"),
                mk.rule(
                    mk.in_exact_layers(
                        [][]int {
                            []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                            []int{mk.IN_ANY, 0, mk.IN_ANY},
                            []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        },
                        [][]int{[]int{mk.IN_ANY, 3, mk.IN_ANY}, []int{3, 2, 0}, []int{mk.IN_ANY, 0, mk.IN_ANY}},
                    ),
                    mk.out_exact_layers(
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, 7, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                        [][]int {
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                            []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        },
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{0}}, [][]int{[]int{7}}),
                    mk.out_exact_layers([][]int{[]int{7}}, [][]int{[]int{7}}),
                ),
            ),
            mk.all(
                mk.kattr(.comment, "place windows"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{mk.IN_ANY, 3, 3, 3, mk.IN_ANY}}, [][]int{[]int{7, 0, 0, 0, 7}}),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 6, 6, 6, mk.OUT_KEEP}},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{mk.IN_ANY, 6, 6, 6, mk.IN_ANY}}, [][]int{[]int{7, 0, 0, 0, 7}}),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 6, 6, 6, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.prl(
                mk.kattr(.comment, "find h-uneven windows"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{6, 7, 2, 3}}, [][]int{[]int{6, 7, 7, 6}}),
                    mk.out_exact_layers(
                        [][]int{[]int{8, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{8, mk.OUT_KEEP, mk.OUT_KEEP, 8}},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{6, 7, 7, 6}}, [][]int{[]int{6, 7, 2, 3}}),
                    mk.out_exact_layers(
                        [][]int{[]int{8, mk.OUT_KEEP, mk.OUT_KEEP, 8}},
                        [][]int{[]int{8, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}},
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.comment, "mark h-uneven windows"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{8}}, [][]int{[]int{6}}),
                    mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{8}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{6}}, [][]int{[]int{8}}),
                    mk.out_exact_layers([][]int{[]int{8}}, [][]int{[]int{mk.OUT_KEEP}}),
                ),
            ),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layer([]int{6, 7, 7, 6}, []int{0, 0, 0, 0})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer(
                        []int{mk.OUT_KEEP, 6, 6, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    ),
                ),
                mk.kattr(.comment, "merge h-even windows"),
            ),
            mk.prl(
                mk.kattr(.in_, mk.in_exact_layer([]int{8})),
                mk.kattr(.out, mk.out_exact_layer([]int{6})),
                mk.kattr(.comment, "erase markings"),
            ),
            mk.prl(
                mk.kattr(.comment, "find v-uneven windows"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{7, 6}}, [][]int{[]int{2, 3}}, [][]int{[]int{6, 6}}),
                    mk.out_exact_layers(
                        [][]int{[]int{mk.OUT_KEEP, 8}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{8, 8}},
                    ),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{6, 6}}, [][]int{[]int{2, 3}}, [][]int{[]int{7, 6}}),
                    mk.out_exact_layers(
                        [][]int{[]int{8, 8}},
                        [][]int{[]int{mk.OUT_KEEP, mk.OUT_KEEP}},
                        [][]int{[]int{mk.OUT_KEEP, 8}},
                    ),
                ),
            ),
            mk.all(
                mk.kattr(.comment, "mark v-uneven windows"),
                mk.rule(mk.in_exact_layer([]int{6, 8}), mk.out_exact_layer([]int{8, mk.OUT_KEEP})),
                mk.rule(mk.in_exact_layer([]int{8, 6}), mk.out_exact_layer([]int{mk.OUT_KEEP, 8})),
            ),
            mk.prl(
                mk.kattr(.comment, "merge v-even windows"),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{6, 0}}, [][]int{[]int{3, 0}}, [][]int{[]int{6, 0}}),
                    mk.out_exact_layers([][]int{[]int{6, 0}}, [][]int{[]int{6, 0}}, [][]int{[]int{6, 0}}),
                ),
                mk.rule(
                    mk.in_exact_layers([][]int{[]int{6, 0}}, [][]int{[]int{2, 0}}, [][]int{[]int{6, 0}}),
                    mk.out_exact_layers([][]int{[]int{6, 0}}, [][]int{[]int{6, 0}}, [][]int{[]int{6, 0}}),
                ),
            ),
            mk.prl(
                mk.kattr(.comment, "forget structure"),
                mk.rule(mk.in_exact_layer([]int{7}), mk.out_exact_layer([]int{3})),
                mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{3})),
                mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{3})),
                mk.rule(mk.in_exact_layer([]int{8}), mk.out_exact_layer([]int{6})),
            ),
            mk.prl(
                mk.kattr(
                    .in_,
                    mk.in_exact_layers(
                        [][]int{[]int{3, 3, 3, 3, 3}},
                        [][]int{[]int{3, 6, 6, 6, 3}},
                        [][]int{[]int{3, 6, 6, 6, 3}},
                        [][]int{[]int{3, 6, 6, 6, 3}},
                        [][]int{[]int{3, 6, 6, 6, 3}},
                        [][]int{[]int{3, 3, 3, 3, 3}},
                    ),
                ),
                mk.kattr(
                    .out,
                    mk.out_exact_layers(
                        [][]int{[]int{3, 3, 3, 3, 3}},
                        [][]int{[]int{3, 3, 3, 3, 3}},
                        [][]int{[]int{3, 3, 3, 3, 3}},
                        [][]int{[]int{3, 3, 3, 3, 3}},
                        [][]int{[]int{3, 3, 3, 3, 3}},
                        [][]int{[]int{3, 3, 3, 3, 3}},
                    ),
                ),
            ),
        ),
    )
}
