// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_smartsaw :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(9)),
        mk.kattr(.origin, true),
        mk.union_node(mk.kattr(.symbol, "?"), mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(2)))),
        mk.union_node(mk.kattr(.symbol, "_"), mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(8)))),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1, 0, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 2})),
            mk.rule(mk.in_exact_layer([]int{2, 0, 0}), mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 2})),
        ),
        mk.markov_node(
            mk.markov_node(
                mk.markov_node(
                    mk.one(mk.kattr(.in_, "Y_D"), mk.kattr(.out, mk.out_exact_layer([]int{7, 6, 4}))),
                    mk.one(
                        mk.kattr(.in_, mk.in_exact_layer([]int{3, 5, 5})),
                        mk.kattr(.out, mk.out_exact_layer([]int{2, 8, 1})),
                    ),
                ),
                mk.all(mk.kattr(.in_, "G_D"), mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 6, 4}))),
                mk.markov_node(
                    mk.one(
                        mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 2})),
                        mk.kattr(.out, mk.out_exact_layer([]int{5, 5, 3})),
                    ),
                    mk.one(
                        mk.kattr(.in_, mk.in_exact_layer([]int{1, 5, 5})),
                        mk.kattr(.out, mk.out_exact_layer([]int{2, 8, 1})),
                    ),
                ),
                mk.sequence(
                    mk.one(
                        mk.kattr(.in_, "**D/**_/WWU"),
                        mk.kattr(
                            .out,
                            mk.out_exact_layer(
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{1, 8, 2},
                            ),
                        ),
                    ),
                    mk.all(
                        mk.rule(
                            "*_*/_G_",
                            mk.out_exact_layer(
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, 2, mk.OUT_KEEP},
                            ),
                        ),
                        mk.rule(
                            "*?*/?E?",
                            mk.out_exact_layer(
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                            ),
                        ),
                        mk.rule(
                            "*_*/_U_",
                            mk.out_exact_layer(
                                []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                                []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                            ),
                        ),
                    ),
                ),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{8})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
        ),
    )
}
