// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

load_model_node :: proc(name: string) -> (mk.Proc_Node, bool) {
    switch name {
    case "Apartemazements":
        return model_apartemazements(), true
    case "Backtracker":
        return model_backtracker(), true
    case "BacktrackerCycle":
        return model_backtrackercycle(), true
    case "Basic":
        return model_basic(), true
    case "BasicBrickWall":
        return model_basicbrickwall(), true
    case "BasicDijkstraDungeon":
        return model_basicdijkstradungeon(), true
    case "BasicDijkstraFill":
        return model_basicdijkstrafill(), true
    case "BasicDungeonGrowth":
        return model_basicdungeongrowth(), true
    case "BasicKeys":
        return model_basickeys(), true
    case "BasicPartitioning":
        return model_basicpartitioning(), true
    case "BasicSkyline":
        return model_basicskyline(), true
    case "BasicSnake":
        return model_basicsnake(), true
    case "BernoulliPercolation":
        return model_bernoullipercolation(), true
    case "BiasedGrowth":
        return model_biasedgrowth(), true
    case "BiasedGrowthContraction":
        return model_biasedgrowthcontraction(), true
    case "BiasedMazeGrowth":
        return model_biasedmazegrowth(), true
    case "BiasedVoronoi":
        return model_biasedvoronoi(), true
    case "BishopParity":
        return model_bishopparity(), true
    case "BlueNoise":
        return model_bluenoise(), true
    case "CarmaTower":
        return model_carmatower(), true
    case "Cave":
        return model_cave(), true
    case "CaveContour":
        return model_cavecontour(), true
    case "CentralCrawlers":
        return model_centralcrawlers(), true
    case "CentralSAW":
        return model_centralsaw(), true
    case "ChainDungeon":
        return model_chaindungeon(), true
    case "ChainDungeonMaze":
        return model_chaindungeonmaze(), true
    case "ChainMaze":
        return model_chainmaze(), true
    case "Chase":
        return model_chase(), true
    case "Circuit":
        return model_circuit(), true
    case "ClosedSurface":
        return model_closedsurface(), true
    case "ColoredKnots":
        return model_coloredknots(), true
    case "CompleteSAW":
        return model_completesaw(), true
    case "CompleteSAWSmart":
        return model_completesawsmart(), true
    case "ConnectedCaves":
        return model_connectedcaves(), true
    case "ConstrainedCaves":
        return model_constrainedcaves(), true
    case "Counting":
        return model_counting(), true
    case "Coupling":
        return model_coupling(), true
    case "Crawlers":
        return model_crawlers(), true
    case "CrawlersChase":
        return model_crawlerschase(), true
    case "CrossCountry":
        return model_crosscountry(), true
    case "Cycles":
        return model_cycles(), true
    case "DenseSAW":
        return model_densesaw(), true
    case "DiagonalPath":
        return model_diagonalpath(), true
    case "Digger":
        return model_digger(), true
    case "DijkstraDungeon":
        return model_dijkstradungeon(), true
    case "DualRetraction":
        return model_dualretraction(), true
    case "DualRetraction3D":
        return model_dualretraction3d(), true
    case "DungeonGrowth":
        return model_dungeongrowth(), true
    case "DwarfPath":
        return model_dwarfpath(), true
    case "Dwarves":
        return model_dwarves(), true
    case "Escher":
        return model_escher(), true
    case "EscherSurface":
        return model_eschersurface(), true
    case "EuclideanPath":
        return model_euclideanpath(), true
    case "FindLongCycle":
        return model_findlongcycle(), true
    case "FireNoise":
        return model_firenoise(), true
    case "Flowers":
        return model_flowers(), true
    case "Forest":
        return model_forest(), true
    case "ForestFire":
        return model_forestfire(), true
    case "ForestFireCA":
        return model_forestfireca(), true
    case "GameOfLife":
        return model_gameoflife(), true
    case "GoTo":
        return model_goto(), true
    case "GoToGradient":
        return model_gotogradient(), true
    case "GrowTo":
        return model_growto(), true
    case "Growth":
        return model_growth(), true
    case "GrowthCompetition":
        return model_growthcompetition(), true
    case "GrowthContraction":
        return model_growthcontraction(), true
    case "GrowthWalk":
        return model_growthwalk(), true
    case "HamiltonianPath":
        return model_hamiltonianpath(), true
    case "HamiltonianPaths":
        return model_hamiltonianpaths(), true
    case "Hills":
        return model_hills(), true
    case "IrregularMazeGrowth":
        return model_irregularmazegrowth(), true
    case "IrregularSAW":
        return model_irregularsaw(), true
    case "Island":
        return model_island(), true
    case "Keys":
        return model_keys(), true
    case "KnightPatrol":
        return model_knightpatrol(), true
    case "Knots2D":
        return model_knots2d(), true
    case "Knots3D":
        return model_knots3d(), true
    case "Laplace":
        return model_laplace(), true
    case "Lightning":
        return model_lightning(), true
    case "LoopErasedWalk":
        return model_looperasedwalk(), true
    case "LoopGrowth":
        return model_loopgrowth(), true
    case "LostCity":
        return model_lostcity(), true
    case "MarchingSquares":
        return model_marchingsquares(), true
    case "MazeBacktracker":
        return model_mazebacktracker(), true
    case "MazeGrowth":
        return model_mazegrowth(), true
    case "MazeMap":
        return model_mazemap(), true
    case "MazeTrail":
        return model_mazetrail(), true
    case "ModernHouse":
        return model_modernhouse(), true
    case "MultiHeadedDungeon":
        return model_multiheadeddungeon(), true
    case "MultiHeadedWalk":
        return model_multiheadedwalk(), true
    case "MultiHeadedWalkDungeon":
        return model_multiheadedwalkdungeon(), true
    case "MultiSokoban8":
        return model_multisokoban8(), true
    case "MultiSokoban9":
        return model_multisokoban9(), true
    case "NestedGrowth":
        return model_nestedgrowth(), true
    case "NoDeadEnds":
        return model_nodeadends(), true
    case "Noise":
        return model_noise(), true
    case "NystromDungeon":
        return model_nystromdungeon(), true
    case "OddScale":
        return model_oddscale(), true
    case "OddScale3D":
        return model_oddscale3d(), true
    case "OpenCave":
        return model_opencave(), true
    case "OpenCave3D":
        return model_opencave3d(), true
    case "OrganicMechanic":
        return model_organicmechanic(), true
    case "OrientedEscher":
        return model_orientedescher(), true
    case "PaintCompetition":
        return model_paintcompetition(), true
    case "ParallelGrowth":
        return model_parallelgrowth(), true
    case "ParallelMazeGrowth":
        return model_parallelmazegrowth(), true
    case "ParallelWalk":
        return model_parallelwalk(), true
    case "Partitioning":
        return model_partitioning(), true
    case "Percolation":
        return model_percolation(), true
    case "PeriodicEscher":
        return model_periodicescher(), true
    case "PillarsOfEternity":
        return model_pillarsofeternity(), true
    case "Push":
        return model_push(), true
    case "PutColoredLs":
        return model_putcoloredls(), true
    case "PutLs":
        return model_putls(), true
    case "RainbowGrowth":
        return model_rainbowgrowth(), true
    case "RandomWalk":
        return model_randomwalk(), true
    case "Rectangle":
        return model_rectangle(), true
    case "RegularPath":
        return model_regularpath(), true
    case "RegularSAW":
        return model_regularsaw(), true
    case "RegularSAWRestart":
        return model_regularsawrestart(), true
    case "River":
        return model_river(), true
    case "SAWRestart":
        return model_sawrestart(), true
    case "SeaVilla":
        return model_seavilla(), true
    case "SelectLargeCaves":
        return model_selectlargecaves(), true
    case "SelectLongKnots":
        return model_selectlongknots(), true
    case "SelfAvoidingWalk":
        return model_selfavoidingwalk(), true
    case "SequentialSnake":
        return model_sequentialsnake(), true
    case "SequentialSokoban":
        return model_sequentialsokoban(), true
    case "Sewers":
        return model_sewers(), true
    case "SmartSAW":
        return model_smartsaw(), true
    case "SmarterDigger":
        return model_smarterdigger(), true
    case "SmoothTrail":
        return model_smoothtrail(), true
    case "Snake":
        return model_snake(), true
    case "SnellLaw":
        return model_snelllaw(), true
    case "SoftPath":
        return model_softpath(), true
    case "SokobanLevel1":
        return model_sokobanlevel1(), true
    case "SokobanLevel2":
        return model_sokobanlevel2(), true
    case "StableCrawlers":
        return model_stablecrawlers(), true
    case "StairsPath":
        return model_stairspath(), true
    case "StochasticVoronoi":
        return model_stochasticvoronoi(), true
    case "StormySnellLaw":
        return model_stormysnelllaw(), true
    case "StrangeDungeon":
        return model_strangedungeon(), true
    case "StrangeGrowth":
        return model_strangegrowth(), true
    case "StrangeNoise":
        return model_strangenoise(), true
    case "SubmergedKnots":
        return model_submergedknots(), true
    case "Surface":
        return model_surface(), true
    case "Tetris":
        return model_tetris(), true
    case "Texture":
        return model_texture(), true
    case "TileDungeon":
        return model_tiledungeon(), true
    case "TilePath":
        return model_tilepath(), true
    case "Trail":
        return model_trail(), true
    case "Voronoi":
        return model_voronoi(), true
    case "WaveBrickWall":
        return model_wavebrickwall(), true
    case "WaveDungeon":
        return model_wavedungeon(), true
    case "WaveFlowers":
        return model_waveflowers(), true
    case "Wilson":
        return model_wilson(), true
    case "WolfBasedApproach":
        return model_wolfbasedapproach(), true
    }
    return {}, false
}
