// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_dualretraction3d :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.kattr(.origin, true),
        mk.kattr(.folder, "DualRetraction"),
        mk.one(
            mk.rule_node(mk.kattr(.file, "Room1"), mk.kattr(.legend, "0*123")),
            mk.rule_node(mk.kattr(.file, "Room2"), mk.kattr(.legend, "0*1432")),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{3})),
            mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{3})),
        ),
        mk.all(
            mk.rule(
                mk.in_exact_layers(
                    [][]int{[]int{0, 0, 0}, []int{0, 3, 0}, []int{0, 0, 0}},
                    [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                ),
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                ),
            ),
            mk.rule(
                mk.in_exact_layer([]int{3, 3, 3}, []int{4, 0, 4}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 4, mk.OUT_KEEP}),
            ),
            mk.rule(
                mk.in_exact_layer([]int{4, 4, 4}, []int{4, 0, 4}),
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 4, mk.OUT_KEEP}),
            ),
            mk.rule(
                mk.in_exact_layers(
                    [][]int{[]int{4, 4, 4}, []int{4, 3, 4}, []int{4, 4, 4}},
                    [][]int{[]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0}},
                ),
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 4, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                ),
            ),
        ),
    )
}
