// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_submergedknots :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layers(
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, 1, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 0, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                ),
            ),
        ),
        mk.wfc_node(
            mk.kattr(.values, mk.values_count(3)),
            mk.kattr(.tileset, "Knots3D"),
            mk.kattr(.tiles, "Knots3D/4"),
            mk.rule(mk.sym(1), "Empty"),
            mk.sequence(
                mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
                mk.all(
                    mk.kattr(.in_, mk.in_exact_layers([][]int{[]int{mk.IN_ANY}}, [][]int{[]int{2}})),
                    mk.kattr(.out, mk.out_exact_layers([][]int{[]int{mk.OUT_KEEP}}, [][]int{[]int{0}})),
                    mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_IDENTITY)),
                ),
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{2, 0})),
                    mk.kattr(.out, mk.out_exact_layer([]int{2, 2})),
                    mk.kattr(.steps, 42000),
                ),
            ),
        ),
    )
}
