// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config :: proc(name: string) -> (Model_Config, bool) {
    switch name {
    case "Apartemazements":
        return default_model_config_apartemazements(), true
    case "Backtracker":
        return default_model_config_backtracker(), true
    case "BacktrackerCycle":
        return default_model_config_backtrackercycle(), true
    case "Basic":
        return default_model_config_basic(), true
    case "BasicBrickWall":
        return default_model_config_basicbrickwall(), true
    case "BasicDijkstraDungeon":
        return default_model_config_basicdijkstradungeon(), true
    case "BasicDijkstraFill":
        return default_model_config_basicdijkstrafill(), true
    case "BasicDungeonGrowth":
        return default_model_config_basicdungeongrowth(), true
    case "BasicKeys":
        return default_model_config_basickeys(), true
    case "BasicPartitioning":
        return default_model_config_basicpartitioning(), true
    case "BasicSkyline":
        return default_model_config_basicskyline(), true
    case "BasicSnake":
        return default_model_config_basicsnake(), true
    case "BernoulliPercolation":
        return default_model_config_bernoullipercolation(), true
    case "BiasedGrowth":
        return default_model_config_biasedgrowth(), true
    case "BiasedGrowthContraction":
        return default_model_config_biasedgrowthcontraction(), true
    case "BiasedMazeGrowth":
        return default_model_config_biasedmazegrowth(), true
    case "BiasedVoronoi":
        return default_model_config_biasedvoronoi(), true
    case "BishopParity":
        return default_model_config_bishopparity(), true
    case "BlueNoise":
        return default_model_config_bluenoise(), true
    case "CarmaTower":
        return default_model_config_carmatower(), true
    case "Cave":
        return default_model_config_cave(), true
    case "CaveContour":
        return default_model_config_cavecontour(), true
    case "CentralCrawlers":
        return default_model_config_centralcrawlers(), true
    case "CentralSAW":
        return default_model_config_centralsaw(), true
    case "ChainDungeon":
        return default_model_config_chaindungeon(), true
    case "ChainDungeonMaze":
        return default_model_config_chaindungeonmaze(), true
    case "ChainMaze":
        return default_model_config_chainmaze(), true
    case "Chase":
        return default_model_config_chase(), true
    case "Circuit":
        return default_model_config_circuit(), true
    case "ClosedSurface":
        return default_model_config_closedsurface(), true
    case "ColoredKnots":
        return default_model_config_coloredknots(), true
    case "CompleteSAW":
        return default_model_config_completesaw(), true
    case "CompleteSAWSmart":
        return default_model_config_completesawsmart(), true
    case "ConnectedCaves":
        return default_model_config_connectedcaves(), true
    case "ConstrainedCaves":
        return default_model_config_constrainedcaves(), true
    case "Counting":
        return default_model_config_counting(), true
    case "Coupling":
        return default_model_config_coupling(), true
    case "Crawlers":
        return default_model_config_crawlers(), true
    case "CrawlersChase":
        return default_model_config_crawlerschase(), true
    case "CrossCountry":
        return default_model_config_crosscountry(), true
    case "Cycles":
        return default_model_config_cycles(), true
    case "DenseSAW":
        return default_model_config_densesaw(), true
    case "DiagonalPath":
        return default_model_config_diagonalpath(), true
    case "Digger":
        return default_model_config_digger(), true
    case "DijkstraDungeon":
        return default_model_config_dijkstradungeon(), true
    case "DualRetraction":
        return default_model_config_dualretraction(), true
    case "DualRetraction3D":
        return default_model_config_dualretraction3d(), true
    case "DungeonGrowth":
        return default_model_config_dungeongrowth(), true
    case "DwarfPath":
        return default_model_config_dwarfpath(), true
    case "Dwarves":
        return default_model_config_dwarves(), true
    case "Escher":
        return default_model_config_escher(), true
    case "EscherSurface":
        return default_model_config_eschersurface(), true
    case "EuclideanPath":
        return default_model_config_euclideanpath(), true
    case "FindLongCycle":
        return default_model_config_findlongcycle(), true
    case "FireNoise":
        return default_model_config_firenoise(), true
    case "Flowers":
        return default_model_config_flowers(), true
    case "Forest":
        return default_model_config_forest(), true
    case "ForestFire":
        return default_model_config_forestfire(), true
    case "ForestFireCA":
        return default_model_config_forestfireca(), true
    case "GameOfLife":
        return default_model_config_gameoflife(), true
    case "GoTo":
        return default_model_config_goto(), true
    case "GoToGradient":
        return default_model_config_gotogradient(), true
    case "GrowTo":
        return default_model_config_growto(), true
    case "Growth":
        return default_model_config_growth(), true
    case "GrowthCompetition":
        return default_model_config_growthcompetition(), true
    case "GrowthContraction":
        return default_model_config_growthcontraction(), true
    case "GrowthWalk":
        return default_model_config_growthwalk(), true
    case "HamiltonianPath":
        return default_model_config_hamiltonianpath(), true
    case "HamiltonianPaths":
        return default_model_config_hamiltonianpaths(), true
    case "Hills":
        return default_model_config_hills(), true
    case "IrregularMazeGrowth":
        return default_model_config_irregularmazegrowth(), true
    case "IrregularSAW":
        return default_model_config_irregularsaw(), true
    case "Island":
        return default_model_config_island(), true
    case "Keys":
        return default_model_config_keys(), true
    case "KnightPatrol":
        return default_model_config_knightpatrol(), true
    case "Knots2D":
        return default_model_config_knots2d(), true
    case "Knots3D":
        return default_model_config_knots3d(), true
    case "Laplace":
        return default_model_config_laplace(), true
    case "Lightning":
        return default_model_config_lightning(), true
    case "LoopErasedWalk":
        return default_model_config_looperasedwalk(), true
    case "LoopGrowth":
        return default_model_config_loopgrowth(), true
    case "LostCity":
        return default_model_config_lostcity(), true
    case "MarchingSquares":
        return default_model_config_marchingsquares(), true
    case "MazeBacktracker":
        return default_model_config_mazebacktracker(), true
    case "MazeGrowth":
        return default_model_config_mazegrowth(), true
    case "MazeMap":
        return default_model_config_mazemap(), true
    case "MazeTrail":
        return default_model_config_mazetrail(), true
    case "ModernHouse":
        return default_model_config_modernhouse(), true
    case "MultiHeadedDungeon":
        return default_model_config_multiheadeddungeon(), true
    case "MultiHeadedWalk":
        return default_model_config_multiheadedwalk(), true
    case "MultiHeadedWalkDungeon":
        return default_model_config_multiheadedwalkdungeon(), true
    case "MultiSokoban8":
        return default_model_config_multisokoban8(), true
    case "MultiSokoban9":
        return default_model_config_multisokoban9(), true
    case "NestedGrowth":
        return default_model_config_nestedgrowth(), true
    case "NoDeadEnds":
        return default_model_config_nodeadends(), true
    case "Noise":
        return default_model_config_noise(), true
    case "NystromDungeon":
        return default_model_config_nystromdungeon(), true
    case "OddScale":
        return default_model_config_oddscale(), true
    case "OddScale3D":
        return default_model_config_oddscale3d(), true
    case "OpenCave":
        return default_model_config_opencave(), true
    case "OpenCave3D":
        return default_model_config_opencave3d(), true
    case "OrganicMechanic":
        return default_model_config_organicmechanic(), true
    case "OrientedEscher":
        return default_model_config_orientedescher(), true
    case "PaintCompetition":
        return default_model_config_paintcompetition(), true
    case "ParallelGrowth":
        return default_model_config_parallelgrowth(), true
    case "ParallelMazeGrowth":
        return default_model_config_parallelmazegrowth(), true
    case "ParallelWalk":
        return default_model_config_parallelwalk(), true
    case "Partitioning":
        return default_model_config_partitioning(), true
    case "Percolation":
        return default_model_config_percolation(), true
    case "PeriodicEscher":
        return default_model_config_periodicescher(), true
    case "PillarsOfEternity":
        return default_model_config_pillarsofeternity(), true
    case "Push":
        return default_model_config_push(), true
    case "PutColoredLs":
        return default_model_config_putcoloredls(), true
    case "PutLs":
        return default_model_config_putls(), true
    case "RainbowGrowth":
        return default_model_config_rainbowgrowth(), true
    case "RandomWalk":
        return default_model_config_randomwalk(), true
    case "Rectangle":
        return default_model_config_rectangle(), true
    case "RegularPath":
        return default_model_config_regularpath(), true
    case "RegularSAW":
        return default_model_config_regularsaw(), true
    case "RegularSAWRestart":
        return default_model_config_regularsawrestart(), true
    case "River":
        return default_model_config_river(), true
    case "SAWRestart":
        return default_model_config_sawrestart(), true
    case "SeaVilla":
        return default_model_config_seavilla(), true
    case "SelectLargeCaves":
        return default_model_config_selectlargecaves(), true
    case "SelectLongKnots":
        return default_model_config_selectlongknots(), true
    case "SelfAvoidingWalk":
        return default_model_config_selfavoidingwalk(), true
    case "SequentialSnake":
        return default_model_config_sequentialsnake(), true
    case "SequentialSokoban":
        return default_model_config_sequentialsokoban(), true
    case "Sewers":
        return default_model_config_sewers(), true
    case "SmartSAW":
        return default_model_config_smartsaw(), true
    case "SmarterDigger":
        return default_model_config_smarterdigger(), true
    case "SmoothTrail":
        return default_model_config_smoothtrail(), true
    case "Snake":
        return default_model_config_snake(), true
    case "SnellLaw":
        return default_model_config_snelllaw(), true
    case "SoftPath":
        return default_model_config_softpath(), true
    case "SokobanLevel1":
        return default_model_config_sokobanlevel1(), true
    case "SokobanLevel2":
        return default_model_config_sokobanlevel2(), true
    case "StableCrawlers":
        return default_model_config_stablecrawlers(), true
    case "StairsPath":
        return default_model_config_stairspath(), true
    case "StochasticVoronoi":
        return default_model_config_stochasticvoronoi(), true
    case "StormySnellLaw":
        return default_model_config_stormysnelllaw(), true
    case "StrangeDungeon":
        return default_model_config_strangedungeon(), true
    case "StrangeGrowth":
        return default_model_config_strangegrowth(), true
    case "StrangeNoise":
        return default_model_config_strangenoise(), true
    case "SubmergedKnots":
        return default_model_config_submergedknots(), true
    case "Surface":
        return default_model_config_surface(), true
    case "Tetris":
        return default_model_config_tetris(), true
    case "Texture":
        return default_model_config_texture(), true
    case "TileDungeon":
        return default_model_config_tiledungeon(), true
    case "TilePath":
        return default_model_config_tilepath(), true
    case "Trail":
        return default_model_config_trail(), true
    case "Voronoi":
        return default_model_config_voronoi(), true
    case "WaveBrickWall":
        return default_model_config_wavebrickwall(), true
    case "WaveDungeon":
        return default_model_config_wavedungeon(), true
    case "WaveFlowers":
        return default_model_config_waveflowers(), true
    case "Wilson":
        return default_model_config_wilson(), true
    case "WolfBasedApproach":
        return default_model_config_wolfbasedapproach(), true
    }
    return {}, false
}

model_palette_symbol :: proc(name: string, value: int) -> (u8, bool) {
    switch name {
    case "Apartemazements":
        return model_palette_symbol_apartemazements(value)
    case "Backtracker":
        return model_palette_symbol_backtracker(value)
    case "BacktrackerCycle":
        return model_palette_symbol_backtrackercycle(value)
    case "Basic":
        return model_palette_symbol_basic(value)
    case "BasicBrickWall":
        return model_palette_symbol_basicbrickwall(value)
    case "BasicDijkstraDungeon":
        return model_palette_symbol_basicdijkstradungeon(value)
    case "BasicDijkstraFill":
        return model_palette_symbol_basicdijkstrafill(value)
    case "BasicDungeonGrowth":
        return model_palette_symbol_basicdungeongrowth(value)
    case "BasicKeys":
        return model_palette_symbol_basickeys(value)
    case "BasicPartitioning":
        return model_palette_symbol_basicpartitioning(value)
    case "BasicSkyline":
        return model_palette_symbol_basicskyline(value)
    case "BasicSnake":
        return model_palette_symbol_basicsnake(value)
    case "BernoulliPercolation":
        return model_palette_symbol_bernoullipercolation(value)
    case "BiasedGrowth":
        return model_palette_symbol_biasedgrowth(value)
    case "BiasedGrowthContraction":
        return model_palette_symbol_biasedgrowthcontraction(value)
    case "BiasedMazeGrowth":
        return model_palette_symbol_biasedmazegrowth(value)
    case "BiasedVoronoi":
        return model_palette_symbol_biasedvoronoi(value)
    case "BishopParity":
        return model_palette_symbol_bishopparity(value)
    case "BlueNoise":
        return model_palette_symbol_bluenoise(value)
    case "CarmaTower":
        return model_palette_symbol_carmatower(value)
    case "Cave":
        return model_palette_symbol_cave(value)
    case "CaveContour":
        return model_palette_symbol_cavecontour(value)
    case "CentralCrawlers":
        return model_palette_symbol_centralcrawlers(value)
    case "CentralSAW":
        return model_palette_symbol_centralsaw(value)
    case "ChainDungeon":
        return model_palette_symbol_chaindungeon(value)
    case "ChainDungeonMaze":
        return model_palette_symbol_chaindungeonmaze(value)
    case "ChainMaze":
        return model_palette_symbol_chainmaze(value)
    case "Chase":
        return model_palette_symbol_chase(value)
    case "Circuit":
        return model_palette_symbol_circuit(value)
    case "ClosedSurface":
        return model_palette_symbol_closedsurface(value)
    case "ColoredKnots":
        return model_palette_symbol_coloredknots(value)
    case "CompleteSAW":
        return model_palette_symbol_completesaw(value)
    case "CompleteSAWSmart":
        return model_palette_symbol_completesawsmart(value)
    case "ConnectedCaves":
        return model_palette_symbol_connectedcaves(value)
    case "ConstrainedCaves":
        return model_palette_symbol_constrainedcaves(value)
    case "Counting":
        return model_palette_symbol_counting(value)
    case "Coupling":
        return model_palette_symbol_coupling(value)
    case "Crawlers":
        return model_palette_symbol_crawlers(value)
    case "CrawlersChase":
        return model_palette_symbol_crawlerschase(value)
    case "CrossCountry":
        return model_palette_symbol_crosscountry(value)
    case "Cycles":
        return model_palette_symbol_cycles(value)
    case "DenseSAW":
        return model_palette_symbol_densesaw(value)
    case "DiagonalPath":
        return model_palette_symbol_diagonalpath(value)
    case "Digger":
        return model_palette_symbol_digger(value)
    case "DijkstraDungeon":
        return model_palette_symbol_dijkstradungeon(value)
    case "DualRetraction":
        return model_palette_symbol_dualretraction(value)
    case "DualRetraction3D":
        return model_palette_symbol_dualretraction3d(value)
    case "DungeonGrowth":
        return model_palette_symbol_dungeongrowth(value)
    case "DwarfPath":
        return model_palette_symbol_dwarfpath(value)
    case "Dwarves":
        return model_palette_symbol_dwarves(value)
    case "Escher":
        return model_palette_symbol_escher(value)
    case "EscherSurface":
        return model_palette_symbol_eschersurface(value)
    case "EuclideanPath":
        return model_palette_symbol_euclideanpath(value)
    case "FindLongCycle":
        return model_palette_symbol_findlongcycle(value)
    case "FireNoise":
        return model_palette_symbol_firenoise(value)
    case "Flowers":
        return model_palette_symbol_flowers(value)
    case "Forest":
        return model_palette_symbol_forest(value)
    case "ForestFire":
        return model_palette_symbol_forestfire(value)
    case "ForestFireCA":
        return model_palette_symbol_forestfireca(value)
    case "GameOfLife":
        return model_palette_symbol_gameoflife(value)
    case "GoTo":
        return model_palette_symbol_goto(value)
    case "GoToGradient":
        return model_palette_symbol_gotogradient(value)
    case "GrowTo":
        return model_palette_symbol_growto(value)
    case "Growth":
        return model_palette_symbol_growth(value)
    case "GrowthCompetition":
        return model_palette_symbol_growthcompetition(value)
    case "GrowthContraction":
        return model_palette_symbol_growthcontraction(value)
    case "GrowthWalk":
        return model_palette_symbol_growthwalk(value)
    case "HamiltonianPath":
        return model_palette_symbol_hamiltonianpath(value)
    case "HamiltonianPaths":
        return model_palette_symbol_hamiltonianpaths(value)
    case "Hills":
        return model_palette_symbol_hills(value)
    case "IrregularMazeGrowth":
        return model_palette_symbol_irregularmazegrowth(value)
    case "IrregularSAW":
        return model_palette_symbol_irregularsaw(value)
    case "Island":
        return model_palette_symbol_island(value)
    case "Keys":
        return model_palette_symbol_keys(value)
    case "KnightPatrol":
        return model_palette_symbol_knightpatrol(value)
    case "Knots2D":
        return model_palette_symbol_knots2d(value)
    case "Knots3D":
        return model_palette_symbol_knots3d(value)
    case "Laplace":
        return model_palette_symbol_laplace(value)
    case "Lightning":
        return model_palette_symbol_lightning(value)
    case "LoopErasedWalk":
        return model_palette_symbol_looperasedwalk(value)
    case "LoopGrowth":
        return model_palette_symbol_loopgrowth(value)
    case "LostCity":
        return model_palette_symbol_lostcity(value)
    case "MarchingSquares":
        return model_palette_symbol_marchingsquares(value)
    case "MazeBacktracker":
        return model_palette_symbol_mazebacktracker(value)
    case "MazeGrowth":
        return model_palette_symbol_mazegrowth(value)
    case "MazeMap":
        return model_palette_symbol_mazemap(value)
    case "MazeTrail":
        return model_palette_symbol_mazetrail(value)
    case "ModernHouse":
        return model_palette_symbol_modernhouse(value)
    case "MultiHeadedDungeon":
        return model_palette_symbol_multiheadeddungeon(value)
    case "MultiHeadedWalk":
        return model_palette_symbol_multiheadedwalk(value)
    case "MultiHeadedWalkDungeon":
        return model_palette_symbol_multiheadedwalkdungeon(value)
    case "MultiSokoban8":
        return model_palette_symbol_multisokoban8(value)
    case "MultiSokoban9":
        return model_palette_symbol_multisokoban9(value)
    case "NestedGrowth":
        return model_palette_symbol_nestedgrowth(value)
    case "NoDeadEnds":
        return model_palette_symbol_nodeadends(value)
    case "Noise":
        return model_palette_symbol_noise(value)
    case "NystromDungeon":
        return model_palette_symbol_nystromdungeon(value)
    case "OddScale":
        return model_palette_symbol_oddscale(value)
    case "OddScale3D":
        return model_palette_symbol_oddscale3d(value)
    case "OpenCave":
        return model_palette_symbol_opencave(value)
    case "OpenCave3D":
        return model_palette_symbol_opencave3d(value)
    case "OrganicMechanic":
        return model_palette_symbol_organicmechanic(value)
    case "OrientedEscher":
        return model_palette_symbol_orientedescher(value)
    case "PaintCompetition":
        return model_palette_symbol_paintcompetition(value)
    case "ParallelGrowth":
        return model_palette_symbol_parallelgrowth(value)
    case "ParallelMazeGrowth":
        return model_palette_symbol_parallelmazegrowth(value)
    case "ParallelWalk":
        return model_palette_symbol_parallelwalk(value)
    case "Partitioning":
        return model_palette_symbol_partitioning(value)
    case "Percolation":
        return model_palette_symbol_percolation(value)
    case "PeriodicEscher":
        return model_palette_symbol_periodicescher(value)
    case "PillarsOfEternity":
        return model_palette_symbol_pillarsofeternity(value)
    case "Push":
        return model_palette_symbol_push(value)
    case "PutColoredLs":
        return model_palette_symbol_putcoloredls(value)
    case "PutLs":
        return model_palette_symbol_putls(value)
    case "RainbowGrowth":
        return model_palette_symbol_rainbowgrowth(value)
    case "RandomWalk":
        return model_palette_symbol_randomwalk(value)
    case "Rectangle":
        return model_palette_symbol_rectangle(value)
    case "RegularPath":
        return model_palette_symbol_regularpath(value)
    case "RegularSAW":
        return model_palette_symbol_regularsaw(value)
    case "RegularSAWRestart":
        return model_palette_symbol_regularsawrestart(value)
    case "River":
        return model_palette_symbol_river(value)
    case "SAWRestart":
        return model_palette_symbol_sawrestart(value)
    case "SeaVilla":
        return model_palette_symbol_seavilla(value)
    case "SelectLargeCaves":
        return model_palette_symbol_selectlargecaves(value)
    case "SelectLongKnots":
        return model_palette_symbol_selectlongknots(value)
    case "SelfAvoidingWalk":
        return model_palette_symbol_selfavoidingwalk(value)
    case "SequentialSnake":
        return model_palette_symbol_sequentialsnake(value)
    case "SequentialSokoban":
        return model_palette_symbol_sequentialsokoban(value)
    case "Sewers":
        return model_palette_symbol_sewers(value)
    case "SmartSAW":
        return model_palette_symbol_smartsaw(value)
    case "SmarterDigger":
        return model_palette_symbol_smarterdigger(value)
    case "SmoothTrail":
        return model_palette_symbol_smoothtrail(value)
    case "Snake":
        return model_palette_symbol_snake(value)
    case "SnellLaw":
        return model_palette_symbol_snelllaw(value)
    case "SoftPath":
        return model_palette_symbol_softpath(value)
    case "SokobanLevel1":
        return model_palette_symbol_sokobanlevel1(value)
    case "SokobanLevel2":
        return model_palette_symbol_sokobanlevel2(value)
    case "StableCrawlers":
        return model_palette_symbol_stablecrawlers(value)
    case "StairsPath":
        return model_palette_symbol_stairspath(value)
    case "StochasticVoronoi":
        return model_palette_symbol_stochasticvoronoi(value)
    case "StormySnellLaw":
        return model_palette_symbol_stormysnelllaw(value)
    case "StrangeDungeon":
        return model_palette_symbol_strangedungeon(value)
    case "StrangeGrowth":
        return model_palette_symbol_strangegrowth(value)
    case "StrangeNoise":
        return model_palette_symbol_strangenoise(value)
    case "SubmergedKnots":
        return model_palette_symbol_submergedknots(value)
    case "Surface":
        return model_palette_symbol_surface(value)
    case "Tetris":
        return model_palette_symbol_tetris(value)
    case "Texture":
        return model_palette_symbol_texture(value)
    case "TileDungeon":
        return model_palette_symbol_tiledungeon(value)
    case "TilePath":
        return model_palette_symbol_tilepath(value)
    case "Trail":
        return model_palette_symbol_trail(value)
    case "Voronoi":
        return model_palette_symbol_voronoi(value)
    case "WaveBrickWall":
        return model_palette_symbol_wavebrickwall(value)
    case "WaveDungeon":
        return model_palette_symbol_wavedungeon(value)
    case "WaveFlowers":
        return model_palette_symbol_waveflowers(value)
    case "Wilson":
        return model_palette_symbol_wilson(value)
    case "WolfBasedApproach":
        return model_palette_symbol_wolfbasedapproach(value)
    }
    return 0, false
}

model_override_color :: proc(name: string, value: int) -> (i32, bool) {
    switch name {
    case "Apartemazements":
        return model_override_color_apartemazements(value)
    case "Backtracker":
        return model_override_color_backtracker(value)
    case "BacktrackerCycle":
        return model_override_color_backtrackercycle(value)
    case "Basic":
        return model_override_color_basic(value)
    case "BasicBrickWall":
        return model_override_color_basicbrickwall(value)
    case "BasicDijkstraDungeon":
        return model_override_color_basicdijkstradungeon(value)
    case "BasicDijkstraFill":
        return model_override_color_basicdijkstrafill(value)
    case "BasicDungeonGrowth":
        return model_override_color_basicdungeongrowth(value)
    case "BasicKeys":
        return model_override_color_basickeys(value)
    case "BasicPartitioning":
        return model_override_color_basicpartitioning(value)
    case "BasicSkyline":
        return model_override_color_basicskyline(value)
    case "BasicSnake":
        return model_override_color_basicsnake(value)
    case "BernoulliPercolation":
        return model_override_color_bernoullipercolation(value)
    case "BiasedGrowth":
        return model_override_color_biasedgrowth(value)
    case "BiasedGrowthContraction":
        return model_override_color_biasedgrowthcontraction(value)
    case "BiasedMazeGrowth":
        return model_override_color_biasedmazegrowth(value)
    case "BiasedVoronoi":
        return model_override_color_biasedvoronoi(value)
    case "BishopParity":
        return model_override_color_bishopparity(value)
    case "BlueNoise":
        return model_override_color_bluenoise(value)
    case "CarmaTower":
        return model_override_color_carmatower(value)
    case "Cave":
        return model_override_color_cave(value)
    case "CaveContour":
        return model_override_color_cavecontour(value)
    case "CentralCrawlers":
        return model_override_color_centralcrawlers(value)
    case "CentralSAW":
        return model_override_color_centralsaw(value)
    case "ChainDungeon":
        return model_override_color_chaindungeon(value)
    case "ChainDungeonMaze":
        return model_override_color_chaindungeonmaze(value)
    case "ChainMaze":
        return model_override_color_chainmaze(value)
    case "Chase":
        return model_override_color_chase(value)
    case "Circuit":
        return model_override_color_circuit(value)
    case "ClosedSurface":
        return model_override_color_closedsurface(value)
    case "ColoredKnots":
        return model_override_color_coloredknots(value)
    case "CompleteSAW":
        return model_override_color_completesaw(value)
    case "CompleteSAWSmart":
        return model_override_color_completesawsmart(value)
    case "ConnectedCaves":
        return model_override_color_connectedcaves(value)
    case "ConstrainedCaves":
        return model_override_color_constrainedcaves(value)
    case "Counting":
        return model_override_color_counting(value)
    case "Coupling":
        return model_override_color_coupling(value)
    case "Crawlers":
        return model_override_color_crawlers(value)
    case "CrawlersChase":
        return model_override_color_crawlerschase(value)
    case "CrossCountry":
        return model_override_color_crosscountry(value)
    case "Cycles":
        return model_override_color_cycles(value)
    case "DenseSAW":
        return model_override_color_densesaw(value)
    case "DiagonalPath":
        return model_override_color_diagonalpath(value)
    case "Digger":
        return model_override_color_digger(value)
    case "DijkstraDungeon":
        return model_override_color_dijkstradungeon(value)
    case "DualRetraction":
        return model_override_color_dualretraction(value)
    case "DualRetraction3D":
        return model_override_color_dualretraction3d(value)
    case "DungeonGrowth":
        return model_override_color_dungeongrowth(value)
    case "DwarfPath":
        return model_override_color_dwarfpath(value)
    case "Dwarves":
        return model_override_color_dwarves(value)
    case "Escher":
        return model_override_color_escher(value)
    case "EscherSurface":
        return model_override_color_eschersurface(value)
    case "EuclideanPath":
        return model_override_color_euclideanpath(value)
    case "FindLongCycle":
        return model_override_color_findlongcycle(value)
    case "FireNoise":
        return model_override_color_firenoise(value)
    case "Flowers":
        return model_override_color_flowers(value)
    case "Forest":
        return model_override_color_forest(value)
    case "ForestFire":
        return model_override_color_forestfire(value)
    case "ForestFireCA":
        return model_override_color_forestfireca(value)
    case "GameOfLife":
        return model_override_color_gameoflife(value)
    case "GoTo":
        return model_override_color_goto(value)
    case "GoToGradient":
        return model_override_color_gotogradient(value)
    case "GrowTo":
        return model_override_color_growto(value)
    case "Growth":
        return model_override_color_growth(value)
    case "GrowthCompetition":
        return model_override_color_growthcompetition(value)
    case "GrowthContraction":
        return model_override_color_growthcontraction(value)
    case "GrowthWalk":
        return model_override_color_growthwalk(value)
    case "HamiltonianPath":
        return model_override_color_hamiltonianpath(value)
    case "HamiltonianPaths":
        return model_override_color_hamiltonianpaths(value)
    case "Hills":
        return model_override_color_hills(value)
    case "IrregularMazeGrowth":
        return model_override_color_irregularmazegrowth(value)
    case "IrregularSAW":
        return model_override_color_irregularsaw(value)
    case "Island":
        return model_override_color_island(value)
    case "Keys":
        return model_override_color_keys(value)
    case "KnightPatrol":
        return model_override_color_knightpatrol(value)
    case "Knots2D":
        return model_override_color_knots2d(value)
    case "Knots3D":
        return model_override_color_knots3d(value)
    case "Laplace":
        return model_override_color_laplace(value)
    case "Lightning":
        return model_override_color_lightning(value)
    case "LoopErasedWalk":
        return model_override_color_looperasedwalk(value)
    case "LoopGrowth":
        return model_override_color_loopgrowth(value)
    case "LostCity":
        return model_override_color_lostcity(value)
    case "MarchingSquares":
        return model_override_color_marchingsquares(value)
    case "MazeBacktracker":
        return model_override_color_mazebacktracker(value)
    case "MazeGrowth":
        return model_override_color_mazegrowth(value)
    case "MazeMap":
        return model_override_color_mazemap(value)
    case "MazeTrail":
        return model_override_color_mazetrail(value)
    case "ModernHouse":
        return model_override_color_modernhouse(value)
    case "MultiHeadedDungeon":
        return model_override_color_multiheadeddungeon(value)
    case "MultiHeadedWalk":
        return model_override_color_multiheadedwalk(value)
    case "MultiHeadedWalkDungeon":
        return model_override_color_multiheadedwalkdungeon(value)
    case "MultiSokoban8":
        return model_override_color_multisokoban8(value)
    case "MultiSokoban9":
        return model_override_color_multisokoban9(value)
    case "NestedGrowth":
        return model_override_color_nestedgrowth(value)
    case "NoDeadEnds":
        return model_override_color_nodeadends(value)
    case "Noise":
        return model_override_color_noise(value)
    case "NystromDungeon":
        return model_override_color_nystromdungeon(value)
    case "OddScale":
        return model_override_color_oddscale(value)
    case "OddScale3D":
        return model_override_color_oddscale3d(value)
    case "OpenCave":
        return model_override_color_opencave(value)
    case "OpenCave3D":
        return model_override_color_opencave3d(value)
    case "OrganicMechanic":
        return model_override_color_organicmechanic(value)
    case "OrientedEscher":
        return model_override_color_orientedescher(value)
    case "PaintCompetition":
        return model_override_color_paintcompetition(value)
    case "ParallelGrowth":
        return model_override_color_parallelgrowth(value)
    case "ParallelMazeGrowth":
        return model_override_color_parallelmazegrowth(value)
    case "ParallelWalk":
        return model_override_color_parallelwalk(value)
    case "Partitioning":
        return model_override_color_partitioning(value)
    case "Percolation":
        return model_override_color_percolation(value)
    case "PeriodicEscher":
        return model_override_color_periodicescher(value)
    case "PillarsOfEternity":
        return model_override_color_pillarsofeternity(value)
    case "Push":
        return model_override_color_push(value)
    case "PutColoredLs":
        return model_override_color_putcoloredls(value)
    case "PutLs":
        return model_override_color_putls(value)
    case "RainbowGrowth":
        return model_override_color_rainbowgrowth(value)
    case "RandomWalk":
        return model_override_color_randomwalk(value)
    case "Rectangle":
        return model_override_color_rectangle(value)
    case "RegularPath":
        return model_override_color_regularpath(value)
    case "RegularSAW":
        return model_override_color_regularsaw(value)
    case "RegularSAWRestart":
        return model_override_color_regularsawrestart(value)
    case "River":
        return model_override_color_river(value)
    case "SAWRestart":
        return model_override_color_sawrestart(value)
    case "SeaVilla":
        return model_override_color_seavilla(value)
    case "SelectLargeCaves":
        return model_override_color_selectlargecaves(value)
    case "SelectLongKnots":
        return model_override_color_selectlongknots(value)
    case "SelfAvoidingWalk":
        return model_override_color_selfavoidingwalk(value)
    case "SequentialSnake":
        return model_override_color_sequentialsnake(value)
    case "SequentialSokoban":
        return model_override_color_sequentialsokoban(value)
    case "Sewers":
        return model_override_color_sewers(value)
    case "SmartSAW":
        return model_override_color_smartsaw(value)
    case "SmarterDigger":
        return model_override_color_smarterdigger(value)
    case "SmoothTrail":
        return model_override_color_smoothtrail(value)
    case "Snake":
        return model_override_color_snake(value)
    case "SnellLaw":
        return model_override_color_snelllaw(value)
    case "SoftPath":
        return model_override_color_softpath(value)
    case "SokobanLevel1":
        return model_override_color_sokobanlevel1(value)
    case "SokobanLevel2":
        return model_override_color_sokobanlevel2(value)
    case "StableCrawlers":
        return model_override_color_stablecrawlers(value)
    case "StairsPath":
        return model_override_color_stairspath(value)
    case "StochasticVoronoi":
        return model_override_color_stochasticvoronoi(value)
    case "StormySnellLaw":
        return model_override_color_stormysnelllaw(value)
    case "StrangeDungeon":
        return model_override_color_strangedungeon(value)
    case "StrangeGrowth":
        return model_override_color_strangegrowth(value)
    case "StrangeNoise":
        return model_override_color_strangenoise(value)
    case "SubmergedKnots":
        return model_override_color_submergedknots(value)
    case "Surface":
        return model_override_color_surface(value)
    case "Tetris":
        return model_override_color_tetris(value)
    case "Texture":
        return model_override_color_texture(value)
    case "TileDungeon":
        return model_override_color_tiledungeon(value)
    case "TilePath":
        return model_override_color_tilepath(value)
    case "Trail":
        return model_override_color_trail(value)
    case "Voronoi":
        return model_override_color_voronoi(value)
    case "WaveBrickWall":
        return model_override_color_wavebrickwall(value)
    case "WaveDungeon":
        return model_override_color_wavedungeon(value)
    case "WaveFlowers":
        return model_override_color_waveflowers(value)
    case "Wilson":
        return model_override_color_wilson(value)
    case "WolfBasedApproach":
        return model_override_color_wolfbasedapproach(value)
    }
    return 0, false
}
