// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_forestfire :: proc() -> mk.Proc_Node {
    return mk.prl(
        mk.kattr(.values, mk.values_count(3)),
        mk.rule(mk.in_exact_layer([]int{2, 1}), mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
        mk.rule(
            mk.in_exact_layer([]int{2, mk.IN_ANY}, []int{mk.IN_ANY, 1}),
            mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 2}),
        ),
        mk.rule(mk.in_exact_layer([]int{0}), mk.out_exact_layer([]int{1}), mk.kattr(.p, 0.01)),
        mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{0})),
        mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{2}), mk.kattr(.p, 0.0001)),
    )
}
