// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_crawlers :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1, 2})),
            mk.kattr(.steps, 12),
        ),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{1, 2, 0}), mk.out_exact_layer([]int{0, 1, 2})),
            mk.rule(
                mk.in_exact_layer([]int{1, 2}, []int{mk.IN_ANY, 0}),
                mk.out_exact_layer([]int{0, 1}, []int{mk.OUT_KEEP, 2}),
            ),
        ),
    )
}
