// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_keys :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(10)),
        mk.kattr(.origin, true),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0, mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2, 2, 1})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{3})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.steps, 1),
            mk.rule(mk.in_exact_layer([]int{1}), mk.out_exact_layer([]int{4})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(4)),
                mk.kattr(.from_, mk.one_of(mk.sym(3))),
                mk.kattr(.on, mk.one_of(mk.sym(1), mk.sym(2), mk.sym(4))),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{4, 2, 2, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 5, 7, 8})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.temperature, 2.0),
            mk.rule(mk.in_exact_layer([]int{8, 2, 2, 1}), mk.out_exact_layer([]int{6, 5, 7, 8})),
            mk.rule(mk.in_exact_layer([]int{8, 2, 2, 3}), mk.out_exact_layer([]int{6, 5, 7, 3})),
            mk.field_node(
                mk.kattr(.for_, mk.sym(8)),
                mk.kattr(.to, mk.one_of(mk.sym(3))),
                mk.kattr(.on, mk.one_of(mk.sym(1), mk.sym(2), mk.sym(3), mk.sym(8))),
            ),
        ),
        mk.markov_node(
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{8, 2, 2, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{6, 5, 7, 8})),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{5, 0, 0, mk.IN_ANY}, []int{6, 2, 2, 1})),
                mk.kattr(
                    .out,
                    mk.out_exact_layer([]int{9, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 5, 7, 8}),
                ),
            ),
        ),
        mk.prl(
            mk.rule(mk.in_exact_layer([]int{7}), mk.out_exact_layer([]int{6})),
            mk.rule(mk.in_exact_layer([]int{5}), mk.out_exact_layer([]int{6})),
            mk.rule(mk.in_exact_layer([]int{2}), mk.out_exact_layer([]int{0})),
        ),
    )
}
