// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_regularpath :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(6)),
        mk.kattr(.origin, true),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, mk.IN_ANY, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 1})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{3})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{5})),
            mk.kattr(.steps, 10),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
        mk.markov_node(
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{3, 0, 0})),
                mk.kattr(.out, mk.out_exact_layer([]int{2, 2, 3})),
                mk.observe_node(
                    mk.kattr(.value, mk.sym(4)),
                    mk.kattr(.from_, mk.sym(0)),
                    mk.kattr(.to, mk.one_of(mk.sym(3))),
                ),
                mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(2)))),
                mk.observe_node(mk.kattr(.value, mk.sym(3)), mk.kattr(.to, mk.one_of(mk.sym(2)))),
            ),
            mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{5})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
        ),
    )
}
