// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_looperasedwalk :: proc() -> mk.Proc_Node {
    return mk.one(
        mk.kattr(.values, mk.values_count(6)),
        mk.kattr(.origin, true),
        mk.rule(mk.in_exact_layer([]int{1, 0, 0}), mk.out_exact_layer([]int{2, 2, 1})),
        mk.rule(mk.in_exact_layer([]int{1, 0, 2}), mk.out_exact_layer([]int{3, 2, 4})),
        mk.rule(mk.in_exact_layer([]int{4, 2, 3}), mk.out_exact_layer([]int{4, 0, 5})),
        mk.rule(mk.in_exact_layer([]int{5, 2, 2}), mk.out_exact_layer([]int{0, 0, 5})),
        mk.rule(mk.in_exact_layer([]int{5, 2, 4}), mk.out_exact_layer([]int{0, 0, 1})),
    )
}
