// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_multiheadeddungeon :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.kattr(.origin, true),
        mk.markov_node(
            mk.sequence(
                mk.one(
                    mk.kattr(.in_, mk.in_exact_layer([]int{1, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 0})),
                    mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2, 2, 2, 3})),
                    mk.kattr(.steps, 3),
                ),
                mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
                mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 4, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 1, mk.OUT_KEEP}),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0, 0, 0, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{4, 2, 2, 2, 4})),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0, 0, 0}, []int{0, 4, 2, 2, 2}, []int{0, 0, 0, 0, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 0, 0, 0, 0},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{4, 2, 2, 2, 4},
                    []int{2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 2},
                    []int{2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 2},
                    []int{2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 2},
                    []int{4, 0, 0, 0, 4},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 2, 2, 2, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 4, 2, 2, 2, 4, mk.IN_ANY},
                    []int{mk.IN_ANY, 2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 2, mk.IN_ANY},
                    []int{mk.IN_ANY, 2, mk.IN_ANY, 0, mk.IN_ANY, 2, mk.IN_ANY},
                    []int{mk.IN_ANY, 2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, 2, mk.IN_ANY},
                    []int{mk.IN_ANY, 4, 2, 2, 2, 4, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{2, 2, 2, 2, 2, 2, 2},
                    []int{2, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 2},
                    []int{2, mk.OUT_KEEP, 2, 2, 2, mk.OUT_KEEP, 2},
                    []int{2, mk.OUT_KEEP, 2, 3, 2, mk.OUT_KEEP, 2},
                    []int{2, mk.OUT_KEEP, 2, 2, 2, mk.OUT_KEEP, 2},
                    []int{2, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 2},
                    []int{2, 2, 2, 2, 2, 2, 2},
                ),
            ),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{4})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{3, 2, 2, 2, 3},
                    []int{2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2},
                    []int{3, 2, 2, 2, 3},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0},
                ),
            ),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
    )
}
