// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_circuit :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(11)),
        mk.kattr(.origin, true),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 2, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 2, 2})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, mk.OUT_KEEP, 1})),
        ),
        mk.one(mk.kattr(.file, "Chip"), mk.kattr(.legend, "*12536"), mk.kattr(.steps, 2)),
        mk.markov_node(
            mk.all(
                mk.rule(mk.in_exact_layer([]int{2, 4}), mk.out_exact_layer([]int{1, 4})),
                mk.rule(
                    mk.in_exact_layer([]int{2, mk.IN_ANY}, []int{mk.IN_ANY, 4}),
                    mk.out_exact_layer([]int{1, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 4}),
                ),
            ),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(5))),
                mk.kattr(.to, mk.one_of(mk.sym(10))),
                mk.kattr(.on, mk.one_of(mk.sym(2))),
                mk.kattr(.color, mk.sym(4)),
                mk.kattr(.inertia, true),
            ),
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{5})), mk.kattr(.out, mk.out_exact_layer([]int{10}))),
            mk.one(mk.kattr(.file, "Chip"), mk.kattr(.legend, "*12536")),
        ),
        mk.prl(mk.kattr(.in_, mk.in_exact_layer([]int{0})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{2, 10}), mk.out_exact_layer([]int{2, 2})),
            mk.rule(
                mk.in_exact_layer([]int{2, 2, 2}, []int{1, 1, 2}, []int{2, 2, 2}),
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{2, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.markov_node(
            mk.one(
                mk.rule(mk.in_exact_layer([]int{6, 10, 5, 10}), mk.out_exact_layer([]int{6, 5, 4, 4})),
                mk.rule(mk.in_exact_layer([]int{10, 5, 4}), mk.out_exact_layer([]int{4, 10, 5})),
                mk.rule(
                    mk.in_exact_layer([]int{10, 5}, []int{mk.IN_ANY, 4}),
                    mk.out_exact_layer([]int{4, 10}, []int{mk.OUT_KEEP, 5}),
                ),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{10, 4})), mk.kattr(.out, mk.out_exact_layer([]int{10, 5}))),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{6, 4})), mk.kattr(.out, mk.out_exact_layer([]int{6, 9}))),
        mk.all(
            mk.rule(mk.in_exact_layer([]int{6, 3}), mk.out_exact_layer([]int{3, 6})),
            mk.rule(mk.in_exact_layer([]int{6, 9, 4, 4}), mk.out_exact_layer([]int{3, 9, 7, 8})),
            mk.rule(mk.in_exact_layer([]int{7, 8, 4}), mk.out_exact_layer([]int{4, 7, 8})),
            mk.rule(
                mk.in_exact_layer([]int{7, 8}, []int{mk.IN_ANY, 4}),
                mk.out_exact_layer([]int{4, 7}, []int{mk.OUT_KEEP, 8}),
            ),
            mk.rule(mk.in_exact_layer([]int{7, 8, 5, 3}), mk.out_exact_layer([]int{4, 4, 5, 6})),
        ),
    )
}
