// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

default_model_config_island :: proc() -> Model_Config {
    return Model_Config{size = {800, 800, 1}, steps = -1, pixel_size = 1, iso = false}
}

model_palette_symbol_island :: proc(value: int) -> (u8, bool) {
    values := "UWBRGEYINSOTus"
    if value >= 0 && value < len(values) {
        return values[value], true
    }
    return 0, false
}

model_override_color_island :: proc(value: int) -> (i32, bool) {
    switch value {
    case 7:
        return transmute(i32)u32(0xff000000 | 0xabcbe8), true
    case 0:
        return transmute(i32)u32(0xff000000 | 0xcee6f9), true
    case 11:
        return transmute(i32)u32(0xff000000 | 0x2b8aa9), true
    case 6:
        return transmute(i32)u32(0xff000000 | 0xf1ebc2), true
    case 4:
        return transmute(i32)u32(0xff000000 | 0xa8d1a5), true
    case 5:
        return transmute(i32)u32(0xff000000 | 0x93c08d), true
    case 9:
        return transmute(i32)u32(0xff000000 | 0xd0d8ac), true
    case 13:
        return transmute(i32)u32(0xff000000 | 0xe9e0b2), true
    }
    return 0, false
}
