// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_loopgrowth :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.kattr(.origin, true),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 1, 0}, []int{0, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 1, 2}, []int{1, 0, 1}, []int{2, 1, 2})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}, []int{2, 1, 2})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 1, 2}, []int{1, 0, 1}, []int{2, 0, 2})),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{2}))),
    )
}
