// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_tetris :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(7)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_X)),
        mk.union_node(mk.kattr(.symbol, "?"), mk.kattr(.values, mk.one_of(mk.sym(0), mk.sym(1), mk.sym(2)))),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{mk.IN_ANY}, []int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP}, []int{1})),
        ),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer([]int{mk.IN_ANY}, []int{mk.IN_ANY}, []int{mk.IN_ANY}, []int{mk.IN_ANY}, []int{1}),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP},
                    []int{mk.OUT_KEEP},
                    []int{mk.OUT_KEEP},
                    []int{mk.OUT_KEEP},
                    []int{3},
                ),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{3}, []int{mk.IN_ANY})),
            mk.kattr(.out, mk.out_exact_layer([]int{2}, []int{mk.OUT_KEEP})),
        ),
        mk.markov_node(
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1, 2})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 1})),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{5, 4})),
                mk.kattr(.out, mk.out_exact_layer([]int{5, 5})),
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_ALL)),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{4}, []int{3})),
                mk.kattr(.out, mk.out_exact_layer([]int{5}, []int{3})),
            ),
            mk.prl(
                mk.rule(mk.in_exact_layer([]int{4}, []int{2}), mk.out_exact_layer([]int{mk.OUT_KEEP}, []int{4})),
                mk.rule(mk.in_exact_layer([]int{4}, []int{1}), mk.out_exact_layer([]int{mk.OUT_KEEP}, []int{4})),
                mk.rule("?/R", mk.out_exact_layer([]int{mk.OUT_KEEP}, []int{2})),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{5})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
            mk.one(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_ALL)),
                mk.rule(
                    mk.in_exact_layer([]int{1, 1, 1}, []int{1, 1, 1}),
                    mk.out_exact_layer([]int{mk.OUT_KEEP, 4, mk.OUT_KEEP}, []int{4, 4, 4}),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{1, 1, 1}, []int{1, 1, 1}),
                    mk.out_exact_layer([]int{4, 4, mk.OUT_KEEP}, []int{mk.OUT_KEEP, 4, 4}),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{1, 1, 1}, []int{1, 1, 1}),
                    mk.out_exact_layer([]int{4, mk.OUT_KEEP, mk.OUT_KEEP}, []int{4, 4, 4}),
                ),
                mk.rule(
                    mk.in_exact_layer([]int{1, 1, 1}, []int{1, 1, 1}),
                    mk.out_exact_layer([]int{4, 4, mk.OUT_KEEP}, []int{4, 4, mk.OUT_KEEP}),
                ),
            ),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{3, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{6, mk.OUT_KEEP})),
        ),
        mk.all(
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_2D_ALL)),
            mk.rule(mk.in_exact_layer([]int{6, mk.IN_ANY}), mk.out_exact_layer([]int{6, 6})),
            mk.rule(mk.in_exact_layer([]int{6, 6}), mk.out_exact_layer([]int{2, 2})),
        ),
    )
}
