// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_wavedungeon :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(4)),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 2, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{2, 2, 2, 2}, []int{2, 2, 2, 2}, []int{2, 2, 2, 2})),
            mk.kattr(.out, mk.out_exact_layer([]int{1, 1, 1, 1}, []int{1, 1, 1, 1}, []int{1, 1, 1, 1})),
            mk.kattr(.steps, 5),
        ),
        mk.markov_node(
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{3, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 3})),
            ),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(3))),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(2))),
                mk.kattr(.color, mk.sym(1)),
                mk.kattr(.inertia, true),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{3}))),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        mk.wfc_node(
            mk.kattr(.sample, "Dungeon"),
            mk.kattr(.values, mk.values_count(3)),
            mk.kattr(.n, 3),
            mk.rule(mk.sym(0), mk.one_of(mk.sym(0))),
            mk.rule(mk.sym(1), mk.one_of(mk.sym(1))),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{1})),
                mk.kattr(.out, mk.out_exact_layer([]int{2})),
                mk.kattr(.steps, 1),
            ),
            mk.all(
                mk.kattr(.in_, mk.in_exact_layer([]int{2, 1})),
                mk.kattr(.out, mk.out_exact_layer([]int{mk.OUT_KEEP, 2})),
            ),
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1})), mk.kattr(.out, mk.out_exact_layer([]int{0}))),
        ),
    )
}
