// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_crosscountry :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(8)),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{0})),
            mk.kattr(.p, 0.435),
            mk.kattr(.steps, 1),
        ),
        mk.convolution_node(
            mk.kattr(.neighborhood, "Moore"),
            mk.rule(mk.sym(1), mk.sym(0), mk.kattr(.sum, "5..8"), mk.kattr(.values, mk.one_of(mk.sym(0)))),
            mk.rule(mk.sym(0), mk.sym(1), mk.kattr(.sum, "6..8"), mk.kattr(.values, mk.one_of(mk.sym(1)))),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0}, []int{0, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{1, 1}, []int{0, 1})),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 1),
            mk.field_node(
                mk.kattr(.for_, mk.sym(2)),
                mk.kattr(.from_, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
            ),
        ),
        mk.one(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{0, 0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0, 0},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, 4, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.steps, 1),
            mk.field_node(
                mk.kattr(.for_, mk.sym(4)),
                mk.kattr(.from_, mk.one_of(mk.sym(2))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
            ),
        ),
        mk.one(
            mk.rule(mk.in_exact_layer([]int{2, 0}), mk.out_exact_layer([]int{6, 2})),
            mk.rule(mk.in_exact_layer([]int{2, 1}), mk.out_exact_layer([]int{6, 3})),
            mk.rule(mk.in_exact_layer([]int{7, 1}), mk.out_exact_layer([]int{5, 3})),
            mk.rule(mk.in_exact_layer([]int{7, 0}), mk.out_exact_layer([]int{5, 2})),
            mk.rule(mk.in_exact_layer([]int{3}), mk.out_exact_layer([]int{7})),
            mk.observe_node(
                mk.kattr(.value, mk.sym(4)),
                mk.kattr(.from_, mk.sym(0)),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
            ),
            mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(6)))),
            mk.observe_node(mk.kattr(.value, mk.sym(1)), mk.kattr(.to, mk.one_of(mk.sym(1), mk.sym(5)))),
            mk.observe_node(mk.kattr(.value, mk.sym(2)), mk.kattr(.to, mk.one_of(mk.sym(6)))),
        ),
    )
}
