// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_dwarfpath :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(8)),
        mk.one(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 3, 3, 3, 3, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 3, mk.OUT_KEEP, mk.OUT_KEEP, 3, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 3, mk.OUT_KEEP, mk.OUT_KEEP, 3, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 3, 3, 3, 3, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 0, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 2, 2}, []int{2, 2, 2})),
            mk.kattr(.steps, 2),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 1),
        ),
        mk.markov_node(
            mk.one(
                mk.rule(mk.in_exact_layer([]int{5, 6}), mk.out_exact_layer([]int{0, 5})),
                mk.rule(mk.in_exact_layer([]int{5, 3}), mk.out_exact_layer([]int{1, 7})),
            ),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(5))),
                mk.kattr(.to, mk.one_of(mk.sym(3))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.color, mk.sym(6)),
                mk.kattr(.inertia, false),
            ),
            mk.one(
                mk.rule(mk.in_exact_layer([]int{1, 4}), mk.out_exact_layer([]int{0, 1})),
                mk.rule(mk.in_exact_layer([]int{1, 2}), mk.out_exact_layer([]int{0, 5})),
            ),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(1))),
                mk.kattr(.to, mk.one_of(mk.sym(2))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.color, mk.sym(4)),
                mk.kattr(.inertia, false),
            ),
        ),
    )
}
