// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_chaindungeon :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(5)),
        mk.all(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, 0, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 2, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
        ),
        mk.one(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2},
                    []int{2, 2, 2, 2, 2, 2, 2, 2},
                    []int{mk.IN_ANY, mk.IN_ANY, 2, 2, 2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, 2, 2, 2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    []int{mk.IN_ANY, mk.IN_ANY, 2, 2, 2, mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{0, 0, 0, 0, 0, 0, 0, 0},
                    []int{0, 4, 4, 4, 4, 4, 4, 0},
                    []int{0, 4, 4, 4, 4, 4, 4, 0},
                    []int{0, 4, 4, 4, 4, 4, 4, 0},
                    []int{0, 4, 4, 4, 4, 4, 4, 0},
                    []int{0, 0, 0, 4, 0, 0, 0, 0},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 0, 4, 0, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 0, 3, 0, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int {
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                        mk.OUT_KEEP,
                    },
                ),
            ),
            mk.kattr(.steps, 2),
        ),
        mk.markov_node(
            mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{1, 3})), mk.kattr(.out, mk.out_exact_layer([]int{1, 1}))),
            mk.path_node(
                mk.kattr(.from_, mk.one_of(mk.sym(1))),
                mk.kattr(.to, mk.one_of(mk.sym(3))),
                mk.kattr(.on, mk.one_of(mk.sym(2))),
                mk.kattr(.color, mk.sym(1)),
                mk.kattr(.inertia, false),
            ),
            mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
        ),
        mk.convchain_node(
            mk.kattr(.sample, "Room"),
            mk.kattr(.on, "B"),
            mk.kattr(.black, "D"),
            mk.kattr(.white, "A"),
            mk.kattr(.n, 3),
            mk.kattr(.steps, 10),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{1, 0}, []int{0, 1})),
            mk.kattr(.out, mk.out_exact_layer([]int{1, 0}, []int{1, 1})),
        ),
        mk.all(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 1, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{0, 0, 0}, []int{0, 0, 0})),
        ),
        mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{4, 1})), mk.kattr(.out, mk.out_exact_layer([]int{4, 4}))),
    )
}
