// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_gameoflife :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.p, 0.5),
            mk.kattr(.steps, 1),
        ),
        mk.convolution_node(
            mk.kattr(.neighborhood, "Moore"),
            mk.kattr(.periodic, true),
            mk.rule(mk.sym(0), mk.sym(1), mk.kattr(.sum, "3"), mk.kattr(.values, mk.one_of(mk.sym(1)))),
            mk.rule(mk.sym(1), mk.sym(0), mk.kattr(.sum, "0,1,4..8"), mk.kattr(.values, mk.one_of(mk.sym(1)))),
        ),
    )
}
