// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_growto :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(3)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{2, 0})),
            mk.kattr(.out, mk.out_exact_layer([]int{2, 2})),
            mk.kattr(.temperature, 10.0),
            mk.field_node(
                mk.kattr(.for_, mk.sym(2)),
                mk.kattr(.to, mk.one_of(mk.sym(1))),
                mk.kattr(.on, mk.one_of(mk.sym(0))),
                mk.kattr(.recompute, false),
            ),
        ),
    )
}
