// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_surface :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(1)),
        mk.wfc_node(mk.kattr(.values, mk.values_count(2)), mk.kattr(.tileset, "Surface")),
    )
}
