// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_oddscale3d :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(2)),
        mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_IDENTITY)),
        mk.prl(
            mk.kattr(
                .in_,
                mk.in_exact_layers(
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, 0, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                    [][]int {
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                        []int{mk.IN_ANY, mk.IN_ANY, mk.IN_ANY},
                    },
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layers(
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, 1, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                    [][]int {
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                        []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    },
                ),
            ),
        ),
        mk.prl(
            mk.kattr(.in_, mk.in_exact_layer([]int{1})),
            mk.kattr(.out, mk.out_exact_layer([]int{0})),
            mk.kattr(.p, 0.5),
            mk.kattr(.steps, 1),
        ),
        mk.map_node(
            mk.kattr(.scale, "6 6 6"),
            mk.kattr(.values, mk.values_count(6)),
            mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_IDENTITY)),
            mk.rule(
                mk.in_exact_layer([]int{1}),
                mk.out_exact_layers(
                    [][]int {
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                    },
                    [][]int {
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                    },
                    [][]int {
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                    },
                    [][]int {
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                    },
                    [][]int {
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                    },
                    [][]int {
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{1, 1, 1, 1, 1, 1, 1},
                    },
                    [][]int {
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                        []int{1, 1, 1, 1, 1, 1, 1},
                        []int{2, 1, 2, 1, 2, 1, 2},
                    },
                ),
            ),
            mk.sequence(
                mk.kattr(.symmetry, mk.symmetry_mask(mk.SYMMETRY_3D_ALL)),
                mk.kattr(.comment, ""),
                mk.all(
                    mk.rule(mk.in_exact_layer([]int{2, 0}), mk.out_exact_layer([]int{3, mk.OUT_KEEP})),
                    mk.rule(
                        mk.in_exact_layer([]int{2, mk.IN_ANY}, []int{mk.IN_ANY, 0}),
                        mk.out_exact_layer([]int{3, mk.OUT_KEEP}, []int{mk.OUT_KEEP, mk.OUT_KEEP}),
                    ),
                ),
                mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{2})), mk.kattr(.out, mk.out_exact_layer([]int{1}))),
                mk.markov_node(
                    mk.one(
                        mk.kattr(.in_, mk.in_exact_layer([]int{4, 1, 3})),
                        mk.kattr(.out, mk.out_exact_layer([]int{4, 5, 4})),
                    ),
                    mk.one(mk.kattr(.in_, mk.in_exact_layer([]int{3})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
                ),
                mk.all(mk.kattr(.in_, mk.in_exact_layer([]int{5})), mk.kattr(.out, mk.out_exact_layer([]int{4}))),
            ),
        ),
    )
}
