// Code generated by examples/gen_procedural.py. DO NOT EDIT.
package example

import mk "../.."

model_sequentialsokoban :: proc() -> mk.Proc_Node {
    return mk.sequence(
        mk.kattr(.values, mk.values_count(8)),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0})),
            mk.kattr(.out, mk.out_exact_layer([]int{1})),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(
                .in_,
                mk.in_exact_layer(
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                    []int{0, 0, 0, 0, 0, 0},
                ),
            ),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 3, 3, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, 3, 3, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.steps, 1),
        ),
        mk.one(
            mk.kattr(.in_, mk.in_exact_layer([]int{0, 0, 0}, []int{0, 0, 0}, []int{0, 0, 0})),
            mk.kattr(
                .out,
                mk.out_exact_layer(
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, 4, mk.OUT_KEEP},
                    []int{mk.OUT_KEEP, mk.OUT_KEEP, mk.OUT_KEEP},
                ),
            ),
            mk.kattr(.steps, 4),
        ),
        mk.markov_node(
            mk.one(
                mk.kattr(.search, true),
                mk.rule(mk.in_exact_layer([]int{1, 0}), mk.out_exact_layer([]int{0, 1})),
                mk.rule(mk.in_exact_layer([]int{1, 2, 0}), mk.out_exact_layer([]int{0, 1, 2})),
                mk.rule(mk.in_exact_layer([]int{1, 2, 7}), mk.out_exact_layer([]int{0, 1, 5})),
                mk.observe_node(mk.kattr(.value, mk.sym(0)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(1)))),
                mk.observe_node(mk.kattr(.value, mk.sym(1)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(1)))),
                mk.observe_node(mk.kattr(.value, mk.sym(2)), mk.kattr(.to, mk.one_of(mk.sym(0), mk.sym(1)))),
                mk.observe_node(
                    mk.kattr(.value, mk.sym(6)),
                    mk.kattr(.from_, mk.sym(7)),
                    mk.kattr(.to, mk.one_of(mk.sym(5))),
                ),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{4})),
                mk.kattr(.out, mk.out_exact_layer([]int{2})),
                mk.kattr(.steps, 1),
            ),
            mk.one(
                mk.kattr(.in_, mk.in_exact_layer([]int{3})),
                mk.kattr(.out, mk.out_exact_layer([]int{6})),
                mk.kattr(.steps, 1),
            ),
        ),
    )
}
